//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003ba0(void);
int32_t function_100003f3c(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003ba0 - 0x100003d50
int64_t function_100003ba0(void) {
    // 0x100003ba0
    int64_t result; // 0x100003ba0
    int32_t v1 = result; // 0x100003ba4
    int32_t v2 = 1; // 0x100003bd4
    int32_t v3 = 1; // 0x100003bd4
    int32_t v4 = v1; // 0x100003bd4
    int32_t v5 = 2; // 0x100003bd4
    int32_t v6 = 1; // 0x100003bd4
    int32_t v7 = 1; // 0x100003bd4
    if (v1 % 2 == 0) {
        uint32_t v8 = v1;
        v7++;
        v6 += v5;
        int32_t v9 = v8 / 2; // 0x100003c0c
        v2 = v7;
        v3 = v6;
        v4 = v9;
        v5 *= 2;
        while ((v8 & 2) == 0) {
            // 0x100003bdc
            v8 = v9;
            v7++;
            v6 += v5;
            v9 = v8 / 2;
            v2 = v7;
            v3 = v6;
            v4 = v9;
            v5 *= 2;
        }
    }
    int32_t v10 = v4;
    int32_t v11 = v3; // 0x100003c3c
    int32_t v12 = v2; // 0x100003c3c
    int32_t v13 = v2; // 0x100003c3c
    int32_t v14 = v3; // 0x100003c3c
    int32_t v15 = v10; // 0x100003c3c
    if (v10 <= 9 != v10 != 9) {
        uint32_t v16 = 3;
        int32_t v17 = v16; // 0x100003c78
        int32_t v18 = 1; // 0x100003c78
        int32_t v19 = v10; // 0x100003c78
        int32_t v20 = 1; // 0x100003c78
        int32_t v21; // 0x100003ba0
        int32_t v22; // 0x100003ba0
        int32_t v23; // 0x100003ba0
        int32_t v24; // 0x100003c94
        int32_t v25; // 0x100003cb8
        int32_t v26; // 0x100003c84
        if (v10 % v16 == 0) {
            v26 = 2;
            v24 = v17 + 1;
            v25 = v10 / v16;
            v22 = v24;
            v23 = v25;
            v21 = v26;
            v17 *= v16;
            v18 = v26;
            v19 = v25;
            v20 = v24;
            while (v25 % v16 == 0) {
                // 0x100003c80
                v26 = v21 + 1;
                v24 = v17 + v22;
                v25 = v23 / v16;
                v22 = v24;
                v23 = v25;
                v21 = v26;
                v17 *= v16;
                v18 = v26;
                v19 = v25;
                v20 = v24;
            }
        }
        int32_t v27 = v19;
        v12 *= v18;
        v11 *= v20;
        int32_t v28 = v16 + 2; // 0x100003cec
        uint32_t v29 = v28 * v28; // 0x100003c2c
        v13 = v12;
        v14 = v11;
        v15 = v27;
        while (v29 >= v27 != v29 != v27) {
            // 0x100003c5c
            v16 = v28;
            v23 = v27;
            v17 = v16;
            v18 = 1;
            v19 = v27;
            v20 = 1;
            if (v27 % v16 == 0) {
                v26 = 2;
                v24 = v17 + 1;
                v25 = v23 / v16;
                v22 = v24;
                v23 = v25;
                v21 = v26;
                v17 *= v16;
                v18 = v26;
                v19 = v25;
                v20 = v24;
                while (v25 % v16 == 0) {
                    // 0x100003c80
                    v26 = v21 + 1;
                    v24 = v17 + v22;
                    v25 = v23 / v16;
                    v22 = v24;
                    v23 = v25;
                    v21 = v26;
                    v17 *= v16;
                    v18 = v26;
                    v19 = v25;
                    v20 = v24;
                }
            }
            // 0x100003cc4
            v27 = v19;
            v12 *= v18;
            v11 *= v20;
            v28 = v16 + 2;
            v29 = v28 * v28;
            v13 = v12;
            v14 = v11;
            v15 = v27;
        }
    }
    int32_t v30 = v15;
    int32_t v31 = v13; // 0x100003d04
    int32_t v32 = v14; // 0x100003d04
    if (v30 != 1 && v30 != 0) {
        // 0x100003d0c
        v31 = 2 * v13;
        v32 = (v30 + 1) * v14;
    }
    // 0x100003d30
    *(int32_t *)result = v31;
    *(int32_t *)result = v32;
    return result;
}

// Address range: 0x100003d50 - 0x100003f3c
int64_t entry_point(void) {
    // 0x100003d50
    int32_t v1; // bp-36, 0x100003d50
    int32_t v2 = &v1;
    int32_t v3; // bp-40, 0x100003d50
    int32_t v4 = &v3;
    int32_t v5 = 0;
    function_100003ba0();
    int32_t v6 = v5; // 0x100003dbc
    int32_t v7; // 0x100003dcc
    if (v3 % v1 == 0) {
        // 0x100003dc8
        v7 = v5 + 1;
        if (v7 >= 100 != v7 != 100) {
            // 0x100003e0c
            _printf("%3u ", v2);
            if (v7 % 10 == 0) {
                // 0x100003e4c
                _printf("\n");
            }
        }
        // 0x100003e60
        v6 = v7;
        switch (v5) {
            case 0xf423f: {
            }
            case 0x1869f: {
            }
            case 0x270f: {
            }
            case 999: {
                // 0x100003ec4
                _printf("\n%uth arithmetic number is %u\n", v2, v4);
                _printf("Number of composite arithmetic numbers <= %u: %u\n", v2, v4);
                v6 = v7;
                // break -> 0x100003f1c
                break;
            }
        }
    }
    // 0x100003f1c
    while (v6 >= 0xf4240 != v6 != 0xf4240) {
        // 0x100003d90
        v5 = v6;
        function_100003ba0();
        v6 = v5;
        if (v3 % v1 == 0) {
            // 0x100003dc8
            v7 = v5 + 1;
            if (v7 >= 100 != v7 != 100) {
                // 0x100003e0c
                _printf("%3u ", v2);
                if (v7 % 10 == 0) {
                    // 0x100003e4c
                    _printf("\n");
                }
            }
            // 0x100003e60
            v6 = v7;
            switch (v5) {
                case 0xf423f: {
                }
                case 0x1869f: {
                }
                case 0x270f: {
                }
                case 999: {
                    // 0x100003ec4
                    _printf("\n%uth arithmetic number is %u\n", v2, v4);
                    _printf("Number of composite arithmetic numbers <= %u: %u\n", v2, v4);
                    v6 = v7;
                    // break -> 0x100003f1c
                    break;
                }
            }
        }
    }
    // 0x100003f2c
    return 0;
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(char * format, ...) {
    // 0x100003f3c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

