//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f80(char * a1, char * a2, int64_t a3, char * a4);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___assert_rtn(char * a1, char * a2, int64_t a3, char * a4);

// ------------------------ Functions -------------------------

// Address range: 0x100003f1c - 0x100003f80
int64_t entry_point(void) {
    // 0x100003f1c
    int32_t v1; // 0x100003f1c
    if (v1 != 42) {
        // 0x100003f4c
        ___assert_rtn("main", "assertions-1.c", 6, "a == 42");
    }
    // 0x100003f70
    return 0;
}

// Address range: 0x100003f80 - 0x100003f8c
int64_t function_100003f80(char * a1, char * a2, int64_t a3, char * a4) {
    // 0x100003f80
    return ___assert_rtn(a1, a2, a3, a4);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 2

