//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003b58(void);
int64_t function_100003b94(int64_t a1, int32_t a2, int32_t a3);
int64_t function_100003bd4(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003c1c(void);
int64_t * function_100003f20(int32_t nmemb, int32_t size);
void function_100003f2c(int64_t * ptr);
int32_t function_100003f38(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t * _calloc(int32_t a1, int32_t a2);
void _free(int64_t * a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003b58 - 0x100003b94
int64_t function_100003b58(void) {
    // 0x100003b58
    int64_t v1; // 0x100003b58
    int32_t v2 = v1; // 0x100003b5c
    return (v2 - 1) * v2 / 2 + (int32_t)v1;
}

// Address range: 0x100003b94 - 0x100003bd4
int64_t function_100003b94(int64_t a1, int32_t a2, int32_t a3) {
    // 0x100003b94
    return (int64_t)*(int32_t *)(4 * function_100003b58() + a1);
}

// Address range: 0x100003bd4 - 0x100003c1c
int64_t function_100003bd4(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    int64_t result = function_100003b58(); // 0x100003bf8
    *(int32_t *)(4 * result + a1) = (int32_t)a4;
    return result;
}

// Address range: 0x100003c1c - 0x100003d98
int64_t function_100003c1c(void) {
    // 0x100003c1c
    int64_t v1; // 0x100003c1c
    int32_t v2 = v1; // 0x100003c28
    int64_t result = (int64_t)_calloc((v2 + 1) * v2 / 2, 4); // 0x100003c64
    function_100003bd4(result, 1, 0, 1);
    int32_t v3 = 2 - v2; // 0x100003c94
    if (v3 != 0 && v3 < 0 == (v3 & v2) < 0) {
        // 0x100003d88
        return result;
    }
    uint32_t v4 = 2;
    int32_t v5 = v4 - 1; // 0x100003cc4
    int64_t v6 = function_100003b94(result, v5, v4 - 2); // 0x100003cd0
    int64_t v7 = v4; // 0x100003cd4
    function_100003bd4(result, v7, 0, v6);
    int32_t v8 = 1 - v4; // 0x100003cfc
    int32_t v9 = 1; // 0x100003d04
    int32_t v10; // 0x100003d18
    int64_t v11; // 0x100003d1c
    int32_t v12; // 0x100003d68
    int32_t v13; // 0x100003cfc
    if (v8 < 0 != (v8 & v4) < 0) {
        v10 = v9 - 1;
        v11 = function_100003b94(result, v4, v10);
        function_100003bd4(result, v7, (int64_t)v9, function_100003b94(result, v5, v10) + v11 & 0xffffffff);
        v12 = v9 + 1;
        v13 = v12 - v4;
        v9 = v12;
        while (v13 < 0 != ((v13 ^ v12) & (v12 ^ v4)) < 0) {
            // 0x100003d0c
            v10 = v9 - 1;
            v11 = function_100003b94(result, v4, v10);
            function_100003bd4(result, v7, (int64_t)v9, function_100003b94(result, v5, v10) + v11 & 0xffffffff);
            v12 = v9 + 1;
            v13 = v12 - v4;
            v9 = v12;
        }
    }
    int32_t v14 = v4 + 1; // 0x100003d7c
    while (v14 - v2 == 0 || v14 - v2 < 0 != ((v14 - v2 ^ v14) & (v14 ^ v2)) < 0) {
        // 0x100003ca4
        v4 = v14;
        v5 = v4 - 1;
        v6 = function_100003b94(result, v5, v4 - 2);
        v7 = v4;
        function_100003bd4(result, v7, 0, v6);
        v8 = 1 - v4;
        v9 = 1;
        if (v8 < 0 != (v8 & v4) < 0) {
            v10 = v9 - 1;
            v11 = function_100003b94(result, v4, v10);
            function_100003bd4(result, v7, (int64_t)v9, function_100003b94(result, v5, v10) + v11 & 0xffffffff);
            v12 = v9 + 1;
            v13 = v12 - v4;
            v9 = v12;
            while (v13 < 0 != ((v13 ^ v12) & (v12 ^ v4)) < 0) {
                // 0x100003d0c
                v10 = v9 - 1;
                v11 = function_100003b94(result, v4, v10);
                function_100003bd4(result, v7, (int64_t)v9, function_100003b94(result, v5, v10) + v11 & 0xffffffff);
                v12 = v9 + 1;
                v13 = v12 - v4;
                v9 = v12;
            }
        }
        // 0x100003d78
        v14 = v4 + 1;
    }
    // 0x100003d88
    return result;
}

// Address range: 0x100003d98 - 0x100003f20
int64_t entry_point(void) {
    int64_t v1 = function_100003c1c(); // 0x100003db0
    _printf("First fifteen Bell numbers:\n");
    uint32_t v2 = 1;
    function_100003b94(v1, v2, 0);
    _printf("%2d: %d\n", (int64_t)v2, 0);
    int32_t v3 = v2 + 1; // 0x100003e28
    while (v2 == 14 || v2 < 14 != (13 - v2 & v3) < 0) {
        // 0x100003de4
        v2 = v3;
        function_100003b94(v1, v2, 0);
        _printf("%2d: %d\n", (int64_t)v2, 0);
        v3 = v2 + 1;
    }
    // 0x100003e34
    _printf("\nThe first ten rows of Bell's triangle:\n");
    uint32_t v4 = 1;
    int64_t v5 = v4; // 0x100003e64
    function_100003b94(v1, v4, 0);
    _printf("%d", v5);
    int32_t v6 = 1 - v4; // 0x100003e9c
    int32_t v7 = 1; // 0x100003ea4
    int32_t v8; // 0x100003edc
    int32_t v9; // 0x100003e9c
    if (v6 < 0 != (v6 & v4) < 0) {
        function_100003b94(v1, v4, v7);
        _printf(", %d", v5);
        v8 = v7 + 1;
        v9 = v8 - v4;
        v7 = v8;
        while (v9 < 0 != ((v9 ^ v8) & (v8 ^ v4)) < 0) {
            // 0x100003eac
            function_100003b94(v1, v4, v7);
            _printf(", %d", v5);
            v8 = v7 + 1;
            v9 = v8 - v4;
            v7 = v8;
        }
    }
    // 0x100003ee8
    _printf((char *)0x100003f9b);
    int32_t v10 = v4 + 1; // 0x100003efc
    while (v4 == 9 || v4 < 9 != (8 - v4 & v10) < 0) {
        // 0x100003e60
        v4 = v10;
        v5 = v4;
        function_100003b94(v1, v4, 0);
        _printf("%d", v5);
        v6 = 1 - v4;
        v7 = 1;
        if (v6 < 0 != (v6 & v4) < 0) {
            function_100003b94(v1, v4, v7);
            _printf(", %d", v5);
            v8 = v7 + 1;
            v9 = v8 - v4;
            v7 = v8;
            while (v9 < 0 != ((v9 ^ v8) & (v8 ^ v4)) < 0) {
                // 0x100003eac
                function_100003b94(v1, v4, v7);
                _printf(", %d", v5);
                v8 = v7 + 1;
                v9 = v8 - v4;
                v7 = v8;
            }
        }
        // 0x100003ee8
        _printf((char *)0x100003f9b);
        v10 = v4 + 1;
    }
    // 0x100003f08
    _free((int64_t *)v1);
    return 0;
}

// Address range: 0x100003f20 - 0x100003f2c
int64_t * function_100003f20(int32_t nmemb, int32_t size) {
    // 0x100003f20
    return _calloc(nmemb, size);
}

// Address range: 0x100003f2c - 0x100003f38
void function_100003f2c(int64_t * ptr) {
    // 0x100003f2c
    _free(ptr);
}

// Address range: 0x100003f38 - 0x100003f44
int32_t function_100003f38(char * format, ...) {
    // 0x100003f38
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

