//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003c58(void);
int64_t function_100003cd4(void);
int32_t function_100003edc(int32_t x);
int32_t function_100003ee8(char * nptr);
void function_100003ef4(int32_t status);
int32_t function_100003f00(char * format, ...);
float64_t function_100003f0c(float64_t a1);

// --------------------- Global Variables ---------------------

float64_t g1 = 100.0; // 0x100003f18
float64_t g2 = 6.2831853071795862; // 0x100003f20

// ------- Dynamically Linked Functions Without Header --------

int32_t _abs(int32_t a1);
int32_t _atoi(char * a1);
int32_t _printf(char * a1, ...);
float64_t _sin(float64_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003c58 - 0x100003cd4
int64_t function_100003c58(void) {
    // 0x100003c58
    int64_t v1; // 0x100003c58
    int32_t v2 = v1; // 0x100003c5c
    int32_t v3 = v1; // 0x100003c60
    return (int32_t)v1 - 0xb25a2 + 367 * v2 + 275 * v3 / 9 + 7 * ((v3 + 9) / 12 + v2) / -4;
}

// Address range: 0x100003cd4 - 0x100003d9c
int64_t function_100003cd4(void) {
    // 0x100003cd4
    float64_t v1; // 0x100003cd4
    float64_t v2 = v1;
    int128_t v3 = __asm_sshll(0.0f, 0); // 0x100003cf4
    __asm_sshll(0.0f, 0);
    _sin((float64_t)(int64_t)v3);
    int32_t v4 = __asm_fcvtas(v2 * g2 / v2 * g1); // 0x100003d30
    int64_t v5; // 0x100003cd4
    _printf("%12s cycle: %3i%%", (char *)v5, v5);
    int32_t v6 = _abs(v4); // 0x100003d60
    if (v6 < 15 != (14 - v6 & v6) < 0) {
        // 0x100003d74
        _printf(" (critical day)");
    }
    // 0x100003d84
    return _printf("\n");
}

// Address range: 0x100003d9c - 0x100003edc
int64_t entry_point(void) {
    // 0x100003d9c
    int64_t v1; // 0x100003d9c
    int32_t v2 = v1; // 0x100003da8
    if (v2 < 7 != (6 - v2 & v2) < 0) {
        // 0x100003dc4
        _printf("Usage:\n");
        _printf("cbio y1 m1 d1 y2 m2 d2\n");
        _exit(1);
        // UNREACHABLE
    }
    // 0x100003de4
    _atoi((char *)*(int64_t *)(v1 + 8));
    _atoi((char *)*(int64_t *)(v1 + 16));
    _atoi((char *)*(int64_t *)(v1 + 24));
    int64_t v3 = function_100003c58(); // 0x100003e1c
    _atoi((char *)*(int64_t *)(v1 + 32));
    int32_t v4 = _atoi((char *)*(int64_t *)(v1 + 40)); // 0x100003e3c
    _atoi((char *)*(int64_t *)(v1 + 48));
    _abs((int32_t)v3 - (int32_t)function_100003c58());
    _printf("Age: %u days\n", v4);
    function_100003cd4();
    function_100003cd4();
    function_100003cd4();
    return 0;
}

// Address range: 0x100003edc - 0x100003ee8
int32_t function_100003edc(int32_t x) {
    // 0x100003edc
    return _abs(x);
}

// Address range: 0x100003ee8 - 0x100003ef4
int32_t function_100003ee8(char * nptr) {
    // 0x100003ee8
    return _atoi(nptr);
}

// Address range: 0x100003ef4 - 0x100003f00
void function_100003ef4(int32_t status) {
    // 0x100003ef4
    _exit(status);
}

// Address range: 0x100003f00 - 0x100003f0c
int32_t function_100003f00(char * format, ...) {
    // 0x100003f00
    return _printf(format);
}

// Address range: 0x100003f0c - 0x100003f18
float64_t function_100003f0c(float64_t a1) {
    // 0x100003f0c
    return _sin(a1);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

