//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003d84(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003f0c(int64_t a1);
int32_t function_100003f18(struct _IO_FILE * stream);
struct _IO_FILE * function_100003f24(char * filename, char * modes);
int32_t function_100003f30(struct _IO_FILE * stream, char * format, ...);
int32_t function_100003f3c(int64_t * ptr, int32_t size, int32_t n, struct _IO_FILE * s);
int32_t function_100003f48(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___chkstk_darwin(void);
int64_t ___stack_chk_fail(int64_t a1);
int32_t _fclose(struct _IO_FILE * a1);
struct _IO_FILE * _fopen(char * a1, char * a2);
int32_t _fprintf(struct _IO_FILE * a1, char * a2, ...);
int32_t _fwrite(int64_t * a1, int32_t a2, int32_t a3, struct _IO_FILE * a4);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d68 - 0x100003d84
int64_t entry_point(void) {
    // 0x100003d68
    return ___chkstk_darwin();
}

// Address range: 0x100003d84 - 0x100003f0c
int64_t function_100003d84(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003d84
    int64_t v1; // 0x100003d84
    int64_t * v2 = (int64_t *)(v1 - 24); // 0x100003d98
    *v2 = *(int64_t *)*(int64_t *)0x100004010;
    int64_t v3; // bp-10008, 0x100003d84
    for (int64_t i = 0; i < 100; i++) {
        int64_t v4 = 100 * i + (int64_t)&v3; // 0x100003e24
        int64_t v5 = 0;
        int32_t v6 = 0; // 0x100003d84
        *(char *)(v4 + v5) = (char)(v6 + (int32_t)i);
        v5++;
        v6++;
        while (v5 != 100) {
            // 0x100003e04
            *(char *)(v4 + v5) = (char)(v6 + (int32_t)i);
            v5++;
            v6++;
        }
    }
    struct _IO_FILE * v7 = _fopen("n.pgm", "wb"); // 0x100003e64
    _fprintf(v7, "P5\n %s\n %d\n %d\n %d\n", (char *)v1, v1, v1, v1);
    _fwrite(&v3, 0x2710, 1, v7);
    _fclose(v7);
    int32_t v8 = _printf("OK - file %s saved\n", (char *)0x2710); // 0x100003ecc
    if (*(int64_t *)*(int64_t *)0x100004010 != *v2) {
        // 0x100003ef0
        ___stack_chk_fail((int64_t)v8);
    }
    // 0x100003ef4
    return 0;
}

// Address range: 0x100003f0c - 0x100003f18
int64_t function_100003f0c(int64_t a1) {
    // 0x100003f0c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f18 - 0x100003f24
int32_t function_100003f18(struct _IO_FILE * stream) {
    // 0x100003f18
    return _fclose(stream);
}

// Address range: 0x100003f24 - 0x100003f30
struct _IO_FILE * function_100003f24(char * filename, char * modes) {
    // 0x100003f24
    return _fopen(filename, modes);
}

// Address range: 0x100003f30 - 0x100003f3c
int32_t function_100003f30(struct _IO_FILE * stream, char * format, ...) {
    // 0x100003f30
    return _fprintf(stream, format);
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(int64_t * ptr, int32_t size, int32_t n, struct _IO_FILE * s) {
    // 0x100003f3c
    return _fwrite(ptr, size, n, s);
}

// Address range: 0x100003f48 - 0x100003f54
int32_t function_100003f48(char * format, ...) {
    // 0x100003f48
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

