//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003e28(void);
int32_t function_100003f94(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 1; // 0x100008000

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003e28 - 0x100003f5c
int64_t function_100003e28(void) {
    // 0x100003e28
    int64_t v1; // 0x100003e28
    int32_t v2 = v1; // 0x100003e34
    int32_t v3 = v1; // 0x100003e38
    int32_t v4 = v3 + (int32_t)v1; // 0x100003e50
    int32_t v5 = v2 - v4; // 0x100003e54
    if (v5 < 0 != ((v5 ^ v2) & (v4 ^ v2)) < 0) {
        // 0x100003f50
        int64_t result; // 0x100003e28
        return result;
    }
    if (v3 != 0) {
        // 0x100003f04
        function_100003e28();
        // 0x100003f50
        return function_100003e28();
    }
    int32_t v6 = -v2; // 0x100003e8c
    int32_t v7 = 0; // 0x100003e94
    if (v6 < 0 != (v6 & v2) < 0) {
        if ((g1 << (int64_t)v7 & v1) != 0) {
            // 0x100003ec0
            _printf("%d ", v1);
        }
        // 0x100003ee4
        v7++;
        while (v7 - v2 < 0 != ((v7 - v2 ^ v7) & (v7 ^ v2)) < 0) {
            // 0x100003e9c
            if ((g1 << (int64_t)v7 & v1) != 0) {
                // 0x100003ec0
                _printf("%d ", v1);
            }
            // 0x100003ee4
            v7++;
        }
    }
    // 0x100003f50
    return _printf((char *)0x100003fa4);
}

// Address range: 0x100003f5c - 0x100003f94
int64_t entry_point(void) {
    // 0x100003f5c
    function_100003e28();
    return 0;
}

// Address range: 0x100003f94 - 0x100003fa0
int32_t function_100003f94(char * format, ...) {
    // 0x100003f94
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

