//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int32_t function_100003cc0(struct _IO_FILE * stream);
struct _IO_FILE * function_100003ccc(char * filename, char * modes);
int32_t function_100003cd8(struct _IO_FILE * stream, char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _fclose(struct _IO_FILE * a1);
struct _IO_FILE * _fopen(char * a1, char * a2);
int32_t _fprintf(struct _IO_FILE * a1, char * a2, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003bf8 - 0x100003cc0
int64_t entry_point(void) {
    struct _IO_FILE * v1 = _fopen("TAPE.FILE", "w"); // 0x100003c20
    _fprintf(v1, "This code should be able to write a file to magnetic tape.\n");
    _fprintf(v1, "The Wikipedia page on Magnetic tape data storage shows that magnetic tapes are still in use.\n");
    _fprintf(v1, "In fact, the latest format, at the time of writing this code is TS1155 released in 2017.\n");
    _fprintf(v1, "And since C is already 44, maybe 45, years old in 2017, I am sure someone somewhere did use a C compiler on magnetic tapes.\n");
    _fprintf(v1, "If you happen to have one, please try to compile and execute me on that system.\n");
    _fprintf(v1, "My creator tested me on an i5 machine with SSD and RAM that couldn't have even been dreamt of by Denis Ritchie.\n");
    _fprintf(v1, "Who knows ? Maybe he did foresee today, after all he created something which is still young after 44-45 years and counting...\n");
    _fprintf(v1, "EOF");
    _fclose(v1);
    return 0;
}

// Address range: 0x100003cc0 - 0x100003ccc
int32_t function_100003cc0(struct _IO_FILE * stream) {
    // 0x100003cc0
    return _fclose(stream);
}

// Address range: 0x100003ccc - 0x100003cd8
struct _IO_FILE * function_100003ccc(char * filename, char * modes) {
    // 0x100003ccc
    return _fopen(filename, modes);
}

// Address range: 0x100003cd8 - 0x100003ce4
int32_t function_100003cd8(struct _IO_FILE * stream, char * format, ...) {
    // 0x100003cd8
    return _fprintf(stream, format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

