//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int32_t function_100003e08(char * format, ...);
int32_t function_100003e14(int32_t c);
int32_t function_100003e20(char * s);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _putchar(int32_t a1);
int32_t _puts(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003cc8 - 0x100003e08
int64_t entry_point(void) {
    // 0x100003cc8
    _printf("<table>\n<tr><td>");
    char * v1 = (char *)0x3e2c; // 0x100003cf0
    while (true) {
        char v2 = *v1; // 0x100003cf8
        switch (v2) {
            case 0: {
                // 0x100003dec
                _puts("</td></tr>\n</table>");
                return 0;
            }
            case 10: {
                // 0x100003d78
                _printf("</td></tr>\n<tr><td>");
                // break -> 0x100003ddc
                break;
            }
            case 38: {
                // 0x100003db8
                _printf("&amp;");
                // break -> 0x100003ddc
                break;
            }
            case 44: {
                // 0x100003d88
                _printf("</td><td>");
                // break -> 0x100003ddc
                break;
            }
            case 60: {
                // 0x100003d98
                _printf("&lt;");
                // break -> 0x100003ddc
                break;
            }
            case 62: {
                // 0x100003da8
                _printf("&gt;");
                // break -> 0x100003ddc
                break;
            }
            default: {
                // 0x100003dc8
                _putchar((int32_t)v2);
                // break -> 0x100003ddc
                break;
            }
        }
        // 0x100003ddc
        v1 = (char *)((int64_t)v1 + 1);
    }
    // 0x100003dec
    _puts("</td></tr>\n</table>");
    return 0;
}

// Address range: 0x100003e08 - 0x100003e14
int32_t function_100003e08(char * format, ...) {
    // 0x100003e08
    return _printf(format);
}

// Address range: 0x100003e14 - 0x100003e20
int32_t function_100003e14(int32_t c) {
    // 0x100003e14
    return _putchar(c);
}

// Address range: 0x100003e20 - 0x100003e2c
int32_t function_100003e20(char * s) {
    // 0x100003e20
    return _puts(s);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

