//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int32_t function_100003f7c(char * filename);

// ------- Dynamically Linked Functions Without Header --------

int32_t _remove(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003f24 - 0x100003f7c
int64_t entry_point(void) {
    // 0x100003f24
    _remove("input.txt");
    _remove("/input.txt");
    _remove("docs");
    _remove("/docs");
    return 0;
}

// Address range: 0x100003f7c - 0x100003f88
int32_t function_100003f7c(char * filename) {
    // 0x100003f7c
    return _remove(filename);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 2

