//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003a80(void);
int64_t function_100003b0c(void);
int64_t function_100003c7c(void);
int64_t function_100003cb8(int64_t a1, int64_t a2, int32_t a3);
int64_t function_100003d08(void);
int64_t function_100003e94(int64_t a1);
int64_t * function_100003ea0(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003eac(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x100003eb8

// ------- Dynamically Linked Functions Without Header --------

int64_t ___chkstk_darwin(void);
int64_t ___stack_chk_fail(int64_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003a80 - 0x100003b0c
int64_t function_100003a80(void) {
    // 0x100003a80
    int64_t v1; // 0x100003a80
    if ((int32_t)v1 == 1) {
        // 0x100003abc
        return function_100003c7c();
    }
    // 0x100003ad0
    return ___chkstk_darwin();
}

// Address range: 0x100003b0c - 0x100003c7c
int64_t function_100003b0c(void) {
    // 0x100003b0c
    int64_t v1; // 0x100003b0c
    int64_t v2 = v1;
    int64_t * v3 = (int64_t *)(v2 - 80); // 0x100003b1c
    int64_t v4; // 0x100003b0c
    *v3 = (int64_t)&v4 - *(int64_t *)(v2 - 88);
    int32_t * v5 = (int32_t *)(v2 - 60); // 0x100003b24
    *v5 = 0;
    int32_t * v6 = (int32_t *)(v2 - 28); // 0x100003b30
    int32_t v7 = *v6; // 0x100003b30
    int32_t v8 = -v7; // 0x100003b34
    if (v8 < 0 != (v7 & v8) < 0) {
        int32_t v9 = 0; // 0x100003b6c
        int64_t v10 = *(int64_t *)(*(int64_t *)(v2 - 24) + (int64_t)(8 * v9 + 8)); // 0x100003b54
        *(int64_t *)(8 * (int64_t)v9 + *v3) = v10 + 8;
        v9 = *v5 + 1;
        *v5 = v9;
        int32_t v11 = *v6; // 0x100003b30
        while (v9 - v11 < 0 != ((v9 - v11 ^ v9) & (v11 ^ v9)) < 0) {
            // 0x100003b44
            v10 = *(int64_t *)(*(int64_t *)(v2 - 24) + (int64_t)(8 * v9 + 8));
            *(int64_t *)(8 * (int64_t)v9 + *v3) = v10 + 8;
            v9 = *v5 + 1;
            *v5 = v9;
            v11 = *v6;
        }
    }
    int32_t * v12 = (int32_t *)(v2 - 64); // 0x100003b78
    *v12 = 0;
    int32_t * v13 = (int32_t *)(v2 - 68); // 0x100003b80
    *v13 = 1;
    int32_t v14 = *v12; // 0x100003b88
    int32_t v15 = *v6; // 0x100003b8c
    int32_t v16 = v14 - v15; // 0x100003b90
    if (v16 != 0 && v16 < 0 == ((v16 ^ v14) & (v15 ^ v14)) < 0) {
        // 0x100003c68
        *(int64_t *)(v2 - 16) = *(int64_t *)(v2 - 40);
        return function_100003c7c();
    }
    int64_t v17 = v2 - 96;
    int64_t * v18 = (int64_t *)(v2 - 24);
    float64_t * v19 = (float64_t *)(v2 - 104);
    int64_t v20 = v2 - 40;
    float64_t * v21 = (float64_t *)v20;
    __asm_sshll(0.0f, 0);
    float64_t v22; // 0x100003b0c
    *(int64_t *)v17 = (int64_t)v22;
    float64_t v23 = *(float64_t *)*(int64_t *)(8 * (int64_t)*v12 + *v18); // 0x100003bc4
    *v19 = v23;
    function_100003a80();
    float64_t v24 = *v21 + *(float64_t *)v17 * v23 * *v19; // 0x100003bec
    *v21 = v24;
    int32_t v25 = *v12; // 0x100003bf4
    while (v25 != *v6) {
        int64_t v26 = 8 * (int64_t)v25; // 0x100003c1c
        *(int64_t *)(*v3 + v26) = *(int64_t *)(*v18 + v26) + 8;
        if (*(int32_t *)(v2 - 32) == 0) {
            // 0x100003c40
            *v13 = -*v13;
        }
        int32_t v27 = *v12 + 1; // 0x100003c5c
        *v12 = v27;
        int32_t v28 = *v6; // 0x100003b8c
        int32_t v29 = v27 - v28; // 0x100003b90
        if (v29 != 0 && v29 < 0 == ((v29 ^ v27) & (v28 ^ v27)) < 0) {
            // break -> 0x100003c68
            break;
        }
        __asm_sshll(0.0f, 0);
        *(int64_t *)v17 = (int64_t)v24;
        v23 = *(float64_t *)*(int64_t *)(8 * (int64_t)*v12 + *v18);
        *v19 = v23;
        function_100003a80();
        v24 = *v21 + *(float64_t *)v17 * v23 * *v19;
        *v21 = v24;
        v25 = *v12;
    }
    // 0x100003c68
    *(int64_t *)(v2 - 16) = *(int64_t *)v20;
    return function_100003c7c();
}

// Address range: 0x100003c7c - 0x100003cb8
int64_t function_100003c7c(void) {
    // 0x100003c7c
    int64_t v1; // 0x100003c7c
    int64_t v2 = v1;
    *(int64_t *)(v2 - 112) = *(int64_t *)(v2 - 16);
    int64_t result; // 0x100003c7c
    if (*(int64_t *)*(int64_t *)0x100004010 != *(int64_t *)(v2 - 8)) {
        // 0x100003ca4
        result = ___stack_chk_fail(v1);
    }
    // 0x100003ca8
    return result;
}

// Address range: 0x100003cb8 - 0x100003d08
int64_t function_100003cb8(int64_t a1, int64_t a2, int32_t a3) {
    // 0x100003cb8
    return ___chkstk_darwin();
}

// Address range: 0x100003d08 - 0x100003dcc
int64_t function_100003d08(void) {
    // 0x100003d08
    int64_t v1; // 0x100003d08
    int64_t v2 = v1;
    int64_t * v3 = (int64_t *)(v2 - 56); // 0x100003d18
    int64_t v4; // 0x100003d08
    *v3 = (int64_t)&v4 - *(int64_t *)(v2 - 64);
    int32_t * v5 = (int32_t *)(v2 - 44); // 0x100003d20
    *v5 = 0;
    int32_t * v6 = (int32_t *)(v2 - 20); // 0x100003d2c
    int32_t v7 = *v6; // 0x100003d2c
    int32_t v8 = -v7; // 0x100003d30
    if (v8 < 0 != (v7 & v8) < 0) {
        int32_t v9 = 0;
        int64_t v10 = *v3; // 0x100003d40
        int64_t v11 = *(int64_t *)(v2 - 16); // 0x100003d44
        *(int64_t *)(8 * (int64_t)v9 + v10) = 8 * (int64_t)(v9 * v7) + v11;
        int32_t v12 = *v5 + 1; // 0x100003d68
        *v5 = v12;
        int32_t v13 = *v6; // 0x100003d2c
        while (v12 - v13 < 0 != ((v12 - v13 ^ v12) & (v13 ^ v12)) < 0) {
            // 0x100003d40
            v9 = v12;
            v10 = *v3;
            v11 = *(int64_t *)(v2 - 16);
            *(int64_t *)(8 * (int64_t)v9 + v10) = 8 * (int64_t)(v9 * v13) + v11;
            v12 = *v5 + 1;
            *v5 = v12;
            v13 = *v6;
        }
    }
    int64_t v14 = function_100003a80(); // 0x100003d80
    float64_t v15; // 0x100003d08
    *(int64_t *)(v2 - 80) = (int64_t)v15;
    *(int64_t *)(v2 - 72) = *(int64_t *)(v2 - 32);
    int64_t result = v14; // 0x100003da8
    if (*(int64_t *)*(int64_t *)0x100004010 != *(int64_t *)(v2 - 8)) {
        // 0x100003db0
        result = ___stack_chk_fail(v14);
    }
    // 0x100003db4
    return result;
}

// Address range: 0x100003dcc - 0x100003e94
int64_t entry_point(void) {
    // 0x100003dcc
    int64_t v1; // bp-240, 0x100003dcc
    int64_t v2 = &v1; // 0x100003dfc
    _memcpy(&v1, &g1, 200);
    function_100003cb8(v2, 5, 0);
    int128_t v3; // 0x100003dcc
    _printf("det:  %14.12g\n", (float64_t)(int64_t)v3);
    function_100003cb8(v2, 5, 1);
    int32_t v4 = _printf("perm: %14.12g\n", (float64_t)(int64_t)v3); // 0x100003e58
    int64_t v5 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003e68
    if (v5 != *(int64_t *)*(int64_t *)0x100004010) {
        // 0x100003e7c
        ___stack_chk_fail((int64_t)v4);
    }
    // 0x100003e80
    return 0;
}

// Address range: 0x100003e94 - 0x100003ea0
int64_t function_100003e94(int64_t a1) {
    // 0x100003e94
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003ea0 - 0x100003eac
int64_t * function_100003ea0(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003ea0
    return _memcpy(dest, src, n);
}

// Address range: 0x100003eac - 0x100003eb8
int32_t function_100003eac(char * format, ...) {
    // 0x100003eac
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

