//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
void function_100003f54(int64_t * ptr);
int64_t * function_100003f60(int32_t size);
int32_t function_100003f6c(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

void _free(int64_t * a1);
int64_t * _malloc(int32_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d9c - 0x100003f54
int64_t entry_point(void) {
    int64_t * v1 = _malloc(0x17d78404); // 0x100003dc8
    int64_t v2 = (int64_t)v1; // 0x100003dc8
    int64_t * v3 = _malloc(0x17d78404); // 0x100003dd8
    int64_t v4 = (int64_t)v3; // 0x100003dd8
    int32_t v5 = 0;
    int64_t v6 = 4 * (int64_t)v5; // 0x100003e0c
    *(int32_t *)(v6 + v2) = 1;
    *(int32_t *)(v6 + v4) = 1;
    int32_t v7 = v5 + 1; // 0x100003e24
    int32_t v8 = v5 - 0x5f5e0ff; // 0x100003df0
    while (v8 == 0 || v8 < 0 != (0x5f5e0fe - v5 & v7) < 0) {
        // 0x100003e00
        v5 = v7;
        v6 = 4 * (int64_t)v5;
        *(int32_t *)(v6 + v2) = 1;
        *(int32_t *)(v6 + v4) = 1;
        v7 = v5 + 1;
        v8 = v5 - 0x5f5e0ff;
    }
    int32_t v9 = 2;
    int32_t v10 = 2 * v9; // 0x100003e5c
    int32_t v11 = v10 - 0x5f5e100; // 0x100003e70
    int32_t v12 = v10; // 0x100003e78
    int32_t v13; // 0x100003d9c
    int64_t v14; // 0x100003e88
    int32_t * v15; // 0x100003e88
    int32_t v16; // 0x100003e88
    int32_t * v17; // 0x100003efc
    int64_t v18; // 0x100003d9c
    int32_t v19; // 0x100003f14
    int32_t v20; // 0x100003e70
    if (v11 == 0 || v11 < 0 != (0x5f5e0ff - v10 & v10) < 0) {
        v14 = 4 * (int64_t)v12;
        v15 = (int32_t *)(v14 + v2);
        v16 = *v15;
        v13 = v16;
        if (v16 == v12) {
            // 0x100003ea0
            _printf("%8d equals the sum of its first %d divisors\n", v18, v18);
            v13 = *v15;
        }
        // 0x100003ed4
        *v15 = v13 + v9;
        v17 = (int32_t *)(v14 + v4);
        *v17 = *v17 + 1;
        v19 = v12 + v9;
        v20 = v19 - 0x5f5e100;
        v12 = v19;
        while (v20 == 0 || v20 < 0 != (0x5f5e0ff - v19 & v19) < 0) {
            // 0x100003e80
            v14 = 4 * (int64_t)v12;
            v15 = (int32_t *)(v14 + v2);
            v16 = *v15;
            v13 = v16;
            if (v16 == v12) {
                // 0x100003ea0
                _printf("%8d equals the sum of its first %d divisors\n", v18, v18);
                v13 = *v15;
            }
            // 0x100003ed4
            *v15 = v13 + v9;
            v17 = (int32_t *)(v14 + v4);
            *v17 = *v17 + 1;
            v19 = v12 + v9;
            v20 = v19 - 0x5f5e100;
            v12 = v19;
        }
    }
    int32_t v21 = v9 + 1; // 0x100003f28
    int32_t v22 = v9 - 0x5f5e0ff; // 0x100003e44
    while (v22 == 0 || v22 < 0 != (0x5f5e0fe - v9 & v21) < 0) {
        // 0x100003e54
        v9 = v21;
        v10 = 2 * v9;
        v11 = v10 - 0x5f5e100;
        v12 = v10;
        if (v11 == 0 || v11 < 0 != (0x5f5e0ff - v10 & v10) < 0) {
            v14 = 4 * (int64_t)v12;
            v15 = (int32_t *)(v14 + v2);
            v16 = *v15;
            v13 = v16;
            if (v16 == v12) {
                // 0x100003ea0
                _printf("%8d equals the sum of its first %d divisors\n", v18, v18);
                v13 = *v15;
            }
            // 0x100003ed4
            *v15 = v13 + v9;
            v17 = (int32_t *)(v14 + v4);
            *v17 = *v17 + 1;
            v19 = v12 + v9;
            v20 = v19 - 0x5f5e100;
            v12 = v19;
            while (v20 == 0 || v20 < 0 != (0x5f5e0ff - v19 & v19) < 0) {
                // 0x100003e80
                v14 = 4 * (int64_t)v12;
                v15 = (int32_t *)(v14 + v2);
                v16 = *v15;
                v13 = v16;
                if (v16 == v12) {
                    // 0x100003ea0
                    _printf("%8d equals the sum of its first %d divisors\n", v18, v18);
                    v13 = *v15;
                }
                // 0x100003ed4
                *v15 = v13 + v9;
                v17 = (int32_t *)(v14 + v4);
                *v17 = *v17 + 1;
                v19 = v12 + v9;
                v20 = v19 - 0x5f5e100;
                v12 = v19;
            }
        }
        // 0x100003f24
        v21 = v9 + 1;
        v22 = v9 - 0x5f5e0ff;
    }
    // 0x100003f34
    _free(v1);
    _free(v3);
    return 0;
}

// Address range: 0x100003f54 - 0x100003f60
void function_100003f54(int64_t * ptr) {
    // 0x100003f54
    _free(ptr);
}

// Address range: 0x100003f60 - 0x100003f6c
int64_t * function_100003f60(int32_t size) {
    // 0x100003f60
    return _malloc(size);
}

// Address range: 0x100003f6c - 0x100003f78
int32_t function_100003f6c(char * format, ...) {
    // 0x100003f6c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

