//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003d68(void);
int64_t function_100003d88(void);
int64_t function_100003da8(void);
int64_t function_100003dc8(void);
int32_t function_100003f4c(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d68 - 0x100003d88
int64_t function_100003d68(void) {
    // 0x100003d68
    int64_t v1; // 0x100003d68
    int64_t result = v1;
    *(int32_t *)result = (int32_t)result >> 1;
    return result;
}

// Address range: 0x100003d88 - 0x100003da8
int64_t function_100003d88(void) {
    // 0x100003d88
    int64_t v1; // 0x100003d88
    int64_t result = v1;
    *(int32_t *)result = 2 * (int32_t)result;
    return result;
}

// Address range: 0x100003da8 - 0x100003dc8
int64_t function_100003da8(void) {
    // 0x100003da8
    int64_t v1; // 0x100003da8
    return (uint64_t)v1 % 2 == 0;
}

// Address range: 0x100003dc8 - 0x100003ef8
int64_t function_100003dc8(void) {
    // 0x100003dc8
    int64_t v1; // 0x100003dc8
    uint64_t v2 = v1;
    if (v2 % 2 != 0) {
        // 0x100003df8
        _printf("ethiopian multiplication of %d by %d\n", v1, v2);
    }
    // 0x100003e24
    if ((int32_t)v1 < 1 != ((int32_t)v1 & -(int32_t)v1) < 0) {
        // 0x100003ee8
        return 0;
    }
    // 0x100003e24
    while (true) {
        // 0x100003e3c
        if (function_100003da8() % 2 == 0) {
            if (v2 % 2 != 0) {
                // 0x100003e94
                _printf("%4d %6d kept\n", v1, v2);
            }
        } else {
            if (v2 % 2 != 0) {
                // 0x100003e58
                _printf("%4d %6d struck\n", v1, v2);
            }
        }
        // 0x100003ed4
        function_100003d68();
        function_100003d88();
    }
}

// Address range: 0x100003ef8 - 0x100003f4c
int64_t entry_point(void) {
    // 0x100003ef8
    function_100003dc8();
    _printf("%d\n", 34);
    return 0;
}

// Address range: 0x100003f4c - 0x100003f58
int32_t function_100003f4c(char * format, ...) {
    // 0x100003f4c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

