//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <setjmp.h>
#include <stdint.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _TYPEDEF___sigset_t {
    int32_t e0[1];
};

struct __jmp_buf_tag {
    int32_t e0[8];
    int32_t e1;
    struct _TYPEDEF___sigset_t e2;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003b84(void);
int64_t function_100003bec(void);
int64_t function_100003c68(int64_t a1);
int64_t function_100003ed0(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003f08(void);
void function_100003f14(int32_t status);
void function_100003f20(struct __jmp_buf_tag env[1], int32_t val);
int32_t function_100003f2c(char * format, ...);
int32_t function_100003f38(struct __jmp_buf_tag env[1]);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(void);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003b84 - 0x100003bec
int64_t function_100003b84(void) {
    int32_t v1[8]; // 0x100003bc0
    struct __jmp_buf_tag v2; // 0x100003bc0
    struct __jmp_buf_tag env[1]; // 0x100003bc0
    // 0x100003b84
    int64_t v3; // 0x100003b84
    int32_t v4 = v3; // 0x100003b90
    _printf("g !\n");
    int64_t v5; // 0x100003b84
    if (v4 != 0) {
        // 0x100003bb8
        v1[0] = v4;
        v2 = (struct {int32_t e0[8]; int32_t e1; struct _TYPEDEF___sigset_t e2;}){
            .e1 = 0,
            .e2 = (struct {int32_t e0[1];}){
                .e0 = {0}
            }
        };
        v2.e0 = v1;
        env[0] = v2;
        _longjmp(env, 1);
        v5 = 1;
    }
    // 0x100003bc4
    _printf("uncaught exception %d\n", v5);
    _exit(1);
    return &g1;
}

// Address range: 0x100003bec - 0x100003c68
int64_t function_100003bec(void) {
    int32_t v1[8]; // 0x100003c3c
    struct __jmp_buf_tag v2; // 0x100003c3c
    struct __jmp_buf_tag env[1]; // 0x100003c3c
    // 0x100003bec
    int64_t v3; // 0x100003bec
    int32_t v4 = v3; // 0x100003bf8
    _printf("h %d!\n", v3);
    int64_t v5; // 0x100003bec
    if (v4 != 0) {
        // 0x100003c34
        v1[0] = v4;
        v2 = (struct {int32_t e0[8]; int32_t e1; struct _TYPEDEF___sigset_t e2;}){
            .e1 = 0,
            .e2 = (struct {int32_t e0[1];}){
                .e0 = {0}
            }
        };
        v2.e0 = v1;
        env[0] = v2;
        _longjmp(env, 2);
        v5 = 2;
    }
    // 0x100003c40
    _printf("uncaught exception %d\n", v5);
    _exit(2);
    return &g1;
}

// Address range: 0x100003c68 - 0x100003d98
int64_t function_100003c68(int64_t a1) {
    struct __jmp_buf_tag env2[1]; // 0x100003d38
    int32_t v1[8]; // 0x100003ca0
    struct __jmp_buf_tag v2; // 0x100003ca0
    struct __jmp_buf_tag env[1]; // 0x100003ca0
    int32_t v3[8]; // 0x100003d38
    struct __jmp_buf_tag v4; // 0x100003d38
    // 0x100003c68
    int64_t v5; // bp-232, 0x100003c68
    v1[0] = &v5;
    v2 = (struct {int32_t e0[8]; int32_t e1; struct _TYPEDEF___sigset_t e2;}){
        .e1 = 0,
        .e2 = (struct {int32_t e0[1];}){
            .e0 = {0}
        }
    };
    v2.e0 = v1;
    env[0] = v2;
    uint32_t val = _setjmp(env); // 0x100003ca0
    switch (val) {
        case 0: {
            // 0x100003cc0
            function_100003b84();
            // UNREACHABLE
        }
        case 1: {
            // 0x100003cf8
            _printf("exception 1\n");
            function_100003bec();
            // UNREACHABLE
        }
    }
    // 0x100003d1c
    int64_t v6; // 0x100003c68
    int32_t v7 = v6; // 0x100003c90
    int64_t v8; // 0x100003c68
    if (v7 != 0) {
        // 0x100003d30
        v3[0] = v7;
        v4 = (struct {int32_t e0[8]; int32_t e1; struct _TYPEDEF___sigset_t e2;}){
            .e1 = 0,
            .e2 = (struct {int32_t e0[1];}){
                .e0 = {0}
            }
        };
        v4.e0 = v3;
        env2[0] = v4;
        _longjmp(env2, val);
        v8 = val;
    }
    // 0x100003d3c
    _printf("uncaught exception %d\n", v8);
    _exit(val);
    // UNREACHABLE
}

// Address range: 0x100003d98 - 0x100003ed0
int64_t entry_point(void) {
    int32_t v1[8]; // 0x100003ddc
    struct __jmp_buf_tag v2; // 0x100003ddc
    struct __jmp_buf_tag env[1]; // 0x100003ddc
    // 0x100003d98
    int64_t v3; // bp-232, 0x100003d98
    v1[0] = &v3;
    v2 = (struct {int32_t e0[8]; int32_t e1; struct _TYPEDEF___sigset_t e2;}){
        .e1 = 0,
        .e2 = (struct {int32_t e0[1];}){
            .e0 = {0}
        }
    };
    v2.e0 = v1;
    env[0] = v2;
    int32_t status = _setjmp(env); // 0x100003ddc
    switch (status) {
        case 0: {
            // 0x100003dfc
            function_100003c68(0);
            // break -> 0x100003ec4
            break;
        }
        case 2: {
            // 0x100003e4c
            _printf("exception 2\n");
            // break -> 0x100003ec4
            break;
        }
        case 3: {
            // 0x100003e64
            _printf("exception 3\n");
            // break -> 0x100003ec4
            break;
        }
        default: {
            // 0x100003e9c
            int64_t v4; // 0x100003d98
            _printf("uncaught exception %d\n", v4);
            _exit(status);
            // UNREACHABLE
        }
    }
    // 0x100003ec4
    function_100003bec();
    // UNREACHABLE
}

// Address range: 0x100003ed0 - 0x100003f08
int64_t function_100003ed0(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003ed0
    int64_t v1; // 0x100003ed0
    if (*(int64_t *)*(int64_t *)0x100004008 != *(int64_t *)(v1 - 24)) {
        // 0x100003ef0
        ___stack_chk_fail();
    }
    // 0x100003ef4
    return 0;
}

// Address range: 0x100003f08 - 0x100003f14
int64_t function_100003f08(void) {
    // 0x100003f08
    return ___stack_chk_fail();
}

// Address range: 0x100003f14 - 0x100003f20
void function_100003f14(int32_t status) {
    // 0x100003f14
    _exit(status);
}

// Address range: 0x100003f20 - 0x100003f2c
void function_100003f20(struct __jmp_buf_tag env[1], int32_t val) {
    // 0x100003f20
    _longjmp(env, val);
}

// Address range: 0x100003f2c - 0x100003f38
int32_t function_100003f2c(char * format, ...) {
    // 0x100003f2c
    return _printf(format);
}

// Address range: 0x100003f38 - 0x100003f44
int32_t function_100003f38(struct __jmp_buf_tag env[1]) {
    // 0x100003f38
    return _setjmp(env);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

