//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int32_t function_100003f98(char * command);

// ------- Dynamically Linked Functions Without Header --------

int32_t _system(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003f64 - 0x100003f98
int64_t entry_point(void) {
    // 0x100003f64
    _system("ls");
    return 0;
}

// Address range: 0x100003f98 - 0x100003fa4
int32_t function_100003f98(char * command) {
    // 0x100003f98
    return _system(command);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 2

