//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f64(void);
int32_t function_100003f70(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(void);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d80 - 0x100003f64
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003d94
    int64_t v2 = 1; // bp-120, 0x100003da4
    int64_t v3 = &v2;
    int64_t v4 = 1;
    int64_t v5 = 8 * v4 + v3;
    *(int64_t *)v5 = *(int64_t *)(v5 - 8) * v4;
    v4++;
    while (v4 != 12) {
        // 0x100003dc8
        v5 = 8 * v4 + v3;
        *(int64_t *)v5 = *(int64_t *)(v5 - 8) * v4;
        v4++;
    }
    int32_t v6 = 9;
    int64_t v7; // 0x100003d80
    _printf("The factorions for base %d are:\n", v7);
    uint64_t v8 = (int64_t)v6;
    int64_t v9; // 0x100003d80
    int64_t v10; // 0x100003d80
    uint64_t v11; // 0x100003d80
    int64_t v12; // 0x100003eac
    int64_t v13; // 0x100003ea4
    for (int64_t i = 1; i < 0x16e360; i++) {
        // 0x100003e84
        v11 = i;
        v12 = *(int64_t *)(0x100000000 * (v11 % v8) / 0x20000000 + v3);
        v10 = v11 / v8;
        v9 = v12;
        while (v11 >= v8) {
            // 0x100003e84
            v11 = v10;
            v13 = *(int64_t *)(0x100000000 * (v11 % v8) / 0x20000000 + v3);
            v12 = v13 + v9;
            v10 = v11 / v8;
            v9 = v12;
        }
        if (v12 == i) {
            // 0x100003ee0
            _printf("%llu ", v7);
        }
    }
    // 0x100003f10
    _printf("\n\n");
    int32_t v14 = v6 + 1; // 0x100003f24
    int32_t v15 = v6 - 11; // 0x100003e0c
    while (v15 == 0 || v15 < 0 != (10 - v6 & v14) < 0) {
        // 0x100003e1c
        v6 = v14;
        _printf("The factorions for base %d are:\n", v7);
        v8 = (int64_t)v6;
        for (int64_t i = 1; i < 0x16e360; i++) {
            // 0x100003e84
            v11 = i;
            v12 = *(int64_t *)(0x100000000 * (v11 % v8) / 0x20000000 + v3);
            v10 = v11 / v8;
            v9 = v12;
            while (v11 >= v8) {
                // 0x100003e84
                v11 = v10;
                v13 = *(int64_t *)(0x100000000 * (v11 % v8) / 0x20000000 + v3);
                v12 = v13 + v9;
                v10 = v11 / v8;
                v9 = v12;
            }
            if (v12 == i) {
                // 0x100003ee0
                _printf("%llu ", v7);
            }
        }
        // 0x100003f10
        _printf("\n\n");
        v14 = v6 + 1;
        v15 = v6 - 11;
    }
    // 0x100003f30
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003f50
        ___stack_chk_fail();
    }
    // 0x100003f54
    return 0;
}

// Address range: 0x100003f64 - 0x100003f70
int64_t function_100003f64(void) {
    // 0x100003f64
    return ___stack_chk_fail();
}

// Address range: 0x100003f70 - 0x100003f7c
int32_t function_100003f70(char * format, ...) {
    // 0x100003f70
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

