//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003bec(void);
int64_t function_100003c0c(void);
int64_t function_100003c30(int64_t a1);
int64_t function_100003f00(int64_t a1);
int64_t * function_100003f0c(int32_t size);
int64_t * function_100003f18(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003f24(char * format, ...);
int64_t * function_100003f30(int64_t * ptr, int32_t size);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x200000001; // 0x100003f3c
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int64_t * _malloc(int32_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);
int64_t * _realloc(int64_t * a1, int32_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003bec - 0x100003c0c
int64_t function_100003bec(void) {
    // 0x100003bec
    int64_t v1; // 0x100003bec
    return (uint64_t)v1 % 2 == 0;
}

// Address range: 0x100003c0c - 0x100003c30
int64_t function_100003c0c(void) {
    // 0x100003c0c
    int64_t v1; // 0x100003c0c
    return (int32_t)v1 % 3;
}

// Address range: 0x100003c30 - 0x100003d70
int64_t function_100003c30(int64_t a1) {
    // 0x100003c30
    int64_t v1; // 0x100003c30
    int32_t v2 = v1; // 0x100003c40
    int64_t result; // 0x100003c30
    if ((int32_t)v1 == 0) {
        // 0x100003c70
        result = (int64_t)_malloc(4 * v2);
    }
    int32_t v3 = -v2; // 0x100003c9c
    if (v3 < 0 != (v2 & v3) < 0) {
        // 0x100003cac
        return (int64_t)*(int32_t *)v1;
    }
    // 0x100003d54
    *(int32_t *)v1 = 0;
    return result;
}

// Address range: 0x100003d70 - 0x100003f00
int64_t entry_point(void) {
    // 0x100003d70
    int64_t v1; // bp-64, 0x100003d70
    _memcpy(&v1, &g1, 40);
    function_100003c30((int64_t)&g2);
    _printf("Filtered even:");
    int32_t v2; // 0x100003d70
    int32_t v3 = -v2;
    int32_t v4 = 0; // 0x100003df4
    if (v3 < 0 == (v2 & v3) < 0) {
        // 0x100003ec0
        _printf("\n");
        function_100003c30((int64_t)&g2);
        _printf("In-place filtered not multiple of 3:");
    } else {
        _printf(" %d", 10);
        v4++;
        while (v4 - v2 < 0 != ((v4 - v2 ^ v4) & (v4 ^ v2)) < 0) {
            // 0x100003dfc
            _printf(" %d", 10);
            v4++;
        }
        // 0x100003e88
        _printf("\n");
        function_100003c30((int64_t)&g2);
        _printf("In-place filtered not multiple of 3:");
        int32_t v5 = 0; // 0x100003eb4
        _printf(" %d", 8);
        v5++;
        while (v5 - v2 < 0 != ((v5 - v2 ^ v5) & (v5 ^ v2)) < 0) {
            // 0x100003e88
            _printf(" %d", 8);
            v5++;
        }
    }
    int32_t v6 = _printf("\n"); // 0x100003ec8
    int64_t v7 = *(int64_t *)0x100004008; // 0x100003ed4
    if (*(int64_t *)v7 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003eec
        ___stack_chk_fail((int64_t)v6);
    }
    // 0x100003ef0
    return 0;
}

// Address range: 0x100003f00 - 0x100003f0c
int64_t function_100003f00(int64_t a1) {
    // 0x100003f00
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f0c - 0x100003f18
int64_t * function_100003f0c(int32_t size) {
    // 0x100003f0c
    return _malloc(size);
}

// Address range: 0x100003f18 - 0x100003f24
int64_t * function_100003f18(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003f18
    return _memcpy(dest, src, n);
}

// Address range: 0x100003f24 - 0x100003f30
int32_t function_100003f24(char * format, ...) {
    // 0x100003f24
    return _printf(format);
}

// Address range: 0x100003f30 - 0x100003f3c
int64_t * function_100003f30(int64_t * ptr, int32_t size) {
    // 0x100003f30
    return _realloc(ptr, size);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

