//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f28(void);
int32_t function_100003f98(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003f28 - 0x100003f6c
int64_t function_100003f28(void) {
    // 0x100003f28
    int64_t v1; // 0x100003f28
    _printf("%d\n", v1);
    return function_100003f28();
}

// Address range: 0x100003f6c - 0x100003f98
int64_t entry_point(void) {
    // 0x100003f6c
    function_100003f28();
    return 0;
}

// Address range: 0x100003f98 - 0x100003fa4
int32_t function_100003f98(char * format, ...) {
    // 0x100003f98
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

