//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000039a8(void);
int64_t function_100003a54(void);
int64_t function_100003b68(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003f78(void);
int32_t function_100003f84(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___chkstk_darwin(void);
int64_t ___stack_chk_fail(void);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x1000039a8 - 0x100003a54
int64_t function_1000039a8(void) {
    // 0x1000039a8
    int64_t result; // 0x1000039a8
    if ((int32_t)result != 0) {
        // 0x100003a4c
        return result;
    }
    int32_t * v1 = (int32_t *)result; // 0x1000039b0
    int32_t v2 = result;
    int32_t * v3; // 0x1000039a8
    int32_t v4; // 0x1000039a8
    int32_t v5; // 0x1000039a8
    if ((int32_t)result == 1) {
        int32_t v6 = result; // 0x1000039ac
        *v1 = v6 + -1 - v2;
        int32_t * v7 = (int32_t *)(result + 4);
        int32_t v8 = -1 - *v7 + v6; // 0x100003a10
        *v7 = v8;
        v4 = v8;
        v3 = v7;
        int64_t v9; // 0x1000039a8
        v5 = *(int32_t *)&v9;
    } else {
        int32_t * v10 = (int32_t *)(result + 4); // 0x100003a30
        v4 = *v10;
        v3 = v10;
        v5 = v2;
    }
    // 0x100003a20
    *v1 = v4;
    *v3 = v5;
    // 0x100003a4c
    return result;
}

// Address range: 0x100003a54 - 0x100003b4c
int64_t function_100003a54(void) {
    // 0x100003a54
    int64_t v1; // 0x100003a54
    int32_t v2 = v1; // 0x100003a60
    int32_t * v3 = (int32_t *)v1; // 0x100003a68
    *v3 = 0;
    int32_t * v4 = (int32_t *)(v1 + 4); // 0x100003a88
    *v4 = 0;
    int32_t v5 = 1 - v2; // 0x100003a98
    if (v5 < 0 == (v5 & v2) < 0) {
        // 0x100003b40
        int64_t result; // 0x100003a54
        return result;
    }
    int32_t v6 = v1; // 0x100003a54
    int32_t v7 = 1; // 0x100003b34
    int32_t v8 = v6 / 2; // 0x100003ab0
    int64_t result2 = function_1000039a8(); // 0x100003ae4
    int64_t v9; // 0x100003a54
    *v3 = *(int32_t *)&v9 + v8 % 2 * v7;
    *v4 = *v4 + (v8 ^ v6) % 2 * v7;
    v7 *= 2;
    int32_t v10 = v7 - v2; // 0x100003a98
    v6 /= 4;
    while (v10 < 0 != ((v10 ^ v7) & (v7 ^ v2)) < 0) {
        // 0x100003aa8
        v8 = v6 / 2;
        result2 = function_1000039a8();
        *v3 = *(int32_t *)&v9 + v8 % 2 * v7;
        *v4 = *v4 + (v8 ^ v6) % 2 * v7;
        v7 *= 2;
        v10 = v7 - v2;
        v6 /= 4;
    }
    // 0x100003b40
    return result2;
}

// Address range: 0x100003b4c - 0x100003b68
int64_t entry_point(void) {
    // 0x100003b4c
    return ___chkstk_darwin();
}

// Address range: 0x100003b68 - 0x100003f78
int64_t function_100003b68(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003b68
    int64_t v1; // 0x100003b68
    int64_t * v2 = (int64_t *)(v1 - 24); // 0x100003b7c
    *v2 = *(int64_t *)*(int64_t *)0x100004010;
    int64_t v3; // bp-9224, 0x100003b68
    int64_t v4 = &v3;
    for (int64_t i = 0; i < 96; i++) {
        for (int64_t j = 0; j < 96; j++) {
            // 0x100003bbc
            *(char *)(96 * i + v4 + j) = 32;
        }
    }
    // 0x100003c08
    v3 = 46;
    int32_t v5; // 0x100003b68
    int32_t v6 = 3 * v5;
    int32_t v7 = 3 * v5;
    int64_t v8 = 96 * (int64_t)v6 + v4;
    int64_t v9 = v7;
    int64_t v10 = v4 + v9;
    int32_t v11 = v6 + 1;
    int32_t v12 = -v7;
    int32_t v13 = 1 - v7;
    int32_t v14 = v7 + 1;
    char v15 = 1;
    function_100003a54();
    int32_t v16 = 0; // 0x100003c68
    *(char *)(v8 + v9) = 46;
    int32_t v17; // 0x100003b68
    int32_t v18; // 0x100003b68
    int32_t v19; // 0x100003b68
    int32_t v20; // 0x100003b68
    int32_t v21; // 0x100003b68
    int32_t v22; // 0x100003b68
    int32_t v23; // 0x100003b68
    int32_t v24; // 0x100003b68
    int32_t v25; // 0x100003b68
    int32_t v26; // 0x100003da4
    int32_t v27; // 0x100003e30
    int32_t v28; // 0x100003dcc
    int32_t v29; // 0x100003ce8
    int32_t v30; // 0x100003e30
    int32_t v31; // 0x100003dcc
    if (v16 == v6) {
        if (v12 < 0 == (v7 & v12) < 0) {
            // 0x100003d44
            if (v14 < 0) {
                *(char *)(v8 + (int64_t)v14) = 124;
                v19 = v14 + 1;
                v20 = v19;
                while (v19 < 0) {
                    // 0x100003d5c
                    *(char *)(v8 + (int64_t)v20) = 124;
                    v19 = v20 + 1;
                    v20 = v19;
                }
            }
        } else {
            // 0x100003ce0
            v18 = 1;
            if (v13 < 0 != (v13 & v7) < 0) {
                *(char *)(v8 + (int64_t)v18) = 124;
                v17 = v18 + 1;
                v29 = v17 - v7;
                v18 = v17;
                while (v29 < 0 != ((v29 ^ v17) & (v17 ^ v7)) < 0) {
                    // 0x100003cf8
                    *(char *)(v8 + (int64_t)v18) = 124;
                    v17 = v18 + 1;
                    v29 = v17 - v7;
                    v18 = v17;
                }
            }
        }
    } else {
        // 0x100003d9c
        v26 = v16 - v6;
        if (v26 < 0 == ((v26 ^ v16) & (v16 ^ v6)) < 0) {
            // 0x100003e28
            v27 = v11 - v16;
            if (v27 < 0 != ((v27 ^ v11) & (v16 ^ v11)) < 0) {
                *(char *)(96 * (int64_t)v11 + v10) = 95;
                v24 = v11 + 1;
                v30 = v24 - v16;
                v25 = v24;
                while (v30 < 0 != ((v30 ^ v24) & (v24 ^ v16)) < 0) {
                    // 0x100003e40
                    *(char *)(96 * (int64_t)v25 + v10) = 95;
                    v24 = v25 + 1;
                    v30 = v24 - v16;
                    v25 = v24;
                }
            }
        } else {
            // 0x100003dc4
            v22 = v16 + 1;
            v28 = v22 - v6;
            v23 = v22;
            if (v28 < 0 != ((v28 ^ v22) & (v22 ^ v6)) < 0) {
                *(char *)(96 * (int64_t)v23 + v10) = 95;
                v21 = v23 + 1;
                v31 = v21 - v6;
                v23 = v21;
                while (v31 < 0 != ((v31 ^ v21) & (v21 ^ v6)) < 0) {
                    // 0x100003ddc
                    *(char *)(96 * (int64_t)v23 + v10) = 95;
                    v21 = v23 + 1;
                    v31 = v21 - v6;
                    v23 = v21;
                }
            }
        }
    }
    char v32 = v15 + 1; // 0x100003e90
    int32_t v33 = v32; // 0x100003c24
    int32_t v34 = 0; // 0x100003c30
    while ((1023 - v33 & v33) >= 0) {
        // 0x100003c38
        v15 = v32;
        function_100003a54();
        v16 = 0;
        *(char *)(v8 + v9) = 46;
        if (v16 == v6) {
            if (v12 < 0 == (v7 & v12) < 0) {
                // 0x100003d44
                if (v14 < 0) {
                    *(char *)(v8 + (int64_t)v14) = 124;
                    v19 = v14 + 1;
                    v20 = v19;
                    while (v19 < 0) {
                        // 0x100003d5c
                        *(char *)(v8 + (int64_t)v20) = 124;
                        v19 = v20 + 1;
                        v20 = v19;
                    }
                }
            } else {
                // 0x100003ce0
                v18 = 1;
                if (v13 < 0 != (v13 & v7) < 0) {
                    *(char *)(v8 + (int64_t)v18) = 124;
                    v17 = v18 + 1;
                    v29 = v17 - v7;
                    v18 = v17;
                    while (v29 < 0 != ((v29 ^ v17) & (v17 ^ v7)) < 0) {
                        // 0x100003cf8
                        *(char *)(v8 + (int64_t)v18) = 124;
                        v17 = v18 + 1;
                        v29 = v17 - v7;
                        v18 = v17;
                    }
                }
            }
        } else {
            // 0x100003d9c
            v26 = v16 - v6;
            if (v26 < 0 == ((v26 ^ v16) & (v16 ^ v6)) < 0) {
                // 0x100003e28
                v27 = v11 - v16;
                if (v27 < 0 != ((v27 ^ v11) & (v16 ^ v11)) < 0) {
                    *(char *)(96 * (int64_t)v11 + v10) = 95;
                    v24 = v11 + 1;
                    v30 = v24 - v16;
                    v25 = v24;
                    while (v30 < 0 != ((v30 ^ v24) & (v24 ^ v16)) < 0) {
                        // 0x100003e40
                        *(char *)(96 * (int64_t)v25 + v10) = 95;
                        v24 = v25 + 1;
                        v30 = v24 - v16;
                        v25 = v24;
                    }
                }
            } else {
                // 0x100003dc4
                v22 = v16 + 1;
                v28 = v22 - v6;
                v23 = v22;
                if (v28 < 0 != ((v28 ^ v22) & (v22 ^ v6)) < 0) {
                    *(char *)(96 * (int64_t)v23 + v10) = 95;
                    v21 = v23 + 1;
                    v31 = v21 - v6;
                    v23 = v21;
                    while (v31 < 0 != ((v31 ^ v21) & (v21 ^ v6)) < 0) {
                        // 0x100003ddc
                        *(char *)(96 * (int64_t)v23 + v10) = 95;
                        v21 = v23 + 1;
                        v31 = v21 - v6;
                        v23 = v21;
                    }
                }
            }
        }
        // 0x100003e80
        v32 = v15 + 1;
        v33 = v32;
        v34 = 0;
    }
    for (int32_t i = 0; i < 96; i++) {
        // 0x100003ed4
        _printf("%c", v15);
    }
    // 0x100003f1c
    _printf((char *)0x100003f93);
    while (v34 != 95) {
        // continue -> 0x100003ec0
        continue;
    }
    // 0x100003f3c
    if (*(int64_t *)*(int64_t *)0x100004010 != *v2) {
        // 0x100003f5c
        ___stack_chk_fail();
    }
    // 0x100003f60
    return 0;
}

// Address range: 0x100003f78 - 0x100003f84
int64_t function_100003f78(void) {
    // 0x100003f78
    return ___stack_chk_fail();
}

// Address range: 0x100003f84 - 0x100003f90
int32_t function_100003f84(char * format, ...) {
    // 0x100003f84
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

