//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003654(int64_t * a1);
int64_t function_100003670(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003984(void);
int64_t function_1000039f4(void);
int64_t function_100003ab4(void);
int64_t function_100003b18(void);
int64_t function_100003b48(void);
int64_t function_100003bac(void);
int64_t function_100003db4(void);
int64_t function_100003ef4(int64_t a1);
int32_t function_100003f00(int32_t x);
void function_100003f0c(int64_t * s, int32_t n);
void function_100003f18(int64_t * ptr);
int64_t * function_100003f24(int32_t size);
int64_t * function_100003f30(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003f3c(char * format, ...);
int64_t * function_100003f48(int64_t * ptr, int32_t size);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___chkstk_darwin(void);
int64_t ___stack_chk_fail(int64_t a1);
int32_t _abs(int32_t a1);
void _bzero(int64_t * a1, int32_t a2);
void _free(int64_t * a1);
int64_t * _malloc(int32_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);
int64_t * _realloc(int64_t * a1, int32_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003654 - 0x100003670
int64_t function_100003654(int64_t * a1) {
    // 0x100003654
    return ___chkstk_darwin();
}

// Address range: 0x100003670 - 0x100003984
int64_t function_100003670(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003670
    int64_t v1; // 0x100003670
    int64_t * v2 = (int64_t *)(v1 - 24); // 0x100003684
    *v2 = *(int64_t *)*(int64_t *)0x100004010;
    int64_t v3; // bp-4104, 0x100003670
    int64_t v4 = &v3; // 0x10000369c
    _memcpy(&v3, (int64_t *)v1, 2048);
    _bzero((int64_t *)(v4 + 2048), 2048);
    int64_t v5 = function_100003984(); // 0x1000036c4
    int64_t v6 = 0; // 0x1000036d8
    int64_t result = 0; // 0x1000036d8
    if (v5 != 0) {
        int32_t v7 = 0;
        if (*(int64_t *)(8 * (int64_t)v7 + v4) >= 1) {
            // 0x100003720
            function_1000039f4();
        }
        int32_t v8 = v7 + 1; // 0x100003738
        while (v7 < 255 != (254 - v7 & v8) < 0) {
            // 0x100003704
            v7 = v8;
            if (*(int64_t *)(8 * (int64_t)v7 + v4) >= 1) {
                // 0x100003720
                function_1000039f4();
            }
            // 0x100003734
            v8 = v7 + 1;
        }
        int32_t * v9 = (int32_t *)(v5 + 8); // 0x10000374c
        int32_t v10 = *v9; // 0x10000374c
        int32_t v11 = v10 - 1; // 0x100003750
        int64_t v12 = function_100003ab4();
        int64_t v13; // bp-6152, 0x100003670
        int64_t v14 = &v13;
        int32_t v15 = 256; // 0x100003758
        int64_t v16 = v12; // 0x100003758
        if (v11 != 0 && v11 < 0 == (v10 & -v10) < 0) {
            int64_t v17 = function_100003ab4(); // 0x100003770
            int64_t v18 = 0x100000000 * v12;
            int64_t v19 = *(int64_t *)((v18 >> 29) + v4); // 0x100003780
            int64_t v20 = 0x100000000 * v17;
            int64_t v21 = *(int64_t *)((v20 >> 29) + v4); // 0x100003788
            *(int64_t *)(8 * (int64_t)v15 + v4) = v21 + v19;
            function_1000039f4();
            *(int32_t *)((v18 >> 30) + v14) = v15;
            *(int32_t *)((v20 >> 30) + v14) = -v15;
            int32_t v22 = *v9; // 0x10000374c
            int32_t v23 = v22 - 1; // 0x100003750
            int64_t v24 = function_100003ab4();
            int64_t v25 = v24; // 0x100003758
            v15++;
            v16 = v24;
            while (v23 != 0 && v23 < 0 == (v22 & -v22) < 0) {
                // 0x100003760
                v17 = function_100003ab4();
                v18 = 0x100000000 * v25;
                v19 = *(int64_t *)((v18 >> 29) + v4);
                v20 = 0x100000000 * v17;
                v21 = *(int64_t *)((v20 >> 29) + v4);
                *(int64_t *)(8 * (int64_t)v15 + v4) = v21 + v19;
                function_1000039f4();
                *(int32_t *)((v18 >> 30) + v14) = v15;
                *(int32_t *)((v20 >> 30) + v14) = -v15;
                v22 = *v9;
                v23 = v22 - 1;
                v24 = function_100003ab4();
                v25 = v24;
                v15++;
                v16 = v24;
            }
        }
        int64_t v26 = v16;
        *(int32_t *)((0x100000000 * v26 >> 30) + v14) = (int32_t)v26;
        function_100003b18();
        result = (int64_t)_malloc(2048);
        int32_t v27 = 0;
        int64_t v28 = v27;
        int64_t v29 = 8 * v28; // 0x100003834
        int32_t * v30; // 0x100003670
        int32_t v31; // 0x100003670
        int32_t v32; // 0x100003670
        int32_t v33; // 0x100003670
        int32_t v34; // 0x100003670
        int32_t * v35; // 0x100003870
        int64_t * v36; // 0x1000038e8
        int64_t v37; // 0x1000038e8
        int64_t * v38; // 0x1000038f4
        int32_t v39; // 0x100003894
        int32_t v40; // 0x1000038bc
        int32_t v41; // 0x1000038cc
        int32_t v42; // 0x1000038d8
        int32_t * v43; // 0x100003870
        int64_t v44; // 0x100003670
        if (*(int64_t *)(v29 + v4) == 0) {
            // 0x100003848
            *(int64_t *)(v29 + result) = 0;
            v44 = result;
        } else {
            // 0x100003868
            v35 = (int32_t *)(4 * v28 + v14);
            v30 = v35;
            v33 = 0;
            v32 = 0;
            v34 = 0;
            if (_abs(*v35) != v27) {
                v39 = *v30;
                v40 = (int32_t)(v39 >= 0) << v33;
                v41 = _abs(v39);
                v42 = v33 + 1;
                v43 = (int32_t *)(4 * (int64_t)v41 + v14);
                v30 = v43;
                v33 = v42;
                v31 = v40;
                v32 = v40;
                v34 = v42;
                while (_abs(*v43) != v41) {
                    // 0x10000388c
                    v39 = *v30;
                    v40 = (int32_t)(v39 >= 0) << v33 | v31;
                    v41 = _abs(v39);
                    v42 = v33 + 1;
                    v43 = (int32_t *)(4 * (int64_t)v41 + v14);
                    v30 = v43;
                    v33 = v42;
                    v31 = v40;
                    v32 = v40;
                    v34 = v42;
                }
            }
            // 0x1000038e4
            v36 = _malloc(8);
            v37 = (int64_t)v36;
            v38 = (int64_t *)(v29 + result);
            *v38 = v37;
            *(int32_t *)v36 = v34;
            *(int32_t *)(*v38 + 4) = v32;
            v44 = v37;
        }
        int32_t v45 = v27 + 1; // 0x100003928
        int64_t v46 = v44; // 0x10000381c
        v6 = v44;
        while (v27 < 255 != (254 - v27 & v45) < 0) {
            // 0x100003824
            v27 = v45;
            v28 = v27;
            v29 = 8 * v28;
            if (*(int64_t *)(v29 + v4) == 0) {
                // 0x100003848
                *(int64_t *)(v29 + result) = 0;
                v44 = v46;
            } else {
                // 0x100003868
                v35 = (int32_t *)(4 * v28 + v14);
                v30 = v35;
                v33 = 0;
                v32 = 0;
                v34 = 0;
                if (_abs(*v35) != v27) {
                    v39 = *v30;
                    v40 = (int32_t)(v39 >= 0) << v33;
                    v41 = _abs(v39);
                    v42 = v33 + 1;
                    v43 = (int32_t *)(4 * (int64_t)v41 + v14);
                    v30 = v43;
                    v33 = v42;
                    v31 = v40;
                    v32 = v40;
                    v34 = v42;
                    while (_abs(*v43) != v41) {
                        // 0x10000388c
                        v39 = *v30;
                        v40 = (int32_t)(v39 >= 0) << v33 | v31;
                        v41 = _abs(v39);
                        v42 = v33 + 1;
                        v43 = (int32_t *)(4 * (int64_t)v41 + v14);
                        v30 = v43;
                        v33 = v42;
                        v31 = v40;
                        v32 = v40;
                        v34 = v42;
                    }
                }
                // 0x1000038e4
                v36 = _malloc(8);
                v37 = (int64_t)v36;
                v38 = (int64_t *)(v29 + result);
                *v38 = v37;
                *(int32_t *)v36 = v34;
                *(int32_t *)(*v38 + 4) = v32;
                v44 = v37;
            }
            // 0x100003924
            v45 = v27 + 1;
            v46 = v44;
            v6 = v44;
        }
    }
    // 0x100003940
    if (*(int64_t *)*(int64_t *)0x100004010 != *v2) {
        // 0x100003968
        ___stack_chk_fail(v6);
    }
    // 0x10000396c
    return result;
}

// Address range: 0x100003984 - 0x1000039f4
int64_t function_100003984(void) {
    int64_t * v1 = _malloc(32); // 0x10000399c
    int64_t result = (int64_t)v1; // 0x10000399c
    int64_t v2; // 0x100003984
    int32_t v3 = v2;
    *v1 = (int64_t)_malloc(4 * v3);
    *(int32_t *)(result + 16) = v3;
    *(int32_t *)(result + 12) = v3;
    *(int32_t *)(result + 8) = 0;
    return result;
}

// Address range: 0x1000039f4 - 0x100003ab4
int64_t function_1000039f4(void) {
    // 0x1000039f4
    int64_t v1; // 0x1000039f4
    int32_t * v2 = (int32_t *)(v1 + 8); // 0x100003a0c
    int32_t v3 = *v2; // 0x100003a0c
    int32_t v4 = v3 + 1; // 0x100003a10
    int32_t * v5 = (int32_t *)(v1 + 12); // 0x100003a18
    int32_t v6 = *v5; // 0x100003a18
    int32_t v7 = v4 - v6; // 0x100003a1c
    int32_t v8 = v3; // 0x100003a24
    int64_t v9; // 0x1000039f4
    if (v7 != 0 && v7 < 0 == ((v7 ^ v4) & (v4 ^ v6)) < 0) {
        int32_t * v10 = (int32_t *)(v1 + 16); // 0x100003a40
        int64_t * v11 = (int64_t *)v1; // 0x100003a50
        int64_t v12 = (int64_t)_realloc(v11, *v10 + v6); // 0x100003a50
        *v11 = v12;
        *v5 = *v5 + *v10;
        v8 = *v2;
        v9 = v12;
    }
    // 0x100003a78
    *(int32_t *)(4 * (int64_t)v8 + v9) = (int32_t)v1;
    *v2 = *v2 + 1;
    return function_100003db4();
}

// Address range: 0x100003ab4 - 0x100003b18
int64_t function_100003ab4(void) {
    // 0x100003ab4
    int64_t v1; // 0x100003ab4
    int32_t * v2 = (int32_t *)(v1 + 8); // 0x100003ac0
    uint32_t v3 = *v2; // 0x100003ac0
    int64_t result = 0xffffffff; // 0x100003acc
    if (v3 >= 1) {
        int32_t v4 = v3 - 1; // 0x100003adc
        *v2 = v4;
        result = (int64_t)*(int32_t *)(4 * (int64_t)v4 + v1);
    }
    // 0x100003b0c
    return result;
}

// Address range: 0x100003b18 - 0x100003b48
int64_t function_100003b18(void) {
    // 0x100003b18
    int64_t v1; // 0x100003b18
    int64_t * v2 = (int64_t *)v1; // 0x100003b30
    _free(v2);
    _free(v2);
    return &g1;
}

// Address range: 0x100003b48 - 0x100003bac
int64_t function_100003b48(void) {
    int32_t v1 = 0;
    int64_t v2; // 0x100003b48
    _free((int64_t *)*(int64_t *)(8 * (int64_t)v1 + v2));
    int32_t v3 = v1 + 1; // 0x100003b8c
    while (v1 < 255 != (254 - v1 & v3) < 0) {
        // 0x100003b74
        v1 = v3;
        _free((int64_t *)*(int64_t *)(8 * (int64_t)v1 + v2));
        v3 = v1 + 1;
    }
    // 0x100003b98
    _free((int64_t *)v2);
    return &g1;
}

// Address range: 0x100003bac - 0x100003c30
int64_t function_100003bac(void) {
    // 0x100003bac
    int64_t result; // 0x100003bac
    int32_t v1 = result; // 0x100003bb4
    *(char *)((0x100000000 * result >> 32) + result) = 0;
    if (v1 < 1) {
        // 0x100003c28
        return result;
    }
    int32_t v2 = v1; // 0x100003c04
    int32_t v3 = result;
    int64_t v4 = result & 0xffffffff;
    v2--;
    *(char *)(result + (int64_t)v2) = (char)(v3 - 2 * v3 / 2) + 48;
    int64_t v5 = v4 - 1; // 0x100003bdc
    int32_t v6 = v3 >> 1; // 0x100003bdc
    while (v4 >= 2) {
        // 0x100003be4
        v3 = v6;
        v4 = v5;
        v2--;
        *(char *)(result + (int64_t)v2) = (char)(v3 - 2 * v3 / 2) + 48;
        v5 = v4 - 1;
        v6 = v3 >> 1;
    }
    // 0x100003c28
    return result;
}

// Address range: 0x100003c30 - 0x100003db4
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003c48
    int64_t v2; // bp-2184, 0x100003c30
    _bzero(&v2, 2048);
    char v3 = *(char *)0x3f54; // 0x100003c74
    if (v3 != 0) {
        char * v4 = (char *)0x3f54; // 0x100003c90
        v4 = (char *)((int64_t)v4 + 1);
        int64_t * v5 = (int64_t *)(8 * (int64_t)v3 + (int64_t)&v2); // 0x100003ca0
        *v5 = *v5 + 1;
        char v6 = *v4; // 0x100003c74
        while (v6 != 0) {
            // 0x100003c88
            v4 = (char *)((int64_t)v4 + 1);
            v5 = (int64_t *)(8 * (int64_t)v6 + (int64_t)&v2);
            *v5 = *v5 + 1;
            v6 = *v4;
        }
    }
    int64_t v7 = function_100003654(&v2); // 0x100003cb4
    int64_t v8; // bp-132, 0x100003c30
    int64_t v9 = &v8;
    int32_t v10 = 0;
    int64_t v11 = *(int64_t *)(8 * (int64_t)v10 + v7); // 0x100003ce0
    int64_t v12; // 0x100003c30
    if (v11 != 0) {
        // 0x100003cf4
        function_100003bac();
        _printf("%c (%d) %s\n", (char)*(int32_t *)v11, v9, (char *)v12);
    }
    int32_t v13 = v10 + 1; // 0x100003d68
    while (v10 < 255 != (254 - v10 & v13) < 0) {
        // 0x100003cd8
        v10 = v13;
        v11 = *(int64_t *)(8 * (int64_t)v10 + v7);
        if (v11 != 0) {
            // 0x100003cf4
            function_100003bac();
            _printf("%c (%d) %s\n", (char)*(int32_t *)v11, v9, (char *)v12);
        }
        // 0x100003d64
        v13 = v10 + 1;
    }
    int64_t v14 = function_100003b48(); // 0x100003d78
    if (*(int64_t *)*(int64_t *)0x100004010 != v1) {
        // 0x100003d9c
        ___stack_chk_fail(v14);
    }
    // 0x100003da0
    return 0;
}

// Address range: 0x100003db4 - 0x100003ef4
int64_t function_100003db4(void) {
    // 0x100003db4
    int64_t result; // 0x100003db4
    int32_t * v1 = (int32_t *)(result + 8); // 0x100003de4
    int32_t v2 = *v1; // 0x100003de4
    int32_t v3 = 1 - v2; // 0x100003de8
    if (v3 < 0 == (v3 & v2) < 0) {
        // 0x100003eec
        return result;
    }
    int32_t v4 = v2; // 0x100003db4
    int32_t v5 = 1;
    int32_t v6 = 2;
    int64_t v7 = *(int64_t *)(result + 24); // 0x100003dfc
    int32_t * v8 = (int32_t *)(result + (int64_t)(4 * v5 - 4)); // 0x100003e0c
    int32_t v9 = *v8; // 0x100003e0c
    int64_t v10 = *(int64_t *)(8 * (int64_t)v9 + v7); // 0x100003e10
    int32_t * v11 = (int32_t *)(4 * (int64_t)v5 + result); // 0x100003e24
    int32_t v12 = *v11; // 0x100003e24
    int64_t v13 = *(int64_t *)(8 * (int64_t)v12 + v7); // 0x100003e28
    int64_t v14 = v10 - v13; // 0x100003e2c
    int32_t v15; // 0x100003db4
    int32_t v16; // 0x100003db4
    int32_t v17; // 0x100003ea0
    if (v14 < 0 == ((v14 ^ v10) & (v13 ^ v10)) < 0) {
        // 0x100003e3c
        v15 = v6;
        v16 = v6 + 1;
    } else {
        // 0x100003e58
        *v8 = v12;
        *v11 = v9;
        v17 = v5 - 1;
        v4 = *v1;
        v15 = v17 == 0 ? v6 : v17;
        v16 = v6 + (int32_t)(v17 == 0);
    }
    // 0x100003ee8
    while (v15 - v4 < 0 != ((v15 - v4 ^ v15) & (v15 ^ v4)) < 0) {
        // 0x100003df8
        v5 = v15;
        v6 = v16;
        v7 = *(int64_t *)(result + 24);
        v8 = (int32_t *)(result + (int64_t)(4 * v5 - 4));
        v9 = *v8;
        v10 = *(int64_t *)(8 * (int64_t)v9 + v7);
        v11 = (int32_t *)(4 * (int64_t)v5 + result);
        v12 = *v11;
        v13 = *(int64_t *)(8 * (int64_t)v12 + v7);
        v14 = v10 - v13;
        if (v14 < 0 == ((v14 ^ v10) & (v13 ^ v10)) < 0) {
            // 0x100003e3c
            v15 = v6;
            v16 = v6 + 1;
        } else {
            // 0x100003e58
            *v8 = v12;
            *v11 = v9;
            v17 = v5 - 1;
            v4 = *v1;
            v15 = v17 == 0 ? v6 : v17;
            v16 = v6 + (int32_t)(v17 == 0);
        }
    }
    // 0x100003eec
    return result;
}

// Address range: 0x100003ef4 - 0x100003f00
int64_t function_100003ef4(int64_t a1) {
    // 0x100003ef4
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f00 - 0x100003f0c
int32_t function_100003f00(int32_t x) {
    // 0x100003f00
    return _abs(x);
}

// Address range: 0x100003f0c - 0x100003f18
void function_100003f0c(int64_t * s, int32_t n) {
    // 0x100003f0c
    _bzero(s, n);
}

// Address range: 0x100003f18 - 0x100003f24
void function_100003f18(int64_t * ptr) {
    // 0x100003f18
    _free(ptr);
}

// Address range: 0x100003f24 - 0x100003f30
int64_t * function_100003f24(int32_t size) {
    // 0x100003f24
    return _malloc(size);
}

// Address range: 0x100003f30 - 0x100003f3c
int64_t * function_100003f30(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003f30
    return _memcpy(dest, src, n);
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(char * format, ...) {
    // 0x100003f3c
    return _printf(format);
}

// Address range: 0x100003f48 - 0x100003f54
int64_t * function_100003f48(int64_t * ptr, int32_t size) {
    // 0x100003f48
    return _realloc(ptr, size);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 18

