//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003ab4(void);
int64_t function_100003b18(void);
int64_t function_100003b98(void);
int64_t function_100003f5c(int64_t a1);
int32_t function_100003f68(char * format, ...);

// --------------------- Global Variables ---------------------

int32_t * g1 = (int32_t *)0x100000000; // 0x100003f74

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003ab4 - 0x100003b18
int64_t function_100003ab4(void) {
    int64_t result = 1; // 0x100003ad0
    int64_t v1; // 0x100003ab4
    if ((int32_t)v1 != 0) {
        // 0x100003ae4
        result = function_100003ab4() * v1 & 0xffffffff;
    }
    // 0x100003b08
    return result;
}

// Address range: 0x100003b18 - 0x100003b98
int64_t function_100003b18(void) {
    // 0x100003b18
    int64_t v1; // 0x100003b18
    int32_t v2 = v1; // 0x100003b1c
    int32_t result = 0; // 0x100003b3c
    if (v2 < 1) {
        // 0x100003b8c
        return 0;
    }
    uint32_t v3 = v2; // 0x100003b3c
    uint32_t v4 = v3 % 10;
    result += v4 * v4;
    while (v3 >= 10) {
        // 0x100003b44
        v3 /= 10;
        v4 = v3 % 10;
        result += v4 * v4;
    }
    // 0x100003b8c
    return result;
}

// Address range: 0x100003b98 - 0x100003ecc
int64_t function_100003b98(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003bac
    int64_t v2; // 0x100003b98
    int32_t v3 = v2; // 0x100003bb8
    int64_t v4; // bp-64, 0x100003b98
    int64_t v5 = &v4;
    for (int64_t i = 0; i < 10; i++) {
        // 0x100003bec
        *(int32_t *)(4 * i + v5) = 0;
    }
    int32_t v6; // 0x100003b98
    int64_t result; // 0x100003b98
    int64_t v7; // 0x100003b98
    int64_t v8; // 0x100003b98
    if (v3 == (int32_t)v2) {
        // 0x100003c28
        result = 1;
        v8 = 0;
        if (v2 == 0) {
            goto lab_0x100003e90;
        } else {
            int32_t v9 = -v3; // 0x100003c5c
            int32_t v10 = 0; // 0x100003c64
            result = 1;
            if (v9 < 0 == (v9 & v3) < 0) {
                goto lab_0x100003e90;
            } else {
                int32_t v11 = *(int32_t *)(4 * (int64_t)v10 + v2); // 0x100003c74
                int32_t v12 = *(int32_t *)(4 * (int64_t)v11 + (int64_t)&g1); // 0x100003c80
                int32_t * v13 = (int32_t *)(4 * (int64_t)v12 + v5); // 0x100003c94
                *v13 = *v13 + 1;
                int32_t v14 = v12 * v12; // 0x100003cb0
                int32_t v15 = v10 + 1; // 0x100003cc0
                int32_t v16 = v15 - v3; // 0x100003c5c
                v10 = v15;
                int32_t v17 = v14; // 0x100003c64
                while (v16 < 0 != ((v16 ^ v15) & (v15 ^ v3)) < 0) {
                    // 0x100003c6c
                    v11 = *(int32_t *)(4 * (int64_t)v10 + v2);
                    v12 = *(int32_t *)(4 * (int64_t)v11 + (int64_t)&g1);
                    v13 = (int32_t *)(4 * (int64_t)v12 + v5);
                    *v13 = *v13 + 1;
                    v14 = v12 * v12 + v17;
                    v15 = v10 + 1;
                    v16 = v15 - v3;
                    v10 = v15;
                    v17 = v14;
                }
                // 0x100003ccc
                v6 = v14;
                result = 1;
                switch (v14) {
                    case 0: {
                        goto lab_0x100003e90;
                    }
                    case 89: {
                        goto lab_0x100003d68;
                    }
                    case 1: {
                        goto lab_0x100003d68;
                    }
                    default: {
                        if (v14 == 89) {
                            goto lab_0x100003d7c;
                        } else {
                            int64_t v18 = function_100003b18(); // 0x100003d58
                            int32_t v19 = v18;
                            v6 = v19;
                            v7 = v18;
                            while (v19 != 1 == (v19 != 89)) {
                                // 0x100003d54
                                v18 = function_100003b18();
                                v19 = v18;
                                v6 = v19;
                                v7 = v18;
                            }
                            goto lab_0x100003d68;
                        }
                    }
                }
            }
        }
    } else {
        int32_t v20 = v2; // 0x100003bc0
        int32_t v21 = v2; // 0x100003bc4
        int32_t v22 = v20 - v21; // 0x100003e0c
        result = 0;
        if (v22 < 0 != ((v22 ^ v20) & (int32_t)(v2 ^ v2)) < 0) {
            int64_t v23 = 0; // 0x100003e68
            if (v2 != 0) {
                // 0x100003e30
                *(int32_t *)((0x100000000 * v2 >> 30) + v2) = v20;
            }
            int64_t v24 = function_100003b98(); // 0x100003e60
            v23 += v24;
            int32_t v25 = v20 + 1; // 0x100003e78
            int32_t v26 = v25 - v21; // 0x100003e0c
            result = v23;
            v8 = v24;
            while (v26 < 0 != ((v26 ^ v25) & (v25 ^ v21)) < 0) {
                int32_t v27 = v25;
                if (v2 != 0) {
                    // 0x100003e30
                    *(int32_t *)((0x100000000 * v2 >> 30) + v2) = v27;
                }
                // 0x100003e44
                v24 = function_100003b98();
                v23 += v24;
                v25 = v27 + 1;
                v26 = v25 - v21;
                result = v23;
                v8 = v24;
            }
        }
        goto lab_0x100003e90;
    }
  lab_0x100003e90:
    // 0x100003e90
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003eb8
        ___stack_chk_fail(v8);
    }
    // 0x100003ebc
    return result;
  lab_0x100003d68:
    // 0x100003d68
    result = 1;
    v8 = v7;
    if (v6 == 89) {
        goto lab_0x100003d7c;
    } else {
        goto lab_0x100003e90;
    }
  lab_0x100003d7c:;
    int32_t v28 = function_100003ab4(); // 0x100003b98
    int64_t v29 = function_100003ab4(); // 0x100003db0
    int32_t v30 = v28 / (int32_t)v29; // 0x100003db8
    int32_t v31 = 1; // 0x100003dc8
    int32_t v32 = v31; // 0x100003d9c
    v28 = v30;
    while (v31 != 10) {
        // 0x100003da4
        v29 = function_100003ab4();
        v30 = v28 / (int32_t)v29;
        v31 = v32 + 1;
        v32 = v31;
        v28 = v30;
    }
    // 0x100003dd4
    int64_t v33; // 0x100003b98
    *(int32_t *)v2 = *(int32_t *)&v33 + v30;
    result = 1;
    v8 = v29;
    goto lab_0x100003e90;
}

// Address range: 0x100003ecc - 0x100003f5c
int64_t entry_point(void) {
    // 0x100003ecc
    function_100003b98();
    int32_t v1 = _printf("%d\n", 0); // 0x100003f24
    int64_t v2 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003f34
    if (v2 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003f48
        ___stack_chk_fail((int64_t)v1);
    }
    // 0x100003f4c
    return 0;
}

// Address range: 0x100003f5c - 0x100003f68
int64_t function_100003f5c(int64_t a1) {
    // 0x100003f5c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f68 - 0x100003f74
int32_t function_100003f68(char * format, ...) {
    // 0x100003f68
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

