//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003c64(void);
int64_t function_100003cb8(void);
int64_t function_100003d60(void);
int32_t function_100003eb8(char * nptr);
void function_100003ec4(int64_t * ptr);
int64_t * function_100003ed0(int32_t size);
int32_t function_100003edc(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _atoi(char * a1);
void _free(int64_t * a1);
int64_t * _malloc(int32_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003c64 - 0x100003cb8
int64_t function_100003c64(void) {
    // 0x100003c64
    int64_t v1; // 0x100003c64
    int32_t v2 = v1; // 0x100003c68
    int32_t result = 0; // 0x100003c80
    if (v2 == 0) {
        // 0x100003cac
        return 0;
    }
    int32_t v3 = v2; // 0x100003c80
    result++;
    while (v3 >= 10) {
        // 0x100003c88
        v3 /= 10;
        result++;
    }
    // 0x100003cac
    return result;
}

// Address range: 0x100003cb8 - 0x100003d60
int64_t function_100003cb8(void) {
    // 0x100003cb8
    int64_t v1; // 0x100003cb8
    int32_t v2 = v1; // 0x100003cc8
    int64_t result = (int64_t)_malloc(4 * v2); // 0x100003cd4
    int32_t v3 = -v2; // 0x100003cf0
    int32_t v4 = 0; // 0x100003cf8
    if (v3 < 0 == (v3 & v2) < 0) {
        // 0x100003d50
        return result;
    }
    int32_t v5 = 0; // 0x100003cf8
    int32_t v6 = _atoi((char *)(v1 + (int64_t)v5)); // 0x100003d0c
    *(int32_t *)(4 * (int64_t)v4 + result) = v6;
    v4++;
    int32_t v7 = v4 - v2; // 0x100003cf0
    v5 = v5 + 1 + (int32_t)function_100003c64();
    while (v7 < 0 != ((v7 ^ v4) & (v4 ^ v2)) < 0) {
        // 0x100003d00
        v6 = _atoi((char *)(v1 + (int64_t)v5));
        *(int32_t *)(4 * (int64_t)v4 + result) = v6;
        v4++;
        v7 = v4 - v2;
        v5 = v5 + 1 + (int32_t)function_100003c64();
    }
    // 0x100003d50
    return result;
}

// Address range: 0x100003d60 - 0x100003e04
int64_t function_100003d60(void) {
    // 0x100003d60
    int64_t v1; // 0x100003d60
    int32_t v2 = v1; // 0x100003d68
    int32_t v3 = -v2; // 0x100003d84
    if (v3 < 0 == (v3 & v2) < 0) {
        // 0x100003df8
        return 1;
    }
    int32_t v4 = 1;
    int32_t v5 = 0;
    int32_t v6 = v4; // 0x100003da0
    int32_t v7; // 0x100003dc4
    int32_t v8; // 0x100003db4
    int32_t v9; // 0x100003dc0
    if (v5 != 0) {
        // 0x100003da8
        v8 = *(int32_t *)(v1 + (int64_t)(4 * v5 - 4));
        v9 = *(int32_t *)(4 * (int64_t)v5 + v1);
        v7 = v8 - v9;
        v6 = v4 + (int32_t)(v7 != 0 == v7 < 0 == ((v7 ^ v8) & (v9 ^ v8)) < 0);
    }
    int32_t result = v6;
    int32_t v10 = v5 + 1; // 0x100003dec
    int32_t v11 = v10 - v2; // 0x100003d84
    while (v11 < 0 != ((v11 ^ v10) & (v10 ^ v2)) < 0) {
        // 0x100003d94
        v4 = result;
        v5 = v10;
        v6 = v4;
        if (v5 != 0) {
            // 0x100003da8
            v8 = *(int32_t *)(v1 + (int64_t)(4 * v5 - 4));
            v9 = *(int32_t *)(4 * (int64_t)v5 + v1);
            v7 = v8 - v9;
            v6 = v4 + (int32_t)(v7 != 0 == v7 < 0 == ((v7 ^ v8) & (v9 ^ v8)) < 0);
        }
        // 0x100003de8
        result = v6;
        v10 = v5 + 1;
        v11 = v10 - v2;
    }
    // 0x100003df8
    return result;
}

// Address range: 0x100003e04 - 0x100003eb8
int64_t entry_point(void) {
    int64_t v1 = function_100003cb8(); // 0x100003e2c
    if ((int32_t)function_100003d60() == 1) {
        // 0x100003e54
        _printf("Did you forgot to turn on your brain?! This array is already sorted!\n");
        // 0x100003ea0
        _free((int64_t *)v1);
        return 0;
    }
    // 0x100003e64
    int64_t v2; // 0x100003e04
    int32_t v3 = v2; // 0x100003e14
    int32_t v4 = v3 - 11; // 0x100003e6c
    if (v4 == 0 || v4 < 0 != (v3 - 1 & 10 - v3) < 0) {
        // 0x100003e7c
        _printf("Am I really supposed to sort this? Sort it by yourself!\n");
    } else {
        // 0x100003e8c
        _printf("Am I really supposed to sort this? Bhahahaha!\n");
    }
    // 0x100003ea0
    _free((int64_t *)v1);
    return 0;
}

// Address range: 0x100003eb8 - 0x100003ec4
int32_t function_100003eb8(char * nptr) {
    // 0x100003eb8
    return _atoi(nptr);
}

// Address range: 0x100003ec4 - 0x100003ed0
void function_100003ec4(int64_t * ptr) {
    // 0x100003ec4
    _free(ptr);
}

// Address range: 0x100003ed0 - 0x100003edc
int64_t * function_100003ed0(int32_t size) {
    // 0x100003ed0
    return _malloc(size);
}

// Address range: 0x100003edc - 0x100003ee8
int32_t function_100003edc(char * format, ...) {
    // 0x100003edc
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

