//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003acc(void);
int64_t function_100003c20(void);
int32_t function_100003f4c(char * format, ...);
int32_t function_100003f58(int32_t c);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _putchar(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003acc - 0x100003c20
int64_t function_100003acc(void) {
    // 0x100003acc
    int64_t v1; // 0x100003acc
    uint64_t v2 = v1;
    uint64_t v3 = v2 * v2; // 0x100003ae0
    if ((v3 - v2) % (0x100000000 * v1 - 0x100000000 >> 32) != 0) {
        // 0x100003c14
        return 0;
    }
    int32_t v4 = v1; // 0x100003ad4
    int32_t v5 = 1; // 0x100003b44
    int32_t v6 = 1; // 0x100003b44
    int64_t v7 = 1; // 0x100003b44
    if (v2 > 1) {
        v5 *= v4;
        int64_t v8 = v5; // 0x100003b34
        v6 = v5;
        v7 = v8;
        while (v2 > v8) {
            // 0x100003b4c
            v5 *= v4;
            v8 = v5;
            v6 = v5;
            v7 = v8;
        }
    }
    // 0x100003b60
    if (v2 == v7) {
        // 0x100003c14
        return v2 == 1;
    }
    int64_t v9 = v6; // 0x100003b9c
    uint64_t v10 = v3 % v9;
    uint64_t v11 = v10; // 0x100003bbc
    int64_t v12 = v9; // 0x100003bbc
    if (v10 >= v2) {
        // 0x100003c14
        return 0;
    }
    int32_t v13 = v6; // 0x100003bbc
    int32_t result = v13; // 0x100003be4
    while (v3 / v12 + v11 != v2) {
        // 0x100003bf8
        v13 *= v4;
        v12 = v13;
        v11 = v3 % v12;
        result = 0;
        if (v11 >= v2) {
            // break -> 0x100003c14
            break;
        }
        result = v13;
    }
    // 0x100003c14
    return result;
}

// Address range: 0x100003c20 - 0x100003d30
int64_t function_100003c20(void) {
    // 0x100003c20
    int64_t v1; // 0x100003c20
    uint64_t v2 = 0x100000000 * v1 >> 32; // 0x100003c34
    int64_t v3 = v2; // 0x100003c50
    int64_t v4; // 0x100003c20
    if (v2 < v1) {
        v3 *= v2;
        while (v3 < v1) {
            // 0x100003c58
            v3 *= v2;
        }
        // 0x100003cac
        v4 = v3;
        if (v3 < v2) {
            // 0x100003d24
            int64_t result; // 0x100003c20
            return result;
        }
    } else {
        // 0x100003c70
        v4 = v2;
        if (v1 == 0) {
            // 0x100003d24
            return 0;
        }
    }
    uint64_t v5 = v4;
    v5 /= v2;
    int64_t v6; // 0x100003c20
    uint64_t v7 = v6 / v5; // 0x100003cc0
    int32_t v8 = v7;
    int32_t result2; // 0x100003c20
    if (v7 < 10) {
        // 0x100003cdc
        result2 = _putchar(v8 + 48);
    } else {
        // 0x100003cf0
        result2 = _putchar(v8 + 87);
    }
    // 0x100003d08
    while (v6 - v7 * v5 != 0) {
        // 0x100003cac
        v6 -= v7 * v5;
        if (v5 < v2) {
            // break -> 0x100003d24
            break;
        }
        v5 /= v2;
        v7 = v6 / v5;
        v8 = v7;
        if (v7 < 10) {
            // 0x100003cdc
            result2 = _putchar(v8 + 48);
        } else {
            // 0x100003cf0
            result2 = _putchar(v8 + 87);
        }
    }
    // 0x100003d24
    return result2;
}

// Address range: 0x100003d30 - 0x100003f4c
int64_t entry_point(void) {
    // 0x100003d30
    _printf("base 10:\n");
    int64_t v1; // 0x100003d30
    for (int64_t i = 1; i < 0xf4240; i++) {
        // 0x100003d80
        if ((int32_t)function_100003acc() != 0) {
            // 0x100003d9c
            _printf("%3d: %llu\n", 10, v1);
        }
    }
    // 0x100003de0
    _printf("\nbase %d:\n  1: 1\n", 10);
    for (int64_t i = 2; i < 0xf4240; i++) {
        // 0x100003e34
        if ((function_100003acc() & 0xffffffff) != 0) {
            // 0x100003e5c
            _printf("%3d: %llu", 17, v1);
            _printf(" \t");
            function_100003c20();
            _printf("\t");
            function_100003c20();
            _printf("\t");
            function_100003c20();
            _printf(" + ");
            function_100003c20();
            _printf((char *)0x100003f9e);
        }
    }
    // 0x100003f3c
    return 0;
}

// Address range: 0x100003f4c - 0x100003f58
int32_t function_100003f4c(char * format, ...) {
    // 0x100003f4c
    return _printf(format);
}

// Address range: 0x100003f58 - 0x100003f64
int32_t function_100003f58(int32_t c) {
    // 0x100003f58
    return _putchar(c);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

