//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
float64_t function_100003ef4(char * nptr);
void function_100003f00(int32_t status);
int32_t function_100003f0c(struct _IO_FILE * stream);
struct _IO_FILE * function_100003f18(char * filename, char * modes);
void function_100003f24(int64_t * ptr);
int32_t function_100003f30(char ** lineptr, int32_t * n, struct _IO_FILE * stream);
int32_t function_100003f3c(char * format, ...);
char * function_100003f48(char * s, int32_t c);

// ------- Dynamically Linked Functions Without Header --------

float64_t _atof(char * a1);
int32_t _fclose(struct _IO_FILE * a1);
struct _IO_FILE * _fopen(char * a1, char * a2);
void _free(int64_t * a1);
int32_t _getline(char ** a1, int32_t * a2, struct _IO_FILE * a3);
int32_t _printf(char * a1, ...);
char * _strrchr(char * a1, int32_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003d68 - 0x100003ef4
int64_t entry_point(void) {
    // 0x100003d68
    float64_t v1; // 0x100003d68
    float64_t v2 = v1;
    char * v3 = NULL; // bp-40, 0x100003d78
    int64_t v4 = 0; // bp-48, 0x100003d7c
    struct _IO_FILE * v5 = _fopen("data.txt", "r"); // 0x100003d90
    if (v5 == NULL) {
        // 0x100003dac
        _printf("Unable to open file\n");
        _exit(1);
        // UNREACHABLE
    }
    // 0x100003dc0
    _printf("Those earthquakes with a magnitude > 6.0 are:\n\n");
    int32_t v6 = _getline(&v3, (int32_t *)&v4, v5); // 0x100003ddc
    if (v6 != -1) {
        int64_t v7 = v6;
        char * v8; // 0x100003e24
        char * v9; // 0x100003e14
        if (v6 < 2 == (1 - v7 & v7) < 0) {
            // 0x100003e0c
            v9 = _strrchr(v3, 32);
            v8 = _strrchr(v3, 9);
            if (v9 == NULL != (v8 == NULL)) {
                // 0x100003e58
                _atof((char *)((int64_t)(v8 == v9 | v8 < v9 ? v9 : v8) + 1));
                if (v2 != 6.0 && v2 > 6.0 == v2 >= 6.0 == v2 <= 6.0) {
                    // 0x100003e9c
                    _printf("%s", (char *)9);
                }
            }
        }
        int32_t v10 = _getline(&v3, (int32_t *)&v4, v5); // 0x100003ddc
        while (v10 != -1) {
            // 0x100003df4
            v7 = v10;
            if (v10 < 2 == (1 - v7 & v7) < 0) {
                // 0x100003e0c
                v9 = _strrchr(v3, 32);
                v8 = _strrchr(v3, 9);
                if (v9 == NULL != (v8 == NULL)) {
                    // 0x100003e58
                    _atof((char *)((int64_t)(v8 == v9 | v8 < v9 ? v9 : v8) + 1));
                    if (v2 != 6.0 && v2 > 6.0 == v2 >= 6.0 == v2 <= 6.0) {
                        // 0x100003e9c
                        _printf("%s", (char *)9);
                    }
                }
            }
            // 0x100003dd0
            v10 = _getline(&v3, (int32_t *)&v4, v5);
        }
    }
    // 0x100003ebc
    _fclose(v5);
    if (v3 != NULL) {
        // 0x100003ed8
        _free((int64_t *)v3);
    }
    // 0x100003ee4
    return 0;
}

// Address range: 0x100003ef4 - 0x100003f00
float64_t function_100003ef4(char * nptr) {
    // 0x100003ef4
    return _atof(nptr);
}

// Address range: 0x100003f00 - 0x100003f0c
void function_100003f00(int32_t status) {
    // 0x100003f00
    _exit(status);
}

// Address range: 0x100003f0c - 0x100003f18
int32_t function_100003f0c(struct _IO_FILE * stream) {
    // 0x100003f0c
    return _fclose(stream);
}

// Address range: 0x100003f18 - 0x100003f24
struct _IO_FILE * function_100003f18(char * filename, char * modes) {
    // 0x100003f18
    return _fopen(filename, modes);
}

// Address range: 0x100003f24 - 0x100003f30
void function_100003f24(int64_t * ptr) {
    // 0x100003f24
    _free(ptr);
}

// Address range: 0x100003f30 - 0x100003f3c
int32_t function_100003f30(char ** lineptr, int32_t * n, struct _IO_FILE * stream) {
    // 0x100003f30
    return _getline(lineptr, n, stream);
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(char * format, ...) {
    // 0x100003f3c
    return _printf(format);
}

// Address range: 0x100003f48 - 0x100003f54
char * function_100003f48(char * s, int32_t c) {
    // 0x100003f48
    return _strrchr(s, c);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

