//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003a54(void);
int64_t * function_100003ea0(int32_t nmemb, int32_t size);
void function_100003eac(int64_t * ptr);
int64_t * function_100003eb8(int32_t size);
int32_t function_100003ec4(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t * _calloc(int32_t a1, int32_t a2);
void _free(int64_t * a1);
int64_t * _malloc(int32_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003a54 - 0x100003d40
int64_t function_100003a54(void) {
    // 0x100003a54
    int64_t v1; // 0x100003a54
    int32_t v2 = v1; // 0x100003a64
    int32_t v3 = v1; // 0x100003a68
    int32_t v4 = v3 + 1; // 0x100003a80
    int64_t * v5 = _calloc((v2 + 1) * v4, 4); // 0x100003a94
    int64_t v6 = (int64_t)v5; // 0x100003a94
    int64_t v7 = 0x100000000 * v1; // 0x100003aa0
    int64_t * v8 = _malloc((int32_t)((v7 + 0x100000000) / 0x20000000)); // 0x100003ab0
    int64_t v9 = (int64_t)v8; // 0x100003ab0
    *v8 = v6;
    int32_t v10 = 1 - v2; // 0x100003ad8
    if (v10 == 0 || v10 < 0 != (v10 & v2) < 0) {
        int32_t v11 = -v3; // 0x100003b1c
        int32_t v12 = 1;
        int64_t * v13 = (int64_t *)(8 * (int64_t)v12 + v9); // 0x100003b08
        *v13 = 4 * (int64_t)(v12 * v4) + v6;
        int32_t v14; // 0x100003a54
        int32_t v15; // 0x100003a54
        int64_t v16; // 0x100003b38
        int32_t * v17; // 0x100003a54
        int32_t v18; // 0x100003b3c
        int32_t v19; // 0x100003b44
        int64_t v20; // 0x100003a54
        int64_t v21; // 0x100003a54
        int32_t v22; // 0x100003a54
        int32_t v23; // 0x100003be4
        int32_t v24; // 0x100003bf4
        int32_t v25; // 0x100003c40
        if (v3 == 0 || v11 < 0 != (v11 & v3) < 0) {
            // 0x100003b2c
            v16 = 16 * (int64_t)(v12 - 1) + v1;
            v17 = (int32_t *)(v16 + 12);
            v15 = 0;
            v18 = *(int32_t *)(v16 + 8);
            v19 = v18 - v15;
            v20 = *(int64_t *)((int64_t)(8 * v12 - 8) + v9);
            v21 = 4 * (int64_t)v15;
            v22 = *(int32_t *)(v20 + v21);
            if (v19 == 0 || v19 < 0 != ((v19 ^ v18) & (v18 ^ v15)) < 0) {
                // 0x100003b84
                v23 = *v17 + *(int32_t *)(v20 + (int64_t)(4 * (v15 - v18)));
                v24 = v22 - v23;
                v14 = v24 == 0 | v24 < 0 != ((v24 ^ v22) & (v23 ^ v22)) < 0 ? v23 : v22;
                *(int32_t *)(*v13 + v21) = v14;
            } else {
                // 0x100003b54
                *(int32_t *)(*v13 + v21) = v22;
            }
            // 0x100003c3c
            v25 = v15 + 1;
            while (v25 - v3 == 0 || v25 - v3 < 0 != ((v25 - v3 ^ v25) & (v25 ^ v3)) < 0) {
                // 0x100003b2c
                v15 = v25;
                v18 = *(int32_t *)(v16 + 8);
                v19 = v18 - v15;
                v20 = *(int64_t *)((int64_t)(8 * v12 - 8) + v9);
                v21 = 4 * (int64_t)v15;
                v22 = *(int32_t *)(v20 + v21);
                if (v19 == 0 || v19 < 0 != ((v19 ^ v18) & (v18 ^ v15)) < 0) {
                    // 0x100003b84
                    v23 = *v17 + *(int32_t *)(v20 + (int64_t)(4 * (v15 - v18)));
                    v24 = v22 - v23;
                    v14 = v24 == 0 | v24 < 0 != ((v24 ^ v22) & (v23 ^ v22)) < 0 ? v23 : v22;
                    *(int32_t *)(*v13 + v21) = v14;
                } else {
                    // 0x100003b54
                    *(int32_t *)(*v13 + v21) = v22;
                }
                // 0x100003c3c
                v25 = v15 + 1;
            }
        }
        int32_t v26 = v12 + 1; // 0x100003c54
        while (v26 - v2 == 0 || v26 - v2 < 0 != ((v26 - v2 ^ v26) & (v26 ^ v2)) < 0) {
            // 0x100003ae8
            v12 = v26;
            v13 = (int64_t *)(8 * (int64_t)v12 + v9);
            *v13 = 4 * (int64_t)(v12 * v4) + v6;
            if (v3 == 0 || v11 < 0 != (v11 & v3) < 0) {
                // 0x100003b2c
                v16 = 16 * (int64_t)(v12 - 1) + v1;
                v17 = (int32_t *)(v16 + 12);
                v15 = 0;
                v18 = *(int32_t *)(v16 + 8);
                v19 = v18 - v15;
                v20 = *(int64_t *)((int64_t)(8 * v12 - 8) + v9);
                v21 = 4 * (int64_t)v15;
                v22 = *(int32_t *)(v20 + v21);
                if (v19 == 0 || v19 < 0 != ((v19 ^ v18) & (v18 ^ v15)) < 0) {
                    // 0x100003b84
                    v23 = *v17 + *(int32_t *)(v20 + (int64_t)(4 * (v15 - v18)));
                    v24 = v22 - v23;
                    v14 = v24 == 0 | v24 < 0 != ((v24 ^ v22) & (v23 ^ v22)) < 0 ? v23 : v22;
                    *(int32_t *)(*v13 + v21) = v14;
                } else {
                    // 0x100003b54
                    *(int32_t *)(*v13 + v21) = v22;
                }
                // 0x100003c3c
                v25 = v15 + 1;
                while (v25 - v3 == 0 || v25 - v3 < 0 != ((v25 - v3 ^ v25) & (v25 ^ v3)) < 0) {
                    // 0x100003b2c
                    v15 = v25;
                    v18 = *(int32_t *)(v16 + 8);
                    v19 = v18 - v15;
                    v20 = *(int64_t *)((int64_t)(8 * v12 - 8) + v9);
                    v21 = 4 * (int64_t)v15;
                    v22 = *(int32_t *)(v20 + v21);
                    if (v19 == 0 || v19 < 0 != ((v19 ^ v18) & (v18 ^ v15)) < 0) {
                        // 0x100003b84
                        v23 = *v17 + *(int32_t *)(v20 + (int64_t)(4 * (v15 - v18)));
                        v24 = v22 - v23;
                        v14 = v24 == 0 | v24 < 0 != ((v24 ^ v22) & (v23 ^ v22)) < 0 ? v23 : v22;
                        *(int32_t *)(*v13 + v21) = v14;
                    } else {
                        // 0x100003b54
                        *(int32_t *)(*v13 + v21) = v22;
                    }
                    // 0x100003c3c
                    v25 = v15 + 1;
                }
            }
            // 0x100003c50
            v26 = v12 + 1;
        }
    }
    int64_t result = (int64_t)_calloc(v2, 4); // 0x100003c68
    if (v2 < 1) {
        // 0x100003d20
        _free(v5);
        _free(v8);
        return result;
    }
    int64_t v27 = v7 >> 32;
    int64_t v28 = 8 * v27; // 0x100003ca0
    int64_t v29 = 4 * (int64_t)v3; // 0x100003ca8
    int32_t v30 = *(int32_t *)(v29 + *(int64_t *)(v28 + v9)); // 0x100003ca8
    int32_t v31 = *(int32_t *)(*(int64_t *)((v28 + 0xfffffff8 & 0xfffffff8) + v9) + v29); // 0x100003cc0
    int32_t v32 = v30 - v31; // 0x100003cc4
    int64_t v33; // 0x100003a54
    int32_t v34; // 0x100003a54
    int64_t v35; // 0x100003a54
    if (v32 == 0 || v32 < 0 != ((v32 ^ v30) & (v31 ^ v30)) < 0) {
        // 0x100003c98
        v33 = v27 - 1;
        v34 = v3;
    } else {
        // 0x100003cd4
        *(int32_t *)((4 * v27 + 0xfffffffc & 0xfffffffc) + result) = 1;
        v35 = v27 - 1;
        v33 = v35;
        v34 = v3 - *(int32_t *)(v1 + 8 + 16 * v35);
    }
    // 0x100003d10
    while (v33 >= 1) {
        int32_t v36 = v34;
        v27 = v33;
        v28 = 8 * v27;
        v29 = 4 * (int64_t)v36;
        v30 = *(int32_t *)(v29 + *(int64_t *)(v28 + v9));
        v31 = *(int32_t *)(*(int64_t *)((v28 + 0xfffffff8 & 0xfffffff8) + v9) + v29);
        v32 = v30 - v31;
        if (v32 == 0 || v32 < 0 != ((v32 ^ v30) & (v31 ^ v30)) < 0) {
            // 0x100003c98
            v33 = v27 - 1;
            v34 = v36;
        } else {
            // 0x100003cd4
            *(int32_t *)((4 * v27 + 0xfffffffc & 0xfffffffc) + result) = 1;
            v35 = v27 - 1;
            v33 = v35;
            v34 = v36 - *(int32_t *)(v1 + 8 + 16 * v35);
        }
    }
    // 0x100003d20
    _free(v5);
    _free(v8);
    return result;
}

// Address range: 0x100003d40 - 0x100003ea0
int64_t entry_point(void) {
    int64_t v1 = function_100003a54(); // 0x100003d70
    int64_t v2; // 0x100003d40
    for (int64_t i = 0; i < 22; i++) {
        // 0x100003d98
        if (*(int32_t *)(4 * i + v1) != 0) {
            // 0x100003db4
            _printf("%-22s %5d %5d\n", (char *)22, 400, v2);
        }
    }
    // 0x100003e5c
    _printf("%-22s %5d %5d\n", (char *)22, 400, v2);
    return 0;
}

// Address range: 0x100003ea0 - 0x100003eac
int64_t * function_100003ea0(int32_t nmemb, int32_t size) {
    // 0x100003ea0
    return _calloc(nmemb, size);
}

// Address range: 0x100003eac - 0x100003eb8
void function_100003eac(int64_t * ptr) {
    // 0x100003eac
    _free(ptr);
}

// Address range: 0x100003eb8 - 0x100003ec4
int64_t * function_100003eb8(int32_t size) {
    // 0x100003eb8
    return _malloc(size);
}

// Address range: 0x100003ec4 - 0x100003ed0
int32_t function_100003ec4(char * format, ...) {
    // 0x100003ec4
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

