//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef long double float128_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f5c(int64_t * a1, int64_t a2, int64_t a3);
int64_t function_100003f68(int64_t a1);
int32_t function_100003f74(char * format, ...);

// --------------------- Global Variables ---------------------

float128_t g1 = 4.24399158390680721358775060643269284e-314L; // 0x100003f80

// ------- Dynamically Linked Functions Without Header --------

int64_t ___snprintf_chk(int64_t * a1, int64_t a2, int64_t a3);
int64_t ___stack_chk_fail(int64_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d24 - 0x100003f5c
int64_t entry_point(void) {
    float128_t v1 = g1; // bp-48, 0x100003d5c
    int64_t v2; // bp-58, 0x100003d24
    ___snprintf_chk(&v2, 10, 0);
    int64_t v3 = &v2; // 0x100003da4
    char * v4 = (char *)(v3 | 1); // 0x100003da8
    int32_t v5; // 0x100003d24
    int32_t v6; // 0x100003d24
    int32_t v7; // 0x100003d24
    int32_t v8; // 0x100003d24
    int32_t v9; // 0x100003d24
    int64_t v10; // 0x100003d24
    if (*v4 != 0) {
        // 0x100003dbc
        v10 = &v1;
        v7 = 0;
        v5 = 0x96b3d0;
        while (true) {
          lab_0x100003dbc_2:
            // 0x100003dbc
            v6 = v5;
            v8 = v7;
            int32_t v11 = 1; // 0x100003d24
            int32_t v12 = 0; // 0x100003d24
            while (true) {
              lab_0x100003dbc:;
                int32_t v13 = v12;
                char v14 = *(char *)((int64_t)v13 + v3); // 0x100003dc4
                switch (v14) {
                    case 48: {
                        goto lab_0x100003e24;
                    }
                    case 53: {
                        goto lab_0x100003e24;
                    }
                    default: {
                        int32_t v15 = v11;
                        int32_t v16 = v13; // 0x100003e1c
                        if (v6 % ((int32_t)v14 - 48) != 0) {
                            // break -> 0x100003e24
                            break;
                        }
                        v16++;
                        char v17 = *(char *)((int64_t)v16 + v3); // 0x100003e74
                        while (v17 != 0) {
                            // 0x100003e88
                            if (v14 == v17) {
                                int32_t v18 = v8 + 1; // 0x100003ec8
                                v9 = v18 - 4 * v18 / 4;
                                goto lab_0x100003d68;
                            }
                            v16++;
                            v17 = *(char *)((int64_t)v16 + v3);
                        }
                        int32_t v19 = v15 + 1; // 0x100003da0
                        v11 = v19;
                        v12 = v15;
                        if (*(char *)((int64_t)v19 + v3) == 0) {
                            // break (via goto) -> 0x100003f0c
                            goto lab_0x100003f0c_2;
                        }
                        goto lab_0x100003dbc;
                    }
                }
            }
          lab_0x100003e24:;
            int32_t v20 = v8 + 1; // 0x100003e40
            v9 = v20 - 4 * v20 / 4;
            goto lab_0x100003d68;
        }
    }
  lab_0x100003f0c_2:;
    int32_t v21 = _printf("Number found : %d", 10); // 0x100003f24
    int64_t v22 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003f34
    if (v22 != *(int64_t *)*(int64_t *)0x100004010) {
        // 0x100003f48
        ___stack_chk_fail((int64_t)v21);
    }
    // 0x100003f4c
    return 0;
  lab_0x100003d68:;
    int32_t v23 = *(int32_t *)(4 * (int64_t)v8 + v10);
    ___snprintf_chk(&v2, 10, 0);
    v7 = v9;
    v5 = v6 - v23;
    if (*v4 == 0) {
        // break -> 0x100003f0c
        goto lab_0x100003f0c_2;
    }
    goto lab_0x100003dbc_2;
}

// Address range: 0x100003f5c - 0x100003f68
int64_t function_100003f5c(int64_t * a1, int64_t a2, int64_t a3) {
    // 0x100003f5c
    return ___snprintf_chk(a1, a2, a3);
}

// Address range: 0x100003f68 - 0x100003f74
int64_t function_100003f68(int64_t a1) {
    // 0x100003f68
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f74 - 0x100003f80
int32_t function_100003f74(char * format, ...) {
    // 0x100003f74
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

