//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f3c(int64_t a1);
int32_t function_100003f48(char * nptr);
int64_t * function_100003f54(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003f60(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1d0000001f; // 0x100003f6c

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _atoi(char * a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003cd0 - 0x100003f3c
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003ce4
    int64_t v2; // 0x100003cd0
    int32_t v3 = v2; // 0x100003cf0
    int64_t v4; // bp-72, 0x100003cd0
    int64_t v5 = (int64_t)_memcpy(&v4, &g1, 48); // 0x100003d18
    int64_t result = 1; // 0x100003d18
    if (v3 < 2 == (1 - v3 & v3) < 0) {
        int32_t v6 = _atoi((char *)*(int64_t *)(v2 + 8)); // 0x100003d28
        int32_t v7 = v6 - 1700; // 0x100003d30
        v5 = v6;
        result = 1;
        if (v7 != 0 && v7 < 0 == (1699 - v6 & v6) < 0) {
            int32_t v8 = _printf("%d-%02d-%d\n", (int64_t)&g1, 48, v2); // 0x100003ee0
            int64_t v9 = 1;
            int64_t v10 = v9; // 0x100003e4c
            while (v9 != 12) {
                // 0x100003e54
                v8 = _printf("%d-%02d-%d\n", (int64_t)&g1, 48, v2);
                v9 = v10 + 1;
                v10 = v9;
            }
            // 0x100003f00
            v5 = v8;
            result = 0;
        }
    }
    // 0x100003f00
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003f28
        ___stack_chk_fail(v5);
    }
    // 0x100003f2c
    return result;
}

// Address range: 0x100003f3c - 0x100003f48
int64_t function_100003f3c(int64_t a1) {
    // 0x100003f3c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f48 - 0x100003f54
int32_t function_100003f48(char * nptr) {
    // 0x100003f48
    return _atoi(nptr);
}

// Address range: 0x100003f54 - 0x100003f60
int64_t * function_100003f54(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003f54
    return _memcpy(dest, src, n);
}

// Address range: 0x100003f60 - 0x100003f6c
int32_t function_100003f60(char * format, ...) {
    // 0x100003f60
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

