//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <math.h>
#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003cac(void);
int64_t function_100003db4(void);
float64_t function_100003f60(float64_t a1);
int32_t function_100003f6c(char * format, ...);

// --------------------- Global Variables ---------------------

float64_t g1 = 1.8446744073709552e+19; // 0x100003f78

// ------- Dynamically Linked Functions Without Header --------

float64_t _log2(float64_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003cac - 0x100003db4
int64_t function_100003cac(void) {
    // 0x100003cac
    int64_t v1; // 0x100003cac
    int32_t v2 = v1; // 0x100003cb0
    if (v2 == 2) {
        // 0x100003da8
        return 1;
    }
    int32_t v3 = v2 - 1; // 0x100003cd8
    if (v3 == 0 || v3 < 0 != (v2 & -v2) < 0 || 2 * v2 / 2 == v2) {
        // 0x100003da8
        return 0;
    }
    // 0x100003d14
    __asm_sshll(0.0f, 0);
    float64_t v4; // 0x100003cac
    int32_t v5 = sqrt(v4); // 0x100003d30
    int32_t v6 = 3 - v5; // 0x100003d4c
    if (v6 != 0 && v6 < 0 == (v6 & v5) < 0) {
        // 0x100003da8
        return 1;
    }
    int32_t v7 = 3; // 0x100003d54
    int32_t v8 = v2 % v7;
    int32_t result = 0; // 0x100003d7c
    while (v8 != 0) {
        // 0x100003d44
        v7 += 2;
        int32_t v9 = v7 - v5; // 0x100003d4c
        result = v8;
        if (v9 != 0 && v9 < 0 == ((v9 ^ v7) & (v7 ^ v5)) < 0) {
            // break -> 0x100003da8
            break;
        }
        v8 = v2 % v7;
        result = 0;
    }
    // 0x100003da8
    return result;
}

// Address range: 0x100003db4 - 0x100003e7c
int64_t function_100003db4(void) {
    // 0x100003db4
    int64_t v1; // 0x100003db4
    int32_t v2 = v1; // 0x100003db8
    if (v2 == 2) {
        // 0x100003e70
        return 1;
    }
    int32_t v3 = 3 - v2; // 0x100003e10
    int32_t v4 = 3; // 0x100003e18
    if (v3 != 0 && v3 < 0 == (v3 & v2) < 0) {
        // 0x100003e70
        return 0;
    }
    int64_t v5 = 4;
    int64_t v6 = (v5 * v5 - 2) % (-1 - (-1 << (v1 & 0xffffffff)));
    v4++;
    while (v4 - v2 == 0 || v4 - v2 < 0 != ((v4 - v2 ^ v4) & (v4 ^ v2)) < 0) {
        // 0x100003e20
        v5 = v6;
        v6 = (v5 * v5 - 2) % (-1 - (-1 << (v1 & 0xffffffff)));
        v4++;
    }
    // 0x100003e70
    return v6 == 0;
}

// Address range: 0x100003e7c - 0x100003f60
int64_t entry_point(void) {
    // 0x100003e7c
    int128_t v1; // 0x100003e7c
    _log2((float64_t)(int64_t)v1);
    int32_t v2 = 0.5 * g1; // 0x100003ea8
    _printf(" Mersenne primes:\n");
    int32_t v3 = 2 - v2; // 0x100003ed0
    if (v3 != 0 && v3 < 0 == (v3 & v2) < 0) {
        // 0x100003f44
        _printf((char *)0x100003f98);
        return 0;
    }
    int32_t v4 = 2; // 0x100003f38
    int64_t v5; // 0x100003e7c
    if ((int32_t)function_100003cac() != 0) {
        // 0x100003ef8
        if ((int32_t)function_100003db4() != 0) {
            // 0x100003f10
            _printf(" M%u", (int32_t)v5);
        }
    }
    // 0x100003f34
    v4++;
    while (v4 - v2 == 0 || v4 - v2 < 0 != ((v4 - v2 ^ v4) & (v4 ^ v2)) < 0) {
        // 0x100003ee0
        if ((int32_t)function_100003cac() != 0) {
            // 0x100003ef8
            if ((int32_t)function_100003db4() != 0) {
                // 0x100003f10
                _printf(" M%u", (int32_t)v5);
            }
        }
        // 0x100003f34
        v4++;
    }
    // 0x100003f44
    _printf((char *)0x100003f98);
    return 0;
}

// Address range: 0x100003f60 - 0x100003f6c
float64_t function_100003f60(float64_t a1) {
    // 0x100003f60
    return _log2(a1);
}

// Address range: 0x100003f6c - 0x100003f78
int32_t function_100003f6c(char * format, ...) {
    // 0x100003f6c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

