//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003e38(void);
int64_t function_100003ec4(int64_t a1);
int64_t function_100003f5c(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003f68(int64_t a1);
int64_t * function_100003f74(int64_t * addr, int32_t len, int32_t prot, int32_t flags, int32_t fd, int32_t offset);
int32_t function_100003f80(int64_t * addr, int32_t len);
int32_t function_100003f8c(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x82444030424448b; // 0x100003f98

// ------- Dynamically Linked Functions Without Header --------

int64_t ___memcpy_chk(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t ___stack_chk_fail(int64_t a1);
int64_t * _mmap(int64_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
int32_t _munmap(int64_t * a1, int32_t a2);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003e38 - 0x100003ec4
int64_t function_100003e38(void) {
    int64_t v1 = g1; // bp-40, 0x100003e70
    int64_t * v2 = _mmap(NULL, 9, 7, 0x1002, -1, 0); // 0x100003e98
    ___memcpy_chk((int64_t)v2, (int64_t)&v1, 9, -1);
    int64_t v3; // 0x100003e38
    return v3 & 0xffffffff;
}

// Address range: 0x100003ec4 - 0x100003f10
int64_t function_100003ec4(int64_t a1) {
    // 0x100003ec4
    int64_t v1; // 0x100003ec4
    int32_t v2 = _munmap((int64_t *)v1, (int32_t)a1); // 0x100003ed0
    if (*(int64_t *)*(int64_t *)0x100004010 != *(int64_t *)(v1 - 8)) {
        // 0x100003efc
        ___stack_chk_fail((int64_t)v2);
    }
    // 0x100003f00
    return v1 & 0xffffffff;
}

// Address range: 0x100003f10 - 0x100003f5c
int64_t entry_point(void) {
    // 0x100003f10
    function_100003e38();
    _printf("%d\n", 12);
    return 0;
}

// Address range: 0x100003f5c - 0x100003f68
int64_t function_100003f5c(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003f5c
    return ___memcpy_chk(a1, a2, a3, a4);
}

// Address range: 0x100003f68 - 0x100003f74
int64_t function_100003f68(int64_t a1) {
    // 0x100003f68
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f74 - 0x100003f80
int64_t * function_100003f74(int64_t * addr, int32_t len, int32_t prot, int32_t flags, int32_t fd, int32_t offset) {
    // 0x100003f74
    return _mmap(addr, len, prot, flags, fd, offset);
}

// Address range: 0x100003f80 - 0x100003f8c
int32_t function_100003f80(int64_t * addr, int32_t len) {
    // 0x100003f80
    return _munmap(addr, len);
}

// Address range: 0x100003f8c - 0x100003f98
int32_t function_100003f8c(char * format, ...) {
    // 0x100003f8c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

