//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003ac4(void);
int64_t function_100003ca8(void);
int64_t function_100003cfc(void);
int32_t function_100003ef4(char * nptr);
int32_t function_100003f00(int32_t c);
int64_t * function_100003f0c(int32_t size);
int32_t function_100003f18(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _atoi(char * a1);
int32_t _isdigit(int32_t a1);
int64_t * _malloc(int32_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003ac4 - 0x100003ca8
int64_t function_100003ac4(void) {
    // 0x100003ac4
    int64_t v1; // 0x100003ac4
    int32_t v2 = v1; // 0x100003ad0
    if (v2 < 4 != (3 - v2 & v2) < 0) {
        // 0x100003c98
        return 0;
    }
    int32_t v3 = v2 / 4; // 0x100003af0
    if (4 * v3 != v2) {
        // 0x100003c98
        return 0;
    }
    int64_t result = (int64_t)_malloc(8 * v2); // 0x100003b44
    int32_t v4 = -v2;
    if (v4 < 0 == (v4 & v2) < 0) {
        // 0x100003c98
        return result;
    }
    int32_t v5 = v2 * v2; // 0x100003b24
    int32_t v6 = 0; // 0x100003b8c
    *(int64_t *)(8 * (int64_t)v6 + result) = (int64_t)_malloc(4 * v2);
    v6++;
    int32_t v7 = v6 - v2; // 0x100003b5c
    int32_t v8 = 0; // 0x100003b64
    while (v7 < 0 != ((v7 ^ v6) & (v6 ^ v2)) < 0) {
        // 0x100003b6c
        *(int64_t *)(8 * (int64_t)v6 + result) = (int64_t)_malloc(4 * v2);
        v6++;
        v7 = v6 - v2;
        v8 = 0;
    }
    int32_t v9 = 4 * v8 / v3; // 0x100003bf4
    int32_t v10 = 0; // 0x100003c60
    int32_t v11 = 0; // 0x100003ac4
    int32_t v12 = v11 + 1;
    int32_t v13 = (1 << v10 / v3 + v9 & 0x9669) == 0 ? v5 - v11 : v12;
    int64_t v14 = *(int64_t *)(8 * (int64_t)v8 + result); // 0x100003c4c
    *(int32_t *)(v14 + 4 * (int64_t)v10) = v13;
    v10++;
    int32_t v15 = v10 - v2; // 0x100003bcc
    v11 = v12;
    while (v15 < 0 != ((v15 ^ v10) & (v10 ^ v2)) < 0) {
        // 0x100003bdc
        v12 = v11 + 1;
        v13 = (1 << v10 / v3 + v9 & 0x9669) == 0 ? v5 - v11 : v12;
        v14 = *(int64_t *)(8 * (int64_t)v8 + result);
        *(int32_t *)(v14 + 4 * (int64_t)v10) = v13;
        v10++;
        v15 = v10 - v2;
        v11 = v12;
    }
    int32_t v16 = v8 + 1; // 0x100003c80
    int32_t v17 = v16 - v2; // 0x100003bac
    v8 = v16;
    while (v17 < 0 != ((v17 ^ v16) & (v16 ^ v2)) < 0) {
        // 0x100003bdc
        v9 = 4 * v8 / v3;
        v10 = 0;
        v11 = v12;
        v12 = v11 + 1;
        v13 = (1 << v10 / v3 + v9 & 0x9669) == 0 ? v5 - v11 : v12;
        v14 = *(int64_t *)(8 * (int64_t)v8 + result);
        *(int32_t *)(v14 + 4 * (int64_t)v10) = v13;
        v10++;
        v15 = v10 - v2;
        v11 = v12;
        while (v15 < 0 != ((v15 ^ v10) & (v10 ^ v2)) < 0) {
            // 0x100003bdc
            v12 = v11 + 1;
            v13 = (1 << v10 / v3 + v9 & 0x9669) == 0 ? v5 - v11 : v12;
            v14 = *(int64_t *)(8 * (int64_t)v8 + result);
            *(int32_t *)(v14 + 4 * (int64_t)v10) = v13;
            v10++;
            v15 = v10 - v2;
            v11 = v12;
        }
        // 0x100003c7c
        v16 = v8 + 1;
        v17 = v16 - v2;
        v8 = v16;
    }
    // 0x100003c98
    return result;
}

// Address range: 0x100003ca8 - 0x100003cfc
int64_t function_100003ca8(void) {
    // 0x100003ca8
    int64_t v1; // 0x100003ca8
    int32_t v2 = v1; // 0x100003cac
    int32_t result = 1; // 0x100003cc8
    if (v2 < 10 != (9 - v2 & v2) < 0) {
        // 0x100003cf0
        return 1;
    }
    int32_t v3 = v2;
    int32_t v4 = v3 / 10; // 0x100003cd8
    result++;
    while (v3 < 100 == (9 - v4 & v4) < 0) {
        // 0x100003cd0
        v3 = v4;
        v4 = v3 / 10;
        result++;
    }
    // 0x100003cf0
    return result;
}

// Address range: 0x100003cfc - 0x100003e54
int64_t function_100003cfc(void) {
    // 0x100003cfc
    int64_t v1; // 0x100003cfc
    int32_t v2 = v1; // 0x100003d0c
    function_100003ca8();
    int32_t v3 = -v2;
    int32_t result = _printf("Doubly Magic Square of Order : %d and Magic Constant : %d\n\n", v1, v1); // 0x100003d84
    if (v3 < 0 == (v3 & v2) < 0) {
        // 0x100003e48
        return result;
    }
    int32_t v4 = 0; // 0x100003e3c
    int32_t v5 = 0; // 0x100003e1c
    function_100003ca8();
    _printf("%*s%d", v1, (char *)v1, v1);
    v5++;
    while (v5 - v2 < 0 != ((v5 - v2 ^ v5) & (v5 ^ v2)) < 0) {
        // 0x100003dac
        function_100003ca8();
        _printf("%*s%d", v1, (char *)v1, v1);
        v5++;
    }
    // 0x100003e28
    v4++;
    int32_t v6 = v4 - v2; // 0x100003d7c
    result = _printf("\n");
    while (v6 < 0 != ((v6 ^ v4) & (v4 ^ v2)) < 0) {
        // 0x100003dac
        v5 = 0;
        function_100003ca8();
        _printf("%*s%d", v1, (char *)v1, v1);
        v5++;
        while (v5 - v2 < 0 != ((v5 - v2 ^ v5) & (v5 ^ v2)) < 0) {
            // 0x100003dac
            function_100003ca8();
            _printf("%*s%d", v1, (char *)v1, v1);
            v5++;
        }
        // 0x100003e28
        v4++;
        v6 = v4 - v2;
        result = _printf("\n");
    }
    // 0x100003e48
    return result;
}

// Address range: 0x100003e54 - 0x100003ef4
int64_t entry_point(void) {
    // 0x100003e54
    int64_t v1; // 0x100003e54
    if ((int32_t)v1 != 2) {
        // 0x100003ea0
        _printf("Usage : %s <integer specifying rows in magic square>", (char *)v1);
        // 0x100003ee4
        return 0;
    }
    int64_t * v2 = (int64_t *)(v1 + 8); // 0x100003e84
    if (_isdigit((int32_t)*(char *)*v2) == 0) {
        // 0x100003ea0
        _printf("Usage : %s <integer specifying rows in magic square>", (char *)v1);
        // 0x100003ee4
        return 0;
    }
    // 0x100003ec0
    _atoi((char *)*v2);
    function_100003ac4();
    function_100003cfc();
    // 0x100003ee4
    return 0;
}

// Address range: 0x100003ef4 - 0x100003f00
int32_t function_100003ef4(char * nptr) {
    // 0x100003ef4
    return _atoi(nptr);
}

// Address range: 0x100003f00 - 0x100003f0c
int32_t function_100003f00(int32_t c) {
    // 0x100003f00
    return _isdigit(c);
}

// Address range: 0x100003f0c - 0x100003f18
int64_t * function_100003f0c(int32_t size) {
    // 0x100003f0c
    return _malloc(size);
}

// Address range: 0x100003f18 - 0x100003f24
int32_t function_100003f18(char * format, ...) {
    // 0x100003f18
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 8

