//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int32_t function_100003f58(char * format, ...);
int32_t function_100003f64(char * s);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _puts(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003ec0 - 0x100003f58
int64_t entry_point(void) {
    // 0x100003ec0
    _puts("Mapping [0,10] to [-1,0] at intervals of 1:");
    int32_t v1 = 0;
    int64_t v2; // 0x100003ec0
    int128_t v3; // 0x100003ec0
    _printf("f(%d) = %g\n", v2, (float64_t)(int64_t)v3);
    int32_t v4 = v1 + 1; // 0x100003f3c
    while (v1 == 9 || v1 < 9 != (8 - v1 & v4) < 0) {
        // 0x100003ef8
        v1 = v4;
        _printf("f(%d) = %g\n", v2, (float64_t)(int64_t)v3);
        v4 = v1 + 1;
    }
    // 0x100003f48
    return 0;
}

// Address range: 0x100003f58 - 0x100003f64
int32_t function_100003f58(char * format, ...) {
    // 0x100003f58
    return _printf(format);
}

// Address range: 0x100003f64 - 0x100003f70
int32_t function_100003f64(char * s) {
    // 0x100003f64
    return _puts(s);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

