//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000038e8(void);
int64_t function_1000039e4(void);
int64_t function_100003b74(void);
int64_t function_100003bf0(void);
int64_t function_100003e5c(char * a1, char * a2, int64_t a3, char * a4);
int64_t function_100003e68(void);
int64_t function_100003e74(int64_t a1, int64_t a2, int64_t a3);
void function_100003e80(int32_t status);
int32_t function_100003e8c(struct _IO_FILE * stream);
struct _IO_FILE * function_100003e98(char * filename, char * modes);
void function_100003ea4(int64_t * ptr);
int32_t function_100003eb0(struct _IO_FILE * stream, char * format, ...);
int32_t function_100003ebc(char * format, ...);
int64_t * function_100003ec8(int64_t * ptr, int32_t size);
int32_t function_100003ed4(char * s);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___assert_rtn(char * a1, char * a2, int64_t a3, char * a4);
int64_t ___stack_chk_fail(void);
int64_t ___strcpy_chk(int64_t a1, int64_t a2, int64_t a3);
int32_t _fclose(struct _IO_FILE * a1);
struct _IO_FILE * _fopen(char * a1, char * a2);
void _free(int64_t * a1);
int32_t _fscanf(struct _IO_FILE * a1, char * a2, ...);
int32_t _printf(char * a1, ...);
int64_t * _realloc(int64_t * a1, int32_t a2);
int32_t _strlen(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x1000038e8 - 0x1000039e4
int64_t function_1000038e8(void) {
    // 0x1000038e8
    int64_t v1; // 0x1000038e8
    if (v1 == 0) {
        // 0x100003918
        ___assert_rtn("is_ordered_word", "ordered-words-2.c", 18, "word != NULL");
    }
    int32_t v2 = 0; // 0x100003940
    char v3 = *(char *)(v1 + (int64_t)v2); // 0x10000394c
    int64_t result = 1; // 0x100003958
    while (v3 != 0) {
        int32_t v4 = v3; // 0x100003968
        v2++;
        char v5 = *(char *)(v1 + (int64_t)v2); // 0x100003978
        int32_t v6 = v4 - (int32_t)v5; // 0x10000397c
        result = 0;
        if (v5 != 0 && v6 != 0 && v6 < 0 == ((v6 ^ v4) & (int32_t)(v5 ^ v3)) < 0) {
            // break -> 0x1000039d4
            break;
        }
        v3 = *(char *)(v1 + (int64_t)v2);
        result = 1;
    }
    // 0x1000039d4
    return result;
}

// Address range: 0x1000039e4 - 0x100003b74
int64_t function_1000039e4(void) {
    // 0x1000039e4
    int64_t v1; // 0x1000039e4
    int64_t v2; // 0x1000039e4
    if (v1 == 0) {
        // 0x100003a18
        v2 = ___assert_rtn("array_append", "ordered-words-2.c", 30, "words_array != NULL");
    }
    int64_t v3 = v2; // 0x100003a54
    if (v1 == 0) {
        // 0x100003a5c
        v3 = ___assert_rtn("array_append", "ordered-words-2.c", 31, "new_word != NULL");
    }
    int64_t * v4 = (int64_t *)(v1 + 8); // 0x100003a84
    int64_t v5 = *v4; // 0x100003a84
    int64_t v6 = v5; // 0x100003abc
    int64_t v7 = v3; // 0x100003abc
    if (v5 == 0 != (v3 == 0)) {
        // 0x100003ac4
        v7 = ___assert_rtn("array_append", "ordered-words-2.c", 32, "(words_array->len == 0) == (words_array->words == NULL)");
        v6 = *v4;
    }
    int64_t v8 = v6 + 1; // 0x100003af0
    *v4 = v8;
    int64_t * v9 = _realloc((int64_t *)v7, 100 * (int32_t)v8); // 0x100003b10
    int64_t v10 = (int64_t)v9; // 0x100003b10
    *(int64_t *)v1 = v10;
    if (v9 != NULL) {
        // 0x100003b3c
        return ___strcpy_chk(v10 - 100 + 100 * *v4, v1, -1);
    }
    // 0x100003b34
    _exit(1);
    // UNREACHABLE
}

// Address range: 0x100003b74 - 0x100003bf0
int64_t function_100003b74(void) {
    // 0x100003b74
    int64_t v1; // 0x100003b74
    int64_t v2; // 0x100003b74
    if (v1 == 0) {
        // 0x100003ba4
        v2 = ___assert_rtn("array_free", "ordered-words-2.c", 44, "words_array != NULL");
    }
    // 0x100003bc8
    _free((int64_t *)v2);
    *(int64_t *)v1 = 0;
    *(int64_t *)(v1 + 8) = 0;
    return &g1;
}

// Address range: 0x100003bf0 - 0x100003cb4
int64_t function_100003bf0(void) {
    // 0x100003bf0
    int64_t v1; // 0x100003bf0
    int64_t v2; // 0x100003bf0
    if (v1 == 0) {
        // 0x100003c20
        ___assert_rtn("list_print", "ordered-words-2.c", 52, "words_array != NULL");
        v2 = (int64_t)"ordered-words-2.c";
    }
    // 0x100003c44
    int32_t result; // 0x100003c90
    for (int64_t i = 0; i < *(int64_t *)(v1 + 8); i++) {
        // 0x100003c68
        result = _printf("\n%s", (char *)v2);
    }
    // 0x100003ca8
    return result;
}

// Address range: 0x100003cb4 - 0x100003e5c
int64_t entry_point(void) {
    struct _IO_FILE * v1 = _fopen("unixdict.txt", "r"); // 0x100003ce4
    int64_t result = 1; // 0x100003cf8
    char v2; // bp-124, 0x100003cb4
    int32_t v3; // 0x100003cb4
    int32_t v4; // 0x100003cb4
    int32_t v5; // 0x100003cb4
    uint64_t v6; // 0x100003d54
    char ** v7; // 0x100003d38
    if (v1 != NULL) {
        // 0x100003d0c
        v2 = 0;
        int64_t v8; // 0x100003cb4
        v7 = (char **)v8;
        v3 = 0;
        if (_fscanf(v1, "%99s\n", v7) != -1) {
            while (true) {
              lab_0x100003d4c:
                // 0x100003d4c
                v4 = v3;
                uint64_t v9 = (int64_t)_strlen(&v2); // 0x100003d50
                v6 = (int64_t)v4;
                if (v9 == v6 || v9 < v6) {
                    goto lab_0x100003db0;
                } else {
                    // 0x100003d68
                    if ((int32_t)function_1000038e8() == 0) {
                        goto lab_0x100003db0;
                    } else {
                        int32_t v10 = _strlen(&v2); // 0x100003d88
                        function_100003b74();
                        function_1000039e4();
                        v5 = v10;
                        goto lab_0x100003df8;
                    }
                }
            }
        }
      lab_0x100003dfc:
        // 0x100003dfc
        _fclose(v1);
        function_100003bf0();
        function_100003b74();
        result = 0;
    }
    int64_t v11 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003e34
    if (v11 != *(int64_t *)*(int64_t *)0x100004010) {
        // 0x100003e48
        ___stack_chk_fail();
    }
    // 0x100003e4c
    return result;
  lab_0x100003db0:;
    int32_t v12 = _strlen(&v2); // 0x100003db4
    v5 = v4;
    if ((int64_t)v12 == v6) {
        // 0x100003dcc
        v5 = v4;
        if ((int32_t)function_1000038e8() != 0) {
            // 0x100003de4
            function_1000039e4();
            v5 = v4;
        }
    }
    goto lab_0x100003df8;
  lab_0x100003df8:
    // 0x100003df8
    v3 = v5;
    if (_fscanf(v1, "%99s\n", v7) == -1) {
        // break -> 0x100003dfc
        goto lab_0x100003dfc;
    }
    goto lab_0x100003d4c;
}

// Address range: 0x100003e5c - 0x100003e68
int64_t function_100003e5c(char * a1, char * a2, int64_t a3, char * a4) {
    // 0x100003e5c
    return ___assert_rtn(a1, a2, a3, a4);
}

// Address range: 0x100003e68 - 0x100003e74
int64_t function_100003e68(void) {
    // 0x100003e68
    return ___stack_chk_fail();
}

// Address range: 0x100003e74 - 0x100003e80
int64_t function_100003e74(int64_t a1, int64_t a2, int64_t a3) {
    // 0x100003e74
    return ___strcpy_chk(a1, a2, a3);
}

// Address range: 0x100003e80 - 0x100003e8c
void function_100003e80(int32_t status) {
    // 0x100003e80
    _exit(status);
}

// Address range: 0x100003e8c - 0x100003e98
int32_t function_100003e8c(struct _IO_FILE * stream) {
    // 0x100003e8c
    return _fclose(stream);
}

// Address range: 0x100003e98 - 0x100003ea4
struct _IO_FILE * function_100003e98(char * filename, char * modes) {
    // 0x100003e98
    return _fopen(filename, modes);
}

// Address range: 0x100003ea4 - 0x100003eb0
void function_100003ea4(int64_t * ptr) {
    // 0x100003ea4
    _free(ptr);
}

// Address range: 0x100003eb0 - 0x100003ebc
int32_t function_100003eb0(struct _IO_FILE * stream, char * format, ...) {
    // 0x100003eb0
    return _fscanf(stream, format);
}

// Address range: 0x100003ebc - 0x100003ec8
int32_t function_100003ebc(char * format, ...) {
    // 0x100003ebc
    return _printf(format);
}

// Address range: 0x100003ec8 - 0x100003ed4
int64_t * function_100003ec8(int64_t * ptr, int32_t size) {
    // 0x100003ec8
    return _realloc(ptr, size);
}

// Address range: 0x100003ed4 - 0x100003ee0
int32_t function_100003ed4(char * s) {
    // 0x100003ed4
    return _strlen(s);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 16

