//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003eb4(void);
int64_t function_100003f38(char * a1, char * a2, int64_t a3, char * a4);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___assert_rtn(char * a1, char * a2, int64_t a3, char * a4);

// ------------------------ Functions -------------------------

// Address range: 0x100003d74 - 0x100003eb4
int64_t entry_point(void) {
    // 0x100003d74
    if ((uint64_t)function_100003eb4() % 2 == 0) {
        // 0x100003da4
        ___assert_rtn("main", "palindrome.c", 16, "isPalindrome(0)");
    }
    // 0x100003dc8
    if (function_100003eb4() % 2 == 0) {
        // 0x100003df0
        ___assert_rtn("main", "palindrome.c", 17, "isPalindrome(1)");
    }
    // 0x100003e14
    if (function_100003eb4() % 2 == 0) {
        // 0x100003e34
        ___assert_rtn("main", "palindrome.c", 18, "isPalindrome(12321)");
    }
    // 0x100003e58
    if (function_100003eb4() % 2 != 0) {
        // 0x100003e80
        ___assert_rtn("main", "palindrome.c", 19, "!isPalindrome(1234)");
    }
    // 0x100003ea4
    return 0;
}

// Address range: 0x100003eb4 - 0x100003f38
int64_t function_100003eb4(void) {
    // 0x100003eb4
    int64_t v1; // 0x100003eb4
    int32_t v2 = v1; // 0x100003eb8
    if (v2 == 0) {
        // 0x100003f1c
        return 0 == v2;
    }
    int32_t v3 = 0; // 0x100003ed8
    int32_t v4 = v2;
    v3 = 10 * v3 + v4 % 10;
    int32_t v5 = v4 / 10; // 0x100003ed8
    while (v4 >= 10) {
        // 0x100003ee0
        v4 = v5;
        v3 = 10 * v3 + v4 % 10;
        v5 = v4 / 10;
    }
    // 0x100003f1c
    return v3 == v2;
}

// Address range: 0x100003f38 - 0x100003f44
int64_t function_100003f38(char * a1, char * a2, int64_t a3, char * a4) {
    // 0x100003f38
    return ___assert_rtn(a1, a2, a3, a4);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

