//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003d94(void);
int64_t function_100003f28(void);
int32_t function_100003f34(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(void);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003d94 - 0x100003e38
int64_t function_100003d94(void) {
    // 0x100003d94
    int64_t v1; // 0x100003d94
    char v2 = *(char *)v1; // 0x100003db4
    if (v2 == 0) {
        // 0x100003e20
        return false;
    }
    int32_t v3 = 0x3ffffff;
    int32_t v4 = v2;
    int32_t v5 = v4 & -33; // 0x100003dd0
    int32_t v6 = v5 - 90; // 0x100003dd8
    int32_t v7 = v3; // 0x100003de0
    int32_t v8; // 0x100003dec
    if (v6 == 0 || v6 < 0 != (89 - v5 & v4) < 0) {
        // 0x100003de8
        v8 = v5 - 65;
        v7 = v3;
        if (v8 < 0 == (64 - v5 & v4) < 0) {
            // 0x100003dfc
            v7 = v3 & (-1 << v8) - 1;
        }
    }
    // 0x100003e1c
    int64_t v9; // 0x100003d94
    int64_t v10 = v9 + 1;
    int32_t v11 = v7;
    char v12 = *(char *)v10; // 0x100003db4
    while (v12 != 0) {
        // 0x100003dcc
        v3 = v11;
        v4 = v12;
        v5 = v4 & -33;
        v6 = v5 - 90;
        v7 = v3;
        if (v6 == 0 || v6 < 0 != (89 - v5 & v4) < 0) {
            // 0x100003de8
            v8 = v5 - 65;
            v7 = v3;
            if (v8 < 0 == (64 - v5 & v4) < 0) {
                // 0x100003dfc
                v7 = v3 & (-1 << v8) - 1;
            }
        }
        // 0x100003e1c
        v10++;
        v11 = v7;
        v12 = *(char *)v10;
    }
    // 0x100003e20
    return v11 == 0;
}

// Address range: 0x100003e38 - 0x100003f28
int64_t entry_point(void) {
    for (int32_t i = 0; i < 2; i++) {
        // 0x100003e84
        function_100003d94();
        int64_t v1; // 0x100003e38
        _printf("%s: %s\n", (char *)v1, (char *)v1);
    }
    int64_t v2 = *(int64_t *)0x100004008; // 0x100003efc
    if (*(int64_t *)v2 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003f14
        ___stack_chk_fail();
    }
    // 0x100003f18
    return 0;
}

// Address range: 0x100003f28 - 0x100003f34
int64_t function_100003f28(void) {
    // 0x100003f28
    return ___stack_chk_fail();
}

// Address range: 0x100003f34 - 0x100003f40
int32_t function_100003f34(char * format, ...) {
    // 0x100003f34
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

