//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000039dc(void);
int64_t function_100003ae0(void);
int64_t function_100003b74(void);
int64_t function_100003c08(void);
int64_t function_100003c98(void);
void function_100003e7c(int32_t status);
int32_t function_100003e88(char * format, ...);
int32_t function_100003e94(void);
int32_t function_100003ea0(char * format, ...);
void function_100003eac(int32_t seed);
int32_t function_100003eb8(int32_t * timer);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _rand(void);
int32_t _scanf(char * a1, ...);
void _srand(int32_t a1);
int32_t _time(int32_t * a1);

// ------------------------ Functions -------------------------

// Address range: 0x1000039dc - 0x100003ae0
int64_t function_1000039dc(void) {
    // 0x1000039dc
    int64_t v1; // 0x1000039dc
    char v2 = *(char *)v1; // 0x1000039f8
    char v3 = v2; // 0x100003a2c
    int32_t v4 = 4; // 0x100003a2c
    int32_t v5 = 0; // 0x100003a2c
    int64_t result; // 0x1000039dc
    if (v2 == 0) {
        // 0x100003ac8
        result = 0;
        // 0x100003ad4
        return result;
    }
    int32_t v6; // 0x1000039dc
    int32_t v7; // 0x1000039dc
    while (true) {
      lab_0x100003a34:;
        int32_t v8 = v5;
        v7 = v4;
        v6 = v8;
        result = 0xffffffff;
        switch (v3) {
            case 72: {
                // 0x100003a94
                v6 = v8 | v7;
                goto lab_0x100003ad4;
            }
            case 84: {
                goto lab_0x100003ad4;
            }
            case 104: {
                // 0x100003a94
                v6 = v8 | v7;
                goto lab_0x100003ad4;
            }
            case 116: {
                goto lab_0x100003ad4;
            }
            default: {
                return result;
            }
        }
    }
  lab_0x100003ad4:;
    // 0x100003ab8
    int64_t v9; // 0x1000039dc
    int64_t v10 = v9 + 1; // 0x100003a38
    v5 = v6;
    v4 = v7 >> 1;
    v3 = *(char *)v10;
    v9 = v10;
    int32_t result2 = v5; // 0x100003a2c
    if (v4 != 0 != v3 != 0) {
        // 0x100003ad4
        return result2;
    }
    goto lab_0x100003a34;
}

// Address range: 0x100003ae0 - 0x100003b74
int64_t function_100003ae0(void) {
    int32_t result; // 0x100003b50
    for (int32_t i = 2; i > -1; i--) {
        // 0x100003b10
        int64_t v1; // 0x100003ae0
        result = _printf("%c", (char)v1);
    }
    // 0x100003b68
    return result;
}

// Address range: 0x100003b74 - 0x100003c08
int64_t function_100003b74(void) {
    // 0x100003b74
    int64_t v1; // 0x100003b74
    _printf("Enter your sequence of %d (h/t): ", v1);
    char ** v2 = (char **)v1; // 0x100003bb0
    if (_scanf("%3s", v2) != 1) {
        // 0x100003bc4
        _exit(1);
        // UNREACHABLE
    }
    int64_t v3 = function_1000039dc(); // 0x100003bd0
    while ((int32_t)v3 == -1) {
        // 0x100003bf8
        _printf("Please enter only h/t characters: ");
        if (_scanf("%3s", v2) != 1) {
            // 0x100003bc4
            _exit(1);
            // UNREACHABLE
        }
        v3 = function_1000039dc();
    }
    // 0x100003be8
    return v3 & 0xffffffff;
}

// Address range: 0x100003c08 - 0x100003c98
int64_t function_100003c08(void) {
    // 0x100003c08
    int64_t v1; // 0x100003c08
    int32_t v2 = v1; // 0x100003c14
    _printf("Computers sequence of %d is: ", v1);
    int32_t result; // 0x100003c08
    if (v2 == -1) {
        // 0x100003c44
        result = _rand() % 8;
    } else {
        // 0x100003c54
        result = 2 * v2 & 4 ^ 4 | v2 >> 1;
    }
    // 0x100003c74
    function_100003ae0();
    _printf("\n");
    return result;
}

// Address range: 0x100003c98 - 0x100003d9c
int64_t function_100003c98(void) {
    // 0x100003c98
    int64_t v1; // 0x100003c98
    int32_t v2 = v1; // 0x100003ca4
    int32_t v3 = _rand() % 8; // 0x100003cb0
    _printf("Tossed sequence: ");
    function_100003ae0();
    if (v3 == v2) {
        // 0x100003ce8
        _printf("\nUser wins!\n");
        // 0x100003d8c
        return 1;
    }
    int32_t v4 = v3; // 0x100003d48
    while (v4 != (int32_t)v1) {
        // 0x100003d2c
        v4 = _rand() % 2 | 2 * v4 & 6;
        _printf("%c", (char)v1);
        if (v4 == v2) {
            // 0x100003ce8
            _printf("\nUser wins!\n");
            // 0x100003d8c
            return 1;
        }
    }
    // 0x100003d18
    _printf("\nAi wins!\n");
    // 0x100003d8c
    return 0;
}

// Address range: 0x100003d9c - 0x100003e7c
int64_t entry_point(void) {
    // 0x100003d9c
    _srand(_time(NULL));
    while (true) {
        // 0x100003dc4
        _printf("\n");
        int64_t v1; // 0x100003d9c
        if (_rand() % 2 == 0) {
            // 0x100003e08
            function_100003b74();
            v1 = function_100003c08();
        } else {
            int64_t v2 = function_100003c08(); // 0x100003df4
            function_100003b74();
            v1 = v2;
        }
        // 0x100003e20
        function_100003c98();
        int64_t v3; // 0x100003d9c
        _printf("You have won %d out of %d games\n", v1 & 0xffffffff, v3);
        _printf("=================================\n");
    }
}

// Address range: 0x100003e7c - 0x100003e88
void function_100003e7c(int32_t status) {
    // 0x100003e7c
    _exit(status);
}

// Address range: 0x100003e88 - 0x100003e94
int32_t function_100003e88(char * format, ...) {
    // 0x100003e88
    return _printf(format);
}

// Address range: 0x100003e94 - 0x100003ea0
int32_t function_100003e94(void) {
    // 0x100003e94
    return _rand();
}

// Address range: 0x100003ea0 - 0x100003eac
int32_t function_100003ea0(char * format, ...) {
    // 0x100003ea0
    return _scanf(format);
}

// Address range: 0x100003eac - 0x100003eb8
void function_100003eac(int32_t seed) {
    // 0x100003eac
    _srand(seed);
}

// Address range: 0x100003eb8 - 0x100003ec4
int32_t function_100003eb8(int32_t * timer) {
    // 0x100003eb8
    return _time(timer);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 12

