//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
void function_100003f30(int32_t status);
int32_t function_100003f3c(struct _IO_FILE * stream);
struct _IO_FILE * function_100003f48(char * filename, char * modes);
void function_100003f54(int64_t * ptr);
int32_t function_100003f60(char ** lineptr, int32_t * n, struct _IO_FILE * stream);
int32_t function_100003f6c(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _fclose(struct _IO_FILE * a1);
struct _IO_FILE * _fopen(char * a1, char * a2);
void _free(int64_t * a1);
int32_t _getline(char ** a1, int32_t * a2, struct _IO_FILE * a3);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003e70 - 0x100003f30
int64_t entry_point(void) {
    int64_t v1 = 0; // bp-40, 0x100003e80
    int64_t v2 = 0; // bp-48, 0x100003e84
    struct _IO_FILE * v3 = _fopen("file.txt", "r"); // 0x100003e98
    if (v3 == NULL) {
        // 0x100003eb4
        _exit(1);
        // UNREACHABLE
    }
    // 0x100003ec0
    if (_getline((char **)&v1, (int32_t *)&v2, v3) == -1) {
        // 0x100003f18
        _free((int64_t *)v1);
        _fclose(v3);
        return 0;
    }
    _printf("Retrieved line of length %u :\n", (int32_t)(int64_t)&v2);
    _printf("%s", &v2);
    // 0x100003ee4
    while (_getline((char **)&v1, (int32_t *)&v2, v3) != -1) {
        // 0x100003ee4
        _printf("Retrieved line of length %u :\n", (int32_t)(int64_t)&v2);
        _printf("%s", &v2);
    }
    // 0x100003f18
    _free((int64_t *)v1);
    _fclose(v3);
    return 0;
}

// Address range: 0x100003f30 - 0x100003f3c
void function_100003f30(int32_t status) {
    // 0x100003f30
    _exit(status);
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(struct _IO_FILE * stream) {
    // 0x100003f3c
    return _fclose(stream);
}

// Address range: 0x100003f48 - 0x100003f54
struct _IO_FILE * function_100003f48(char * filename, char * modes) {
    // 0x100003f48
    return _fopen(filename, modes);
}

// Address range: 0x100003f54 - 0x100003f60
void function_100003f54(int64_t * ptr) {
    // 0x100003f54
    _free(ptr);
}

// Address range: 0x100003f60 - 0x100003f6c
int32_t function_100003f60(char ** lineptr, int32_t * n, struct _IO_FILE * stream) {
    // 0x100003f60
    return _getline(lineptr, n, stream);
}

// Address range: 0x100003f6c - 0x100003f78
int32_t function_100003f6c(char * format, ...) {
    // 0x100003f6c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 7

