//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003df8(int64_t * a1);
int64_t function_100003ec4(int64_t a1);
int64_t * function_100003ed0(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003edc(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x4013333300000001; // 0x100003ee8

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003df8 - 0x100003e1c
int64_t function_100003df8(int64_t * a1) {
    // 0x100003df8
    int64_t v1; // 0x100003df8
    return (int64_t)_memcpy((int64_t *)v1, &g1, 120);
}

// Address range: 0x100003e1c - 0x100003ec4
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003e30
    int32_t v2; // bp-144, 0x100003e1c
    function_100003df8((int64_t *)&v2);
    int64_t v3; // 0x100003e1c
    int128_t v4; // 0x100003e1c
    int32_t v5 = _printf("Values from a function returning a structure : { %d, %f, %c, %s, %f}\n", v3, (float64_t)(int64_t)v4, (char)v3, (char *)v3, (float64_t)(int64_t)v4); // 0x100003e8c
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003eb0
        ___stack_chk_fail((int64_t)v5);
    }
    // 0x100003eb4
    return 0;
}

// Address range: 0x100003ec4 - 0x100003ed0
int64_t function_100003ec4(int64_t a1) {
    // 0x100003ec4
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003ed0 - 0x100003edc
int64_t * function_100003ed0(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003ed0
    return _memcpy(dest, src, n);
}

// Address range: 0x100003edc - 0x100003ee8
int32_t function_100003edc(char * format, ...) {
    // 0x100003edc
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

