//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003bb8(void);
int64_t function_100003e70(int64_t a1);
int32_t function_100003e7c(char * format, ...);
int32_t function_100003e88(void);
int32_t function_100003e94(char * format, ...);

// --------------------- Global Variables ---------------------

float64_t g1 = 2147483648.0; // 0x100003ea0

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _printf(char * a1, ...);
int32_t _rand(void);
int32_t _scanf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003bb8 - 0x100003c68
int64_t function_100003bb8(void) {
    // 0x100003bb8
    int64_t v1; // 0x100003bb8
    int32_t v2 = v1; // 0x100003bc8
    int32_t v3 = _rand(); // 0x100003bcc
    int32_t v4 = v2 - 1; // 0x100003bf4
    int32_t v5 = 1 - v2; // 0x100003bf8
    if (v5 < 0 == (v5 & v4) < 0) {
        // 0x100003c58
        return 0;
    }
    float64_t v6 = (float64_t)v3 / g1; // 0x100003c20
    int32_t v7 = 0;
    v6 -= *(float64_t *)(8 * (int64_t)v7 + v1);
    if (v6 != 0.0) {
        // 0x100003c38
        if (v6 > 0.0 != (v6 >= 0.0 == v6 <= 0.0)) {
            // break -> 0x100003c58
            break;
        }
    }
    int32_t v8 = v7 + 1; // 0x100003c4c
    int32_t v9 = v8 - v4; // 0x100003bf8
    int32_t result = v8; // 0x100003c08
    while (v9 < 0 != ((v9 ^ v8) & (v8 ^ v4)) < 0) {
        // 0x100003c10
        v7 = v8;
        v6 -= *(float64_t *)(8 * (int64_t)v7 + v1);
        if (v6 != 0.0) {
            // 0x100003c38
            result = v7;
            if (v6 > 0.0 != (v6 >= 0.0 == v6 <= 0.0)) {
                // break -> 0x100003c58
                break;
            }
        }
        // 0x100003c48
        v8 = v7 + 1;
        v9 = v8 - v4;
        result = v8;
    }
    // 0x100003c58
    return result;
}

// Address range: 0x100003c68 - 0x100003e70
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003c7c
    int32_t v2 = 0; // bp-40, 0x100003c88
    int64_t v3; // 0x100003c68
    while (true) {
        function_100003bb8();
        _printf("\nYour choice [1-3]:\n  1. Rock\n  2. Paper\n  3. Scissors\n> ");
        // 0x100003cdc
        while (_scanf("%d", (int64_t *)3) == 0) {
            // 0x100003d20
            _scanf("%1s", (char **)3);
            int32_t v4; // 0x100003c68
            if (v4 % 256 == 113) {
                // break (via goto) -> 0x100003d4c
                goto lab_0x100003d4c;
            }
            function_100003bb8();
            _printf("\nYour choice [1-3]:\n  1. Rock\n  2. Paper\n  3. Scissors\n> ");
        }
        // 0x100003db8
        int32_t v5; // 0x100003c68
        int32_t v6 = v5 - 1; // 0x100003dbc
        int32_t v7 = v5 - 3; // 0x100003dc8
        if (v6 < 0 || v7 != 0 == v7 < 0 == (v6 & 2 - v5) < 0) {
            // 0x100003dec
            _printf("invalid choice; again\n");
        } else {
            // 0x100003dfc
            _printf("You chose %s; I chose %s. %s\n", (char *)3, (char *)v3, (char *)v3);
            int32_t * v8 = (int32_t *)(4 * (int64_t)v6 + (int64_t)&v2); // 0x100003e60
            *v8 = *v8 + 1;
        }
        // 0x100003cdc
        v5 = v6;
    }
  lab_0x100003d4c:;
    int32_t v9 = _printf("Your choices [rock : %d , paper :  %d , scissors %d] ", 3, v3, v3); // 0x100003d7c
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003da0
        ___stack_chk_fail((int64_t)v9);
    }
    // 0x100003da4
    return 0;
}

// Address range: 0x100003e70 - 0x100003e7c
int64_t function_100003e70(int64_t a1) {
    // 0x100003e70
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003e7c - 0x100003e88
int32_t function_100003e7c(char * format, ...) {
    // 0x100003e7c
    return _printf(format);
}

// Address range: 0x100003e88 - 0x100003e94
int32_t function_100003e88(void) {
    // 0x100003e88
    return _rand();
}

// Address range: 0x100003e94 - 0x100003ea0
int32_t function_100003e94(char * format, ...) {
    // 0x100003e94
    return _scanf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

