//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003848(void);
int64_t function_1000038b8(void);
int64_t function_100003948(void);
int64_t function_100003980(void);
int64_t function_1000039b0(int32_t a1, int32_t a2, int64_t a3);
int64_t function_100003a0c(int64_t * a1);
int64_t function_100003ce0(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003d14(void);
int64_t function_100003d3c(int64_t a1, int64_t a2);
int64_t function_100003e04(int32_t a1, int32_t a2);
int64_t function_100003e54(void);
int64_t function_100003f34(int64_t a1);
int32_t function_100003f40(int32_t c, struct _IO_FILE * stream);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _fputc(int32_t a1, struct _IO_FILE * a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003848 - 0x1000038b8
int64_t function_100003848(void) {
    // 0x100003848
    int64_t v1; // 0x100003848
    int32_t * v2 = (int32_t *)(v1 + 24); // 0x100003864
    int32_t v3 = *v2; // 0x100003864
    unsigned char v4 = *(char *)(*(int64_t *)(v1 + 16) + (int64_t)v3); // 0x100003868
    int64_t result = 0xffffffff; // 0x10000387c
    if (v4 != 0) {
        // 0x100003890
        *v2 = v3 + 1;
        result = v4;
    }
    // 0x1000038ac
    return result;
}

// Address range: 0x1000038b8 - 0x100003948
int64_t function_1000038b8(void) {
    // 0x1000038b8
    int64_t v1; // 0x1000038b8
    int64_t v2 = v1;
    char v3 = (int32_t)v2 == -1 ? 0 : (char)v2;
    int32_t * v4 = (int32_t *)(v1 + 24); // 0x100003908
    int32_t v5 = *v4; // 0x100003908
    *v4 = v5 + 1;
    *(char *)(*(int64_t *)(v1 + 16) + (int64_t)v5) = v3;
    if ((int32_t)v2 == -1) {
        // 0x100003930
        *v4 = 0;
    }
    // 0x10000393c
    return 0;
}

// Address range: 0x100003948 - 0x100003980
int64_t function_100003948(void) {
    // 0x100003948
    int64_t v1; // 0x100003948
    int64_t v2 = *(int64_t *)(v1 + 16); // 0x10000396c
    return _fputc((int32_t)v1, (struct _IO_FILE *)v2);
}

// Address range: 0x100003980 - 0x1000039b0
int64_t function_100003980(void) {
    // 0x100003980
    int64_t result; // 0x100003980
    return result;
}

// Address range: 0x1000039b0 - 0x100003a0c
int64_t function_1000039b0(int32_t a1, int32_t a2, int64_t a3) {
    int32_t v1 = -a2; // 0x1000039c0
    int64_t result; // 0x1000039b0
    if (v1 < 0 == (v1 & a2) < 0) {
        // 0x100003a00
        return result;
    }
    // 0x1000039d0
    return *(int64_t *)(result - 8);
}

// Address range: 0x100003a0c - 0x100003ce0
int64_t function_100003a0c(int64_t * a1) {
    // 0x100003a0c
    int64_t result; // 0x100003a0c
    return result;
}

// Address range: 0x100003ce0 - 0x100003d14
int64_t function_100003ce0(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003ce0
    int64_t v1; // 0x100003ce0
    int64_t result; // 0x100003ce0
    if (*(int64_t *)*(int64_t *)0x100004008 != *(int64_t *)(v1 - 24)) {
        // 0x100003d00
        result = ___stack_chk_fail(v1);
    }
    // 0x100003d04
    return result;
}

// Address range: 0x100003d14 - 0x100003d3c
int64_t function_100003d14(void) {
    // 0x100003d14
    int64_t result; // 0x100003d14
    return result;
}

// Address range: 0x100003d3c - 0x100003e04
int64_t function_100003d3c(int64_t a1, int64_t a2) {
    // 0x100003d3c
    int64_t result; // 0x100003d3c
    int32_t v1 = result; // 0x100003d3c
    *(int32_t *)(result - 20) = v1;
    if (v1 == -1) {
        // 0x100003d54
        return result;
    }
    int32_t v2 = v1 - 128; // 0x100003d64
    if (v2 == 0 || v2 < 0 != (127 - v1 & v1) < 0) {
        // 0x100003dec
        return *(int64_t *)(result - 8);
    }
    int32_t v3 = 128 - v1; // 0x100003d90
    if (v3 < 0 == (v2 & v3) < 0) {
        // 0x100003de8
        return function_100003e54();
    }
    // 0x100003da0
    return *(int64_t *)(result - 8);
}

// Address range: 0x100003e04 - 0x100003e54
int64_t function_100003e04(int32_t a1, int32_t a2) {
    // 0x100003e04
    int64_t v1; // 0x100003e04
    *(int32_t *)(v1 - 20) = (int32_t)v1;
    int32_t v2 = -a1; // 0x100003e18
    if (v2 < 0 == (v2 & a1) < 0) {
        // 0x100003e50
        return function_100003e54();
    }
    // 0x100003e28
    return *(int64_t *)(v1 - 16);
}

// Address range: 0x100003e54 - 0x100003e58
int64_t function_100003e54(void) {
    // 0x100003e54
    int64_t result; // 0x100003e54
    return result;
}

// Address range: 0x100003e58 - 0x100003f34
int64_t entry_point(void) {
    int64_t v1 = 0x100003848; // bp-368, 0x100003ea8
    function_100003a0c(&v1);
    int64_t v2 = function_100003d14(); // 0x100003ef8
    int64_t v3 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003f08
    if (v3 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003f1c
        ___stack_chk_fail(v2);
    }
    // 0x100003f20
    return 0;
}

// Address range: 0x100003f34 - 0x100003f40
int64_t function_100003f34(int64_t a1) {
    // 0x100003f34
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f40 - 0x100003f4c
int32_t function_100003f40(int32_t c, struct _IO_FILE * stream) {
    // 0x100003f40
    return _fputc(c, stream);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 14

