//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003e04(void);
int32_t function_100003f88(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003e04 - 0x100003ebc
int64_t function_100003e04(void) {
    // 0x100003e04
    int64_t v1; // 0x100003e04
    int32_t v2 = v1; // 0x100003e08
    int32_t result = v2 * (int32_t)v1; // 0x100003e1c
    int32_t v3 = -v2; // 0x100003e30
    if (v3 < 0 == (v3 & v2) < 0) {
        // 0x100003eb0
        return result;
    }
    int32_t v4 = v2 - 1; // 0x100003e48
    int32_t v5 = 0; // 0x100003e98
    int32_t v6 = result; // 0x100003e88
    while (v6 % v4 == 0) {
        // 0x100003e70
        v6 = v6 + 1 + v6 / v4;
        v5++;
        int32_t v7 = v5 - v2; // 0x100003e30
        int32_t result2 = v6; // 0x100003e38
        if (v7 < 0 == ((v7 ^ v5) & (v5 ^ v2)) < 0) {
            // 0x100003eb0
            return result2;
        }
    }
    // 0x100003eb0
    return 0;
}

// Address range: 0x100003ebc - 0x100003f88
int64_t entry_point(void) {
    for (int32_t i = 2; i < 10; i++) {
        uint32_t v1 = 1;
        int32_t v2 = v1 + 1; // 0x100003f14
        while ((int32_t)function_100003e04() == 0) {
            // 0x100003efc
            v1 = v2;
            v2 = v1 + 1;
        }
        // 0x100003f30
        int64_t v3; // 0x100003ebc
        _printf("%d: %d\t%d\n", (int64_t)v1, v3, v3);
    }
    // 0x100003f78
    return 0;
}

// Address range: 0x100003f88 - 0x100003f94
int32_t function_100003f88(char * format, ...) {
    // 0x100003f88
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 3

