//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003cf0(void);
int64_t function_100003f58(int64_t a1);
int32_t function_100003f64(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003cf0 - 0x100003db0
int64_t function_100003cf0(void) {
    // 0x100003cf0
    int64_t v1; // 0x100003cf0
    int32_t v2 = v1; // 0x100003cf4
    int32_t v3 = 1 - v2; // 0x100003d18
    if (v3 != 0 && v3 < 0 == (v3 & v2) < 0) {
        // 0x100003da4
        return 0;
    }
    int32_t v4 = 0;
    int32_t v5 = 1;
    int32_t v6 = v4; // 0x100003d44
    int32_t v7; // 0x100003cf0
    if (v2 % v5 == 0) {
        // 0x100003d4c
        v7 = v5 == v2 / v5 ? 1 : 2;
        v6 = v7 + v4;
    }
    int32_t result = v6;
    int32_t v8 = v5 + 1; // 0x100003d98
    int32_t v9 = v8 * v8; // 0x100003d10
    int32_t v10 = v9 - v2; // 0x100003d18
    while (v10 == 0 || v10 < 0 != ((v10 ^ v9) & (v9 ^ v2)) < 0) {
        // 0x100003d28
        v4 = result;
        v5 = v8;
        v6 = v4;
        if (v2 % v5 == 0) {
            // 0x100003d4c
            v7 = v5 == v2 / v5 ? 1 : 2;
            v6 = v7 + v4;
        }
        // 0x100003d94
        result = v6;
        v8 = v5 + 1;
        v9 = v8 * v8;
        v10 = v9 - v2;
    }
    // 0x100003da4
    return result;
}

// Address range: 0x100003db0 - 0x100003f58
int64_t entry_point(void) {
    int64_t v1 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003dc4
    int64_t v2; // bp-84, 0x100003db0
    int64_t v3 = &v2;
    for (int64_t i = 0; i < 15; i++) {
        // 0x100003dec
        *(int32_t *)(4 * i + v3) = 0;
    }
    // 0x100003e10
    int64_t v4; // 0x100003db0
    _printf("The first %d terms of the sequence are:\n", v4);
    int32_t v5 = 1;
    int32_t v6 = 0;
    int64_t v7 = function_100003cf0(); // 0x100003e50
    int32_t v8 = v7; // 0x100003e54
    int32_t v9 = v8 - 15; // 0x100003e5c
    int32_t v10 = v6; // 0x100003e64
    int32_t * v11; // 0x100003e78
    if (v9 == 0 || v9 < 0 != (14 - v8 & v8) < 0) {
        // 0x100003e6c
        v11 = (int32_t *)((4 * v7 + 0xfffffffc & 0xfffffffc) + v3);
        v10 = v6;
        if (*v11 == 0) {
            // 0x100003e8c
            *v11 = v5;
            v10 = v6 + 1;
        }
    }
    int32_t v12 = v5 + 1; // 0x100003e44
    int32_t v13 = 0; // 0x100003e44
    while (v10 < 15 != (14 - v10 & v10) < 0) {
        // 0x100003e4c
        v5 = v12;
        v6 = v10;
        v7 = function_100003cf0();
        v8 = v7;
        v9 = v8 - 15;
        v10 = v6;
        if (v9 == 0 || v9 < 0 != (14 - v8 & v8) < 0) {
            // 0x100003e6c
            v11 = (int32_t *)((4 * v7 + 0xfffffffc & 0xfffffffc) + v3);
            v10 = v6;
            if (*v11 == 0) {
                // 0x100003e8c
                *v11 = v5;
                v10 = v6 + 1;
            }
        }
        // 0x100003eb4
        v12 = v5 + 1;
        v13 = 0;
    }
    _printf("%d ", v4);
    int32_t v14 = v13 + 1; // 0x100003f0c
    v13 = v14;
    while (v14 != 15) {
        // 0x100003ee0
        _printf("%d ", v4);
        v14 = v13 + 1;
        v13 = v14;
    }
    int32_t v15 = _printf((char *)0x100003f9d); // 0x100003f20
    if (*(int64_t *)*(int64_t *)0x100004008 != v1) {
        // 0x100003f44
        ___stack_chk_fail((int64_t)v15);
    }
    // 0x100003f48
    return 0;
}

// Address range: 0x100003f58 - 0x100003f64
int64_t function_100003f58(int64_t a1) {
    // 0x100003f58
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f64 - 0x100003f70
int32_t function_100003f64(char * format, ...) {
    // 0x100003f64
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

