//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003bd4(int64_t a1, int64_t a2);
int64_t function_100003e28(void);
int64_t function_100003f30(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_100003f3c(int64_t a1);
void function_100003f48(int64_t * ptr);
int64_t * function_100003f54(int32_t size);
int64_t * function_100003f60(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003f6c(char * format, ...);
int32_t function_100003f78(char * s1, char * s2);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x10000000003f84; // 0x100004040
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___memcpy_chk(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t ___stack_chk_fail(int64_t a1);
void _free(int64_t * a1);
int64_t * _malloc(int32_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);
int32_t _strcmp(char * a1, char * a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003bd4 - 0x100003e28
int64_t function_100003bd4(int64_t a1, int64_t a2) {
    // 0x100003bd4
    int64_t v1; // 0x100003bd4
    int64_t * v2 = _malloc((int32_t)v1); // 0x100003bf4
    int64_t v3 = (0x100000000 * v1 - 0x100000000 >> 32) * v1; // 0x100003c18
    uint64_t v4 = v3 + v1; // 0x100003c1c
    if (v3 != 0 && v4 >= v1) {
        // 0x100003c40
        return v4 - v1;
    }
    int64_t v5 = (int64_t)v2; // 0x100003bf4
    if (v4 >= v1 != v3 != 0) {
        // 0x100003e14
        _free(v2);
        return &g2;
    }
    int64_t v6; // 0x100003bd4
    uint64_t result = v6;
    while (v4 == result || v4 < result) {
        // 0x100003d18
        ___memcpy_chk(v5, v4, v1, -1);
        ___memcpy_chk(v4, result, v1, -1);
        ___memcpy_chk(result, v5, v1, -1);
        int64_t v7 = result + v1;
        int64_t v8 = v7; // 0x100003da0
        int64_t v9 = v7; // 0x100003da0
        if (v7 < v4) {
            ___memcpy_chk(v5, v4, v1, -1);
            ___memcpy_chk(v4, v9, v1, -1);
            ___memcpy_chk(v9, v5, v1, -1);
            int64_t v10 = v4 - v1; // 0x100003e04
            int64_t v11 = v9 + v1;
            v8 = v11;
            v9 = v11;
            int64_t v12 = v10; // 0x100003da0
            while (v11 < v10) {
                // 0x100003da8
                ___memcpy_chk(v5, v12, v1, -1);
                ___memcpy_chk(v12, v9, v1, -1);
                ___memcpy_chk(v9, v5, v1, -1);
                v10 = v12 - v1;
                v11 = v9 + v1;
                v8 = v11;
                v9 = v11;
                v12 = v10;
            }
        }
        // 0x100003c00
        result = v8;
    }
    // 0x100003cdc
    return result;
}

// Address range: 0x100003e28 - 0x100003e5c
int64_t function_100003e28(void) {
    // 0x100003e28
    int64_t v1; // 0x100003e28
    return _strcmp((char *)v1, (char *)v1);
}

// Address range: 0x100003e5c - 0x100003f30
int64_t entry_point(void) {
    // 0x100003e5c
    int64_t v1; // bp-64, 0x100003e5c
    _memcpy(&v1, &g1, 40);
    function_100003bd4((int64_t)&g2, (int64_t)&g2);
    int32_t v2; // 0x100003ee4
    for (int32_t i = 0; i < 5; i++) {
        // 0x100003ec8
        v2 = _printf("%s\n", (char *)5);
    }
    int64_t v3 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003f08
    if (v3 != *(int64_t *)*(int64_t *)0x100004010) {
        // 0x100003f1c
        ___stack_chk_fail((int64_t)v2);
    }
    // 0x100003f20
    return 0;
}

// Address range: 0x100003f30 - 0x100003f3c
int64_t function_100003f30(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x100003f30
    return ___memcpy_chk(a1, a2, a3, a4);
}

// Address range: 0x100003f3c - 0x100003f48
int64_t function_100003f3c(int64_t a1) {
    // 0x100003f3c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f48 - 0x100003f54
void function_100003f48(int64_t * ptr) {
    // 0x100003f48
    _free(ptr);
}

// Address range: 0x100003f54 - 0x100003f60
int64_t * function_100003f54(int32_t size) {
    // 0x100003f54
    return _malloc(size);
}

// Address range: 0x100003f60 - 0x100003f6c
int64_t * function_100003f60(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003f60
    return _memcpy(dest, src, n);
}

// Address range: 0x100003f6c - 0x100003f78
int32_t function_100003f6c(char * format, ...) {
    // 0x100003f6c
    return _printf(format);
}

// Address range: 0x100003f78 - 0x100003f84
int32_t function_100003f78(char * s1, char * s2) {
    // 0x100003f78
    return _strcmp(s1, s2);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

