//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003b58(void);
int64_t function_100003f54(int64_t a1);
int64_t * function_100003f60(int32_t nmemb, int32_t size);
void function_100003f6c(int64_t * ptr);
int32_t function_100003f78(char * format, ...);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int64_t * _calloc(int32_t a1, int32_t a2);
void _free(int64_t * a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003b58 - 0x100003e7c
int64_t function_100003b58(void) {
    // 0x100003b58
    int64_t v1; // 0x100003b58
    int32_t v2 = v1; // 0x100003b68
    int32_t v3 = v1;
    int32_t v4 = 1 - v2; // 0x100003b8c
    int32_t v5 = 1; // 0x100003b94
    int32_t v6 = v3; // 0x100003b94
    if (v4 < 0 != (v4 & v2) < 0) {
        int32_t v7 = v3;
        int32_t v8 = *(int32_t *)(4 * (int64_t)v5 + v1); // 0x100003ba4
        int32_t v9 = v8 - v7; // 0x100003bac
        int32_t v10 = v9 == 0 | v9 < 0 != ((v9 ^ v8) & (v8 ^ v7)) < 0 ? v7 : v8;
        v5++;
        int32_t v11 = v5 - v2; // 0x100003b8c
        v6 = v10;
        while (v11 < 0 != ((v11 ^ v5) & (v5 ^ v2)) < 0) {
            // 0x100003b9c
            v7 = v10;
            v8 = *(int32_t *)(4 * (int64_t)v5 + v1);
            v9 = v8 - v7;
            v10 = v9 == 0 | v9 < 0 != ((v9 ^ v8) & (v8 ^ v7)) < 0 ? v7 : v8;
            v5++;
            v11 = v5 - v2;
            v6 = v10;
        }
    }
    int64_t * v12 = _calloc(1, v6 * v2); // 0x100003bfc
    int64_t v13 = (int64_t)v12; // 0x100003bfc
    int32_t v14 = -v2;
    if (v14 < 0 != (v14 & v2) < 0) {
        int32_t v15 = 0;
        int32_t * v16 = (int32_t *)(4 * (int64_t)v15 + v1); // 0x100003c38
        int32_t v17 = *v16; // 0x100003c38
        int32_t v18 = -v17; // 0x100003c3c
        int32_t v19; // 0x100003c58
        int32_t v20; // 0x100003c78
        int32_t v21; // 0x100003c38
        if (v18 < 0 != (v17 & v18) < 0) {
            // 0x100003c4c
            v19 = v15 * v6;
            v20 = 0;
            *(char *)((int64_t)(v20 + v19) + v13) = 1;
            v20++;
            v21 = *v16;
            while (v20 - v21 < 0 != ((v20 - v21 ^ v20) & (v21 ^ v20)) < 0) {
                // 0x100003c4c
                *(char *)((int64_t)(v20 + v19) + v13) = 1;
                v20++;
                v21 = *v16;
            }
        }
        int32_t v22 = v15 + 1; // 0x100003c8c
        while (v22 - v2 < 0 != ((v22 - v2 ^ v22) & (v22 ^ v2)) < 0) {
            // 0x100003c2c
            v15 = v22;
            v16 = (int32_t *)(4 * (int64_t)v15 + v1);
            v17 = *v16;
            v18 = -v17;
            if (v18 < 0 != (v17 & v18) < 0) {
                // 0x100003c4c
                v19 = v15 * v6;
                v20 = 0;
                *(char *)((int64_t)(v20 + v19) + v13) = 1;
                v20++;
                v21 = *v16;
                while (v20 - v21 < 0 != ((v20 - v21 ^ v20) & (v21 ^ v20)) < 0) {
                    // 0x100003c4c
                    *(char *)((int64_t)(v20 + v19) + v13) = 1;
                    v20++;
                    v21 = *v16;
                }
            }
            // 0x100003c88
            v22 = v15 + 1;
        }
    }
    int32_t v23 = -v6;
    if (v23 < 0 != (v6 & v23) < 0) {
        int32_t v24 = 0;
        int32_t v25 = 0; // 0x100003cd4
        int32_t v26 = 0; // 0x100003cd4
        int32_t v27; // 0x100003b58
        int32_t v28; // 0x100003cf0
        unsigned char v29; // 0x100003cf4
        int32_t v30; // 0x100003cfc
        int32_t v31; // 0x100003d2c
        int32_t v32; // 0x100003ccc
        if (v14 < 0 != (v14 & v2) < 0) {
            v28 = v25 * v6 + v24;
            v30 = (int32_t)*(char *)((int64_t)v28 + v13);
            *(char *)((int64_t)v28 + v13) = 0;
            v31 = v25 + 1;
            v32 = v31 - v2;
            v27 = v30;
            v25 = v31;
            v26 = v30;
            while (v32 < 0 != ((v32 ^ v31) & (v31 ^ v2)) < 0) {
                // 0x100003cdc
                v28 = v25 * v6 + v24;
                v29 = *(char *)((int64_t)v28 + v13);
                v30 = v27 + (int32_t)v29;
                *(char *)((int64_t)v28 + v13) = 0;
                v31 = v25 + 1;
                v32 = v31 - v2;
                v27 = v30;
                v25 = v31;
                v26 = v30;
            }
        }
        int32_t v33 = v2 - v26; // 0x100003d40
        int32_t v34 = -v26; // 0x100003d54
        int32_t v35 = v33; // 0x100003d5c
        int32_t v36; // 0x100003d90
        int32_t v37; // 0x100003d54
        if (v34 < 0 != ((v33 ^ v34) & (v33 ^ v2)) < 0) {
            *(char *)((int64_t)(v35 * v6 + v24) + v13) = 1;
            v36 = v35 + 1;
            v37 = v36 - v2;
            v35 = v36;
            while (v37 < 0 != ((v37 ^ v36) & (v36 ^ v2)) < 0) {
                // 0x100003d64
                *(char *)((int64_t)(v35 * v6 + v24) + v13) = 1;
                v36 = v35 + 1;
                v37 = v36 - v2;
                v35 = v36;
            }
        }
        int32_t v38 = v24 + 1; // 0x100003da4
        while (v38 - v6 < 0 != ((v38 - v6 ^ v38) & (v38 ^ v6)) < 0) {
            // 0x100003cc4
            v24 = v38;
            v25 = 0;
            v26 = 0;
            if (v14 < 0 != (v14 & v2) < 0) {
                v28 = v25 * v6 + v24;
                v30 = (int32_t)*(char *)((int64_t)v28 + v13);
                *(char *)((int64_t)v28 + v13) = 0;
                v31 = v25 + 1;
                v32 = v31 - v2;
                v27 = v30;
                v25 = v31;
                v26 = v30;
                while (v32 < 0 != ((v32 ^ v31) & (v31 ^ v2)) < 0) {
                    // 0x100003cdc
                    v28 = v25 * v6 + v24;
                    v29 = *(char *)((int64_t)v28 + v13);
                    v30 = v27 + (int32_t)v29;
                    *(char *)((int64_t)v28 + v13) = 0;
                    v31 = v25 + 1;
                    v32 = v31 - v2;
                    v27 = v30;
                    v25 = v31;
                    v26 = v30;
                }
            }
            // 0x100003d38
            v33 = v2 - v26;
            v34 = -v26;
            v35 = v33;
            if (v34 < 0 != ((v33 ^ v34) & (v33 ^ v2)) < 0) {
                *(char *)((int64_t)(v35 * v6 + v24) + v13) = 1;
                v36 = v35 + 1;
                v37 = v36 - v2;
                v35 = v36;
                while (v37 < 0 != ((v37 ^ v36) & (v36 ^ v2)) < 0) {
                    // 0x100003d64
                    *(char *)((int64_t)(v35 * v6 + v24) + v13) = 1;
                    v36 = v35 + 1;
                    v37 = v36 - v2;
                    v35 = v36;
                }
            }
            // 0x100003da0
            v38 = v24 + 1;
        }
    }
    int32_t v39 = 0; // 0x100003dc8
    if (v14 < 0 == (v14 & v2) < 0) {
        // 0x100003e68
        _free(v12);
        return &g1;
    }
    int32_t v40 = v39 * v6;
    int32_t v41 = 0; // 0x100003df0
    int32_t v42; // 0x100003b58
    int32_t v43; // 0x100003b58
    int32_t v44; // 0x100003e38
    int32_t v45; // 0x100003de0
    if (v23 < 0 != (v6 & v23) < 0) {
        v43 = 0;
        v41 = v43;
        while (*(char *)((int64_t)(v43 + v40) + v13) != 0) {
            // 0x100003e34
            v44 = v43 + 1;
            v45 = v44 - v6;
            v42 = v44;
            v41 = v44;
            if (v45 < 0 == ((v45 ^ v44) & (v44 ^ v6)) < 0) {
                // break -> 0x100003e44
                break;
            }
            v43 = v42;
            v41 = v43;
        }
    }
    // 0x100003e44
    *(int32_t *)(4 * (int64_t)v39 + v1) = v41;
    v39++;
    while (v39 - v2 < 0 != ((v39 - v2 ^ v39) & (v39 ^ v2)) < 0) {
        // 0x100003dd8
        v40 = v39 * v6;
        v41 = 0;
        if (v23 < 0 != (v6 & v23) < 0) {
            v43 = 0;
            v41 = v43;
            while (*(char *)((int64_t)(v43 + v40) + v13) != 0) {
                // 0x100003e34
                v44 = v43 + 1;
                v45 = v44 - v6;
                v42 = v44;
                v41 = v44;
                if (v45 < 0 == ((v45 ^ v44) & (v44 ^ v6)) < 0) {
                    // break -> 0x100003e44
                    break;
                }
                v43 = v42;
                v41 = v43;
            }
        }
        // 0x100003e44
        *(int32_t *)(4 * (int64_t)v39 + v1) = v41;
        v39++;
    }
    // 0x100003e68
    _free(v12);
    return &g1;
}

// Address range: 0x100003e7c - 0x100003f54
int64_t entry_point(void) {
    // 0x100003e7c
    function_100003b58();
    int32_t v1; // 0x100003f08
    for (int32_t i = 0; i < 8; i++) {
        // 0x100003ee8
        v1 = _printf("%d\n", 8);
    }
    int64_t v2 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003f2c
    if (v2 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003f40
        ___stack_chk_fail((int64_t)v1);
    }
    // 0x100003f44
    return 0;
}

// Address range: 0x100003f54 - 0x100003f60
int64_t function_100003f54(int64_t a1) {
    // 0x100003f54
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f60 - 0x100003f6c
int64_t * function_100003f60(int32_t nmemb, int32_t size) {
    // 0x100003f60
    return _calloc(nmemb, size);
}

// Address range: 0x100003f6c - 0x100003f78
void function_100003f6c(int64_t * ptr) {
    // 0x100003f6c
    _free(ptr);
}

// Address range: 0x100003f78 - 0x100003f84
int32_t function_100003f78(char * format, ...) {
    // 0x100003f78
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

