//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003708(void);
int64_t function_100003794(void);
int64_t function_10000381c(void);
int64_t function_1000038ac(void);
int64_t function_1000039a4(void);
int64_t function_100003ab4(void);
int64_t function_100003b14(void);
int32_t function_100003e54(char * format, ...);

// --------------------- Global Variables ---------------------

int64_t g1 = 0xe0000000a; // 0x1000080a0
int32_t g2 = -0x1120531; // 0x1000083c0
int32_t * g3 = (int32_t *)0x100000c; // 0x1000083c4
int32_t * g4 = NULL; // 0x100008414

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003708 - 0x100003794
int64_t function_100003708(void) {
    // 0x100003708
    int64_t v1; // 0x100003708
    *(int32_t *)((0x100000000 * v1 >> 30) + (int64_t)&g3) = (int32_t)v1;
    *(int32_t *)((0x100000000 * v1 >> 30) + (int64_t)&g3) = (int32_t)v1;
    int64_t result; // 0x100003708
    if (g2 != 0) {
        // 0x100003754
        result = _printf("%4s is engaged to %4s\n", (char *)v1, (char *)v1);
    }
    // 0x100003788
    return result;
}

// Address range: 0x100003794 - 0x10000381c
int64_t function_100003794(void) {
    // 0x100003794
    int64_t v1; // 0x100003794
    *(int32_t *)((0x100000000 * v1 >> 30) + (int64_t)&g3) = -1;
    *(int32_t *)((0x100000000 * v1 >> 30) + (int64_t)&g3) = -1;
    int64_t result; // 0x100003794
    if (g2 != 0) {
        // 0x1000037dc
        result = _printf("%4s dumps %4s\n", (char *)v1, (char *)v1);
    }
    // 0x100003810
    return result;
}

// Address range: 0x10000381c - 0x1000038ac
int64_t function_10000381c(void) {
    // 0x10000381c
    int64_t v1; // 0x10000381c
    int64_t v2 = 40 * (0x100000000 * v1 >> 32) + (int64_t)&g1;
    int32_t v3 = 0;
    int32_t result = v3; // 0x100003884
    while (*(int32_t *)(v2 + 4 * (int64_t)v3) != (int32_t)v1) {
        int32_t v4 = v3 + 1; // 0x100003894
        int32_t v5 = v3 - 8; // 0x100003834
        result = v4;
        if (v5 != 0 && v5 < 0 == (7 - v3 & v4) < 0) {
            // break -> 0x1000038a0
            break;
        }
        v3 = v4;
        result = v3;
    }
    // 0x1000038a0
    return result;
}

// Address range: 0x1000038ac - 0x1000039a4
int64_t function_1000038ac(void) {
    // 0x1000038ac
    int64_t v1; // 0x1000038ac
    if (g2 != 0) {
        // 0x1000038ec
        _printf("%4s proposes to %4s\n", (char *)v1, (char *)v1);
    }
    if (*(int32_t *)((0x100000000 * v1 >> 30) + (int64_t)&g3) == -1) {
        // 0x100003998
        return function_100003708();
    }
    int64_t v2 = function_10000381c(); // 0x10000394c
    int64_t v3 = function_10000381c(); // 0x10000395c
    int32_t v4 = v2; // 0x100003968
    int32_t v5 = v4 - (int32_t)v3; // 0x100003968
    int64_t result = v2 & 0xffffffff; // 0x100003970
    if (v5 < 0 != ((v5 ^ v4) & (int32_t)(v3 ^ v2)) < 0) {
        // 0x100003978
        function_100003794();
        result = function_100003708();
    }
    // 0x100003998
    return result;
}

// Address range: 0x1000039a4 - 0x100003ab4
int64_t function_1000039a4(void) {
    int64_t v1 = function_10000381c(); // 0x1000039c0
    int32_t v2 = v1; // 0x1000039c4
    int64_t v3 = function_10000381c(); // 0x1000039dc
    int32_t v4 = v2 - (int32_t)v3; // 0x1000039e8
    if (v4 < 0 == ((v4 ^ v2) & (int32_t)(v3 ^ v1)) < 0) {
        // 0x100003aa4
        return 0;
    }
    int64_t v5 = function_10000381c(); // 0x100003a00
    int32_t v6 = v5; // 0x100003a04
    int64_t v7; // 0x1000039a4
    uint32_t v8 = *(int32_t *)((0x100000000 * v7 >> 30) + (int64_t)&g3); // 0x100003a18
    int64_t v9 = function_10000381c(); // 0x100003a1c
    int32_t v10 = v6 - (int32_t)v9; // 0x100003a28
    int64_t result = 0; // 0x100003a30
    if (v10 < 0 != ((v10 ^ v6) & (int32_t)(v9 ^ v5)) < 0) {
        // 0x100003a38
        _printf("    %4s (w/ %4s) and %4s (w/ %4s) prefer each other over current pairing.\n", (char *)(int64_t)v8, (char *)v7, (char *)v7, (char *)v7);
        result = 1;
    }
    // 0x100003aa4
    return result;
}

// Address range: 0x100003ab4 - 0x100003b14
int64_t function_100003ab4(void) {
    int64_t v1 = function_1000039a4(); // 0x100003ae0
    return function_1000039a4() + v1 & 0xffffffff;
}

// Address range: 0x100003b14 - 0x100003bc4
int64_t function_100003b14(void) {
    int32_t v1 = 0;
    v1++;
    int32_t v2 = v1;
    int32_t result = (int32_t)function_100003ab4() == 0 ? 0 : 1;
    int32_t v3 = v2 + 1;
    int32_t v4 = v2 - 8; // 0x100003b54
    int32_t v5 = result; // 0x100003b5c
    while (v4 == 0 || v4 < 0 != (v3 & 7 - v2) < 0) {
        // 0x100003b64
        v2 = v3;
        result = (int32_t)function_100003ab4() == 0 ? v5 : 1;
        v3 = v2 + 1;
        v4 = v2 - 8;
        v5 = result;
    }
    while (v1 != 9) {
        // 0x100003b64
        v1++;
        v2 = v1;
        result = (int32_t)function_100003ab4() == 0 ? result : 1;
        v3 = v2 + 1;
        v4 = v2 - 8;
        v5 = result;
        while (v4 == 0 || v4 < 0 != (v3 & 7 - v2) < 0) {
            // 0x100003b64
            v2 = v3;
            result = (int32_t)function_100003ab4() == 0 ? v5 : 1;
            v3 = v2 + 1;
            v4 = v2 - 8;
            v5 = result;
        }
    }
    // 0x100003bb4
    return result;
}

// Address range: 0x100003bc4 - 0x100003e54
int64_t entry_point(void) {
    int32_t v1 = 0;
    int64_t v2 = 4 * (int64_t)v1; // 0x100003c00
    *(int32_t *)(v2 + (int64_t)&g4) = -1;
    *(int32_t *)(v2 + (int64_t)&g3) = -1;
    int32_t v3 = v1 + 1; // 0x100003c1c
    while (v1 == 18 || v1 < 18 != (17 - v1 & v3) < 0) {
        // 0x100003bf0
        v1 = v3;
        v2 = 4 * (int64_t)v1;
        *(int32_t *)(v2 + (int64_t)&g4) = -1;
        *(int32_t *)(v2 + (int64_t)&g3) = -1;
        v3 = v1 + 1;
    }
    int32_t v4 = 0;
    int64_t v5 = v4; // 0x100003c4c
    int64_t v6 = 4 * v5; // 0x100003c58
    int32_t v7 = 0; // 0x100003c64
    int64_t v8; // 0x100003bc4
    int64_t v9 = v8; // 0x100003c64
    int32_t v10; // 0x100003ca8
    uint32_t v11; // 0x100003cb0
    int32_t * v12; // 0x100003ca4
    if (*(int32_t *)(v6 + (int64_t)&g3) == -1) {
        // 0x100003c70
        v12 = (int32_t *)(v6 + (int64_t)&g4);
        v10 = *v12 + 1;
        *v12 = v10;
        v11 = *(int32_t *)(40 * v5 + (int64_t)&g1 + (int64_t)(4 * v10));
        function_1000038ac();
        v7 = 1;
        v9 = v11;
    }
    int64_t v13 = v9;
    int32_t v14 = v7;
    int32_t v15 = v4 + 1; // 0x100003cc0
    int32_t v16 = v4 - 8; // 0x100003c3c
    while (v16 == 0 || v16 < 0 != (7 - v4 & v15) < 0) {
        // 0x100003c4c
        v4 = v15;
        v5 = v4;
        v6 = 4 * v5;
        v7 = v14;
        v9 = v13;
        if (*(int32_t *)(v6 + (int64_t)&g3) == -1) {
            // 0x100003c70
            v12 = (int32_t *)(v6 + (int64_t)&g4);
            v10 = *v12 + 1;
            *v12 = v10;
            v11 = *(int32_t *)(40 * v5 + (int64_t)&g1 + (int64_t)(4 * v10));
            function_1000038ac();
            v7 = 1;
            v9 = v11;
        }
        // 0x100003cbc
        v13 = v9;
        v14 = v7;
        v15 = v4 + 1;
        v16 = v4 - 8;
    }
    // 0x100003cd0
    while (v14 != 0) {
        // 0x100003c2c
        v4 = 0;
        v5 = v4;
        v6 = 4 * v5;
        v7 = 0;
        v9 = v13;
        if (*(int32_t *)(v6 + (int64_t)&g3) == -1) {
            // 0x100003c70
            v12 = (int32_t *)(v6 + (int64_t)&g4);
            v10 = *v12 + 1;
            *v12 = v10;
            v11 = *(int32_t *)(40 * v5 + (int64_t)&g1 + (int64_t)(4 * v10));
            function_1000038ac();
            v7 = 1;
            v9 = v11;
        }
        // 0x100003cbc
        v13 = v9;
        v14 = v7;
        v15 = v4 + 1;
        v16 = v4 - 8;
        while (v16 == 0 || v16 < 0 != (7 - v4 & v15) < 0) {
            // 0x100003c4c
            v4 = v15;
            v5 = v4;
            v6 = 4 * v5;
            v7 = v14;
            v9 = v13;
            if (*(int32_t *)(v6 + (int64_t)&g3) == -1) {
                // 0x100003c70
                v12 = (int32_t *)(v6 + (int64_t)&g4);
                v10 = *v12 + 1;
                *v12 = v10;
                v11 = *(int32_t *)(40 * v5 + (int64_t)&g1 + (int64_t)(4 * v10));
                function_1000038ac();
                v7 = 1;
                v9 = v11;
            }
            // 0x100003cbc
            v13 = v9;
            v14 = v7;
            v15 = v4 + 1;
            v16 = v4 - 8;
        }
    }
    // 0x100003ce4
    _printf("Pairing:\n");
    int32_t v17 = 0;
    int64_t v18; // 0x100003bc4
    _printf("  %4s - %s\n", (char *)v13, (char *)v18);
    int32_t v19 = v17 + 1; // 0x100003d9c
    while (v17 == 8 || v17 < 8 != (7 - v17 & v19) < 0) {
        // 0x100003d0c
        v17 = v19;
        _printf("  %4s - %s\n", (char *)v13, (char *)v18);
        v19 = v17 + 1;
    }
    // 0x100003da8
    _printf((int32_t)function_100003b14() == 0 ? "Stable matchup\n" : "Marriages not stable\n");
    _printf("\nBut if Bob and Fred were to swap:\n");
    function_100003708();
    function_100003708();
    _printf((int32_t)function_100003b14() == 0 ? "Stable matchup\n" : "Marriages not stable\n");
    return 0;
}

// Address range: 0x100003e54 - 0x100003e60
int32_t function_100003e54(char * format, ...) {
    // 0x100003e54
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

