//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003df4(void);
int64_t function_100003e94(int32_t a1);
int64_t function_100003eb4(int32_t a1, int32_t a2);
int64_t function_100003ee4(int64_t a1, int64_t a2, int64_t a3);
int64_t function_100003f5c(int64_t a1);
int32_t function_100003f68(int64_t ** array, int32_t size);
void function_100003f74(int64_t ** array, int32_t size, int32_t fd);
int32_t function_100003f80(struct _IO_FILE * stream, char * format, ...);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _backtrace(int64_t ** a1, int32_t a2);
void _backtrace_symbols_fd(int64_t ** a1, int32_t a2, int32_t a3);
int32_t _fprintf(struct _IO_FILE * a1, char * a2, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003df4 - 0x100003e94
int64_t function_100003df4(void) {
    // 0x100003df4
    int64_t v1; // bp-1632, 0x100003df4
    int32_t v2 = _backtrace((int64_t **)&v1, 200); // 0x100003e20
    int64_t v3 = *(int64_t *)*(int64_t *)0x100004010; // 0x100003e30
    int64_t v4; // 0x100003df4
    _fprintf((struct _IO_FILE *)v3, "--- (depth %d) ---\n", v4);
    _backtrace_symbols_fd((int64_t **)&v1, v2, 2);
    int64_t v5 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003e6c
    int64_t result = &g1; // 0x100003e78
    if (v5 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003e80
        result = ___stack_chk_fail((int64_t)&g1);
    }
    // 0x100003e84
    return result;
}

// Address range: 0x100003e94 - 0x100003eb4
int64_t function_100003e94(int32_t a1) {
    // 0x100003e94
    return function_100003df4();
}

// Address range: 0x100003eb4 - 0x100003ee4
int64_t function_100003eb4(int32_t a1, int32_t a2) {
    // 0x100003eb4
    return function_100003e94(a2 * a1);
}

// Address range: 0x100003ee4 - 0x100003f24
int64_t function_100003ee4(int64_t a1, int64_t a2, int64_t a3) {
    int32_t v1 = a2; // 0x100003ef4
    return function_100003eb4(v1 + (int32_t)a1, (int32_t)a3 + v1);
}

// Address range: 0x100003f24 - 0x100003f5c
int64_t entry_point(void) {
    // 0x100003f24
    function_100003ee4(2, 3, 5);
    return 0;
}

// Address range: 0x100003f5c - 0x100003f68
int64_t function_100003f5c(int64_t a1) {
    // 0x100003f5c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f68 - 0x100003f74
int32_t function_100003f68(int64_t ** array, int32_t size) {
    // 0x100003f68
    return _backtrace(array, size);
}

// Address range: 0x100003f74 - 0x100003f80
void function_100003f74(int64_t ** array, int32_t size, int32_t fd) {
    // 0x100003f74
    _backtrace_symbols_fd(array, size, fd);
}

// Address range: 0x100003f80 - 0x100003f8c
int32_t function_100003f80(struct _IO_FILE * stream, char * format, ...) {
    // 0x100003f80
    return _fprintf(stream, format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 9

