//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f58(int64_t a1);
int32_t function_100003f64(int16_t * pwcs, char * s, int32_t n);
int32_t function_100003f70(char * format, ...);
char * function_100003f7c(int32_t category, char * locale);

// --------------------- Global Variables ---------------------

char * g1; // 0x100003f88

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int32_t _mbstowcs(int16_t * a1, char * a2, int32_t a3);
int32_t _printf(char * a1, ...);
char * _setlocale(int32_t a1, char * a2);

// ------------------------ Functions -------------------------

// Address range: 0x100003ea0 - 0x100003f58
int64_t entry_point(void) {
    // 0x100003ea0
    _setlocale(2, (char *)&g1);
    int64_t v1 = 0x6573b8c3b8c36d; // bp-32, 0x100003ee4
    _printf("bytes: %d\n", (int64_t)&g1);
    _mbstowcs(NULL, (char *)&v1, 0);
    int32_t v2 = _printf("chars: %d\n", (int64_t)&v1); // 0x100003f20
    int64_t v3 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003f30
    if (v3 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003f44
        ___stack_chk_fail((int64_t)v2);
    }
    // 0x100003f48
    return 0;
}

// Address range: 0x100003f58 - 0x100003f64
int64_t function_100003f58(int64_t a1) {
    // 0x100003f58
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f64 - 0x100003f70
int32_t function_100003f64(int16_t * pwcs, char * s, int32_t n) {
    // 0x100003f64
    return _mbstowcs(pwcs, s, n);
}

// Address range: 0x100003f70 - 0x100003f7c
int32_t function_100003f70(char * format, ...) {
    // 0x100003f70
    return _printf(format);
}

// Address range: 0x100003f7c - 0x100003f88
char * function_100003f7c(int32_t category, char * locale) {
    // 0x100003f7c
    return _setlocale(category, locale);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

