//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003cd0(void);
int64_t function_100003d78(void);
int32_t function_100003f08(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003cd0 - 0x100003d78
int64_t function_100003cd0(void) {
    int32_t v1 = 0; // 0x100003ce4
    int32_t v2 = 0; // 0x100003ce4
    int64_t result = 0; // 0x100003cf8
    while ((v2 ^ v1) % 256 == 0) {
        // 0x100003d00
        int64_t v3; // 0x100003cd0
        v1 = (int32_t)*(char *)v3;
        int64_t v4; // 0x100003cd0
        char v5 = *(char *)v4; // 0x100003d20
        v2 = v5;
        v4++;
        v3++;
        if (v5 == 0) {
            // 0x100003d3c
            result = v1 % 256 != 0 ? 1 : 0xffffffff;
            return result;
        }
        result = 0;
    }
  lab_0x100003d6c:
    // 0x100003d6c
    return result;
}

// Address range: 0x100003d78 - 0x100003ea4
int64_t function_100003d78(void) {
    // 0x100003d78
    int64_t v1; // 0x100003d78
    _printf("matching `%s' with `%s':\n", (char *)v1, (char *)v1);
    int32_t v2 = 0; // 0x100003dcc
    int32_t v3 = 0; // 0x100003dcc
    if (*(char *)v1 == 0) {
        // 0x100003e7c
        _printf("end match\n\n");
        // 0x100003e94
        return 0;
    }
    int32_t v4; // 0x100003d78
    while (true) {
        // 0x100003dd4
        v4 = v2;
        int32_t v5 = v4; // 0x100003d78
        switch ((int32_t)v6) {
            case -1: {
                // 0x100003e10
                _printf("matched: pos %d (at end)\n\n", v1);
                // 0x100003e94
                return v4 + 1;
            }
            case 1: {
                // 0x100003e40
                _printf("matched: pos %d\n", v1);
                v5 = v4 + 1;
                // break -> 0x100003e6c
                break;
            }
        }
        // 0x100003e6c
        v2 = v5;
        v3++;
        int32_t result = v2; // 0x100003dcc
        if (*(char *)(v1 + (int64_t)v3) == 0) {
            // 0x100003e7c
            _printf("end match\n\n");
            // 0x100003e94
            return result;
        }
    }
    // 0x100003e10
    _printf("matched: pos %d (at end)\n\n", v1);
    // 0x100003e94
    return v4 + 1;
}

// Address range: 0x100003ea4 - 0x100003f08
int64_t entry_point(void) {
    // 0x100003ea4
    function_100003d78();
    function_100003d78();
    function_100003d78();
    return 0;
}

// Address range: 0x100003f08 - 0x100003f14
int32_t function_100003f08(char * format, ...) {
    // 0x100003f08
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

