//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003f40(int64_t a1, int64_t a2, int64_t a3, char * a4);
int64_t function_100003f4c(int64_t a1);
int64_t function_100003f58(int64_t * a1, int64_t a2, int64_t a3);
int32_t function_100003f64(char * format, ...);
int32_t function_100003f70(char * s);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___sprintf_chk(int64_t a1, int64_t a2, int64_t a3, char * a4);
int64_t ___stack_chk_fail(int64_t a1);
int64_t ___strcat_chk(int64_t * a1, int64_t a2, int64_t a3);
int32_t _printf(char * a1, ...);
int32_t _strlen(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003e04 - 0x100003f40
int64_t entry_point(void) {
    int64_t v1 = (float64_t)*(float128_t *)"Good Morning"; // bp-48, 0x100003e34
    int32_t v2 = _strlen((char *)&v1); // 0x100003e5c
    int32_t v3 = _strlen(" to all"); // 0x100003e68
    int64_t v4 = _strlen(" !!!"); // 0x100003e80
    uint64_t v5 = (int64_t)v3 + (int64_t)v2 + v4; // 0x100003e88
    int64_t v6 = v4; // 0x100003e98
    if (v5 != 24 && v5 <= 24) {
        // 0x100003ea0
        ___strcat_chk(&v1, (int64_t)" to all", 24);
        int32_t v7 = _strlen((char *)&v1); // 0x100003eb8
        ___sprintf_chk((int64_t)v7 + (int64_t)&v1, 0, -1, "%s");
        v6 = _printf("%s\n", NULL);
    }
    int64_t v8 = *(int64_t *)0x100004010; // 0x100003f14
    if (*(int64_t *)v8 != *(int64_t *)*(int64_t *)0x100004010) {
        // 0x100003f2c
        ___stack_chk_fail(v6);
    }
    // 0x100003f30
    return 0;
}

// Address range: 0x100003f40 - 0x100003f4c
int64_t function_100003f40(int64_t a1, int64_t a2, int64_t a3, char * a4) {
    // 0x100003f40
    return ___sprintf_chk(a1, a2, a3, a4);
}

// Address range: 0x100003f4c - 0x100003f58
int64_t function_100003f4c(int64_t a1) {
    // 0x100003f4c
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003f58 - 0x100003f64
int64_t function_100003f58(int64_t * a1, int64_t a2, int64_t a3) {
    // 0x100003f58
    return ___strcat_chk(a1, a2, a3);
}

// Address range: 0x100003f64 - 0x100003f70
int32_t function_100003f64(char * format, ...) {
    // 0x100003f64
    return _printf(format);
}

// Address range: 0x100003f70 - 0x100003f7c
int32_t function_100003f70(char * s) {
    // 0x100003f70
    return _strlen(s);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

