//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003c00(void);
int64_t function_100003c1c(void);
int64_t function_100003c64(void);
int64_t function_100003cac(void);
int64_t function_100003ccc(void);
int64_t function_100003d24(void);
int64_t function_100003d48(int64_t a1);
int32_t function_100003f3c(char * format, ...);
int32_t function_100003f48(char * s);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t _printf(char * a1, ...);
int32_t _puts(char * a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003c00 - 0x100003c1c
int64_t function_100003c00(void) {
    // 0x100003c00
    int64_t v1; // 0x100003c00
    return -v1 & 0xffffffff;
}

// Address range: 0x100003c1c - 0x100003c64
int64_t function_100003c1c(void) {
    // 0x100003c1c
    int64_t v1; // 0x100003c1c
    int64_t v2 = v1;
    int64_t v3 = v1;
    int32_t v4 = v3; // 0x100003c20
    int32_t v5 = v4 - (int32_t)v2; // 0x100003c30
    return (v5 < 0 == ((v5 ^ v4) & (int32_t)(v3 ^ v2)) < 0 ? v2 : v3) & 0xffffffff;
}

// Address range: 0x100003c64 - 0x100003cac
int64_t function_100003c64(void) {
    // 0x100003c64
    int64_t v1; // 0x100003c64
    int64_t v2 = v1;
    int64_t v3 = v1;
    int32_t v4 = v3; // 0x100003c68
    int32_t v5 = v4 - (int32_t)v2; // 0x100003c78
    int64_t v6 = v5 == 0 | v5 < 0 != ((v5 ^ v4) & (int32_t)(v3 ^ v2)) < 0 ? v2 : v3;
    return v6 & 0xffffffff;
}

// Address range: 0x100003cac - 0x100003ccc
int64_t function_100003cac(void) {
    // 0x100003cac
    int64_t v1; // 0x100003cac
    return v1 * v1 & 0xffffffff;
}

// Address range: 0x100003ccc - 0x100003d24
int64_t function_100003ccc(void) {
    // 0x100003ccc
    int64_t v1; // 0x100003ccc
    int32_t v2 = v1; // 0x100003cd4
    int32_t v3 = -(int32_t)v1; // 0x100003ce0
    int32_t v4 = v3 - v2; // 0x100003ce8
    return (v4 == 0 | v4 < 0 != ((v4 ^ v3) & (v3 ^ v2)) < 0 ? v1 : -v1) & 0xffffffff;
}

// Address range: 0x100003d24 - 0x100003d48
int64_t function_100003d24(void) {
    // 0x100003d24
    int64_t v1; // 0x100003d24
    char v2 = *(char *)((v1 + 1 & 0xffffffff) + (int64_t)"F?T"); // 0x100003d3c
    return (int64_t)v2 & 0xffffffff;
}

// Address range: 0x100003d48 - 0x100003e48
int64_t function_100003d48(int64_t a1) {
    // 0x100003d48
    int64_t v1; // 0x100003d48
    _printf("\n[%s]\n    F ? T\n  -------", (char *)v1);
    function_100003d24();
    _printf("\n%c |", (char)v1);
    return 0xffffffff;
}

// Address range: 0x100003e48 - 0x100003f3c
int64_t entry_point(void) {
    // 0x100003e48
    _puts("[Not]");
    int32_t v1 = -1;
    function_100003d24();
    function_100003c00();
    function_100003d24();
    int64_t v2; // 0x100003e48
    _printf("%c | %c\n", (char)v2, (char)v2);
    int32_t v3 = v1 + 1; // 0x100003ed0
    while (v1 == 0 || v1 < 0 != (v3 & -v1) < 0) {
        // 0x100003e84
        v1 = v3;
        function_100003d24();
        function_100003c00();
        function_100003d24();
        _printf("%c | %c\n", (char)v2, (char)v2);
        v3 = v1 + 1;
    }
    // 0x100003edc
    function_100003d48((int64_t)v3);
    function_100003d48((int64_t)&g1);
    function_100003d48((int64_t)&g1);
    function_100003d48((int64_t)&g1);
    return 0;
}

// Address range: 0x100003f3c - 0x100003f48
int32_t function_100003f3c(char * format, ...) {
    // 0x100003f3c
    return _printf(format);
}

// Address range: 0x100003f48 - 0x100003f54
int32_t function_100003f48(char * s) {
    // 0x100003f48
    return _puts(s);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 10

