//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003d24(int64_t a1);
int64_t * function_100003d30(int64_t * dest, int64_t * src, int32_t n);
int32_t function_100003d3c(char * format, ...);

// ------- Dynamically Linked Functions Without Header --------

int64_t ___stack_chk_fail(int64_t a1);
int64_t * _memcpy(int64_t * a1, int64_t * a2, int32_t a3);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003b98 - 0x100003d24
int64_t entry_point(void) {
    // 0x100003b98
    int64_t v1; // bp-152, 0x100003b98
    _memcpy(&v1, (int64_t *)"First", 120);
    int64_t v2; // bp-548, 0x100003b98
    _memcpy(&v2, (int64_t *)"Twelve drummers drumming", 396);
    int32_t v3; // 0x100003b98
    for (int32_t i = 0; i < 12; i++) {
        // 0x100003c48
        _printf("\n\nOn the %s day of Christmas\nMy true love gave to me:", "Twelve drummers drumming");
        int32_t v4 = i;
        if (i == 0) {
            // 0x100003c5c
            v3 = _printf("\nA partridge in a pear tree.");
        } else {
            // 0x100003c6c
            v3 = _printf("\n%s%c", "Twelve drummers drumming", -116);
        }
        int32_t v5 = v4 - 1; // 0x100003c40
        while (v4 >= 1) {
            // 0x100003c48
            v4 = v5;
            if (i == 0) {
                // 0x100003c5c
                v3 = _printf("\nA partridge in a pear tree.");
            } else {
                // 0x100003c6c
                v3 = _printf("\n%s%c", "Twelve drummers drumming", -116);
            }
            // 0x100003cc4
            v5 = v4 - 1;
        }
    }
    int64_t v6 = *(int64_t *)*(int64_t *)0x100004008; // 0x100003cf8
    if (v6 != *(int64_t *)*(int64_t *)0x100004008) {
        // 0x100003d0c
        ___stack_chk_fail((int64_t)v3);
    }
    // 0x100003d10
    return 0;
}

// Address range: 0x100003d24 - 0x100003d30
int64_t function_100003d24(int64_t a1) {
    // 0x100003d24
    return ___stack_chk_fail(a1);
}

// Address range: 0x100003d30 - 0x100003d3c
int64_t * function_100003d30(int64_t * dest, int64_t * src, int32_t n) {
    // 0x100003d30
    return _memcpy(dest, src, n);
}

// Address range: 0x100003d3c - 0x100003d48
int32_t function_100003d3c(char * format, ...) {
    // 0x100003d3c
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

