//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t * function_100003f5c(int32_t nmemb, int32_t size);
float64_t function_100003f68(float64_t a1);
int32_t function_100003f74(char * format, ...);

// --------------------- Global Variables ---------------------

float64_t g1 = 0.9385; // 0x100003f80

// ------- Dynamically Linked Functions Without Header --------

int64_t * _calloc(int32_t a1, int32_t a2);
float64_t _log(float64_t a1);
int32_t _printf(char * a1, ...);

// ------------------------ Functions -------------------------

// Address range: 0x100003c18 - 0x100003f5c
int64_t entry_point(void) {
    // 0x100003c18
    float64_t v1; // 0x100003c18
    float64_t v2 = v1;
    __asm_sshll(0.0f, 0);
    _log((float64_t)(int64_t)__asm_sshll(0.0f, 0));
    _log(_log((float64_t)(int64_t)__asm_sshll(0.0f, 0)));
    int32_t v3 = __asm_fcvtps(v2 * (2 * v2 - g1)); // 0x100003c98
    int32_t v4 = v3 - 2; // 0x100003ca8
    int32_t v5 = v4 / 2; // 0x100003cac
    int64_t v6 = (int64_t)_calloc(v5 + 1, 4); // 0x100003cc8
    if (v3 < 4 || v4 > 1 != (v5 & -v5) < 0) {
        int32_t v7 = 0;
        *(int32_t *)(4 * (int64_t)v7 + v6) = 2 * v7 | 1;
        int32_t v8 = v7 + 1; // 0x100003d14
        while (v8 - v5 == 0 || v8 - v5 < 0 != ((v8 - v5 ^ v8) & (v8 ^ v5)) < 0) {
            // 0x100003cf0
            v7 = v8;
            *(int32_t *)(4 * (int64_t)v7 + v6) = 2 * v7 | 1;
            v8 = v7 + 1;
        }
    }
    // 0x100003d2c
    if (v4 < 8 == (3 - v5 & v5) < 0) {
        int32_t v9 = 1;
        int32_t v10 = 2;
        int32_t v11 = 2 * v9; // 0x100003d74
        int32_t v12 = (v5 - v9) / (v11 | 1); // 0x100003d7c
        int32_t v13 = v9 - v12; // 0x100003d80
        int32_t v14 = v9; // 0x100003d88
        int32_t v15; // 0x100003c18
        int32_t * v16; // 0x100003dc0
        int32_t v17; // 0x100003df0
        int32_t v18; // 0x100003d80
        if (v13 == 0 || v13 < 0 != ((v13 ^ v9) & (v9 ^ v12)) < 0) {
            v15 = v14;
            v16 = (int32_t *)(4 * (int64_t)(v15 + v9 + v15 * v11) + v6);
            if (*v16 != 0) {
                // 0x100003dd4
                *v16 = 0;
            }
            // 0x100003dec
            v17 = v15 + 1;
            v18 = v17 - v12;
            while (v18 == 0 || v18 < 0 != ((v18 ^ v17) & (v17 ^ v12)) < 0) {
                // 0x100003d90
                v15 = v17;
                v16 = (int32_t *)(4 * (int64_t)(v15 + v9 + v15 * v11) + v6);
                if (*v16 != 0) {
                    // 0x100003dd4
                    *v16 = 0;
                }
                // 0x100003dec
                v17 = v15 + 1;
                v18 = v17 - v12;
            }
        }
        int32_t v19 = v10 + 1; // 0x100003d30
        int32_t v20 = 2 * v10 * v19; // 0x100003d40
        while (v5 - v20 < 0 == ((v5 - v20 ^ v5) & (v20 ^ v5)) < 0) {
            // 0x100003d5c
            v9 = v10;
            v10 = v19;
            v11 = 2 * v9;
            v12 = (v5 - v9) / (v11 | 1);
            v13 = v9 - v12;
            v14 = v9;
            if (v13 == 0 || v13 < 0 != ((v13 ^ v9) & (v9 ^ v12)) < 0) {
                v15 = v14;
                v16 = (int32_t *)(4 * (int64_t)(v15 + v9 + v15 * v11) + v6);
                if (*v16 != 0) {
                    // 0x100003dd4
                    *v16 = 0;
                }
                // 0x100003dec
                v17 = v15 + 1;
                v18 = v17 - v12;
                while (v18 == 0 || v18 < 0 != ((v18 ^ v17) & (v17 ^ v12)) < 0) {
                    // 0x100003d90
                    v15 = v17;
                    v16 = (int32_t *)(4 * (int64_t)(v15 + v9 + v15 * v11) + v6);
                    if (*v16 != 0) {
                        // 0x100003dd4
                        *v16 = 0;
                    }
                    // 0x100003dec
                    v17 = v15 + 1;
                    v18 = v17 - v12;
                }
            }
            // 0x100003d2c
            v19 = v10 + 1;
            v20 = 2 * v10 * v19;
        }
    }
    int32_t v21 = 1 - v5; // 0x100003e28
    if (v21 != 0 && v21 < 0 == (v21 & v5) < 0) {
        // 0x100003f4c
        return 0;
    }
    int32_t v22 = 1; // 0x100003e30
    int32_t v23 = 0;
    int32_t v24 = v23; // 0x100003e4c
    int64_t v25; // 0x100003c18
    int32_t v26; // 0x100003e7c
    int32_t v27; // 0x100003ea0
    int32_t v28; // 0x100003eac
    if (*(int32_t *)(4 * (int64_t)v22 + v6) != 0) {
        if (v23 % 10 == 0) {
            // 0x100003e78
            v26 = v23 - 100;
            if (v26 == 0 || v26 < 0 != (99 - v23 & v23) < 0) {
                // 0x100003e8c
                _printf("\n");
            }
        }
        // 0x100003e9c
        v27 = v23 + 1;
        v28 = v23 - 99;
        if (v28 == 0 || v28 < 0 != (v27 & 98 - v23) < 0) {
            // 0x100003ebc
            _printf("%3d ", 4);
            v24 = v27;
        } else {
            // 0x100003ee4
            v24 = v27;
            if (v27 == 0xf4240) {
                // 0x100003efc
                _printf("\n%d th prime is %d\n", 4, v25);
                return 0;
            }
        }
    }
    // 0x100003f3c
    v22++;
    while (v22 - v5 == 0 || v22 - v5 < 0 != ((v22 - v5 ^ v22) & (v22 ^ v5)) < 0) {
        // 0x100003e38
        v23 = v24;
        v24 = v23;
        if (*(int32_t *)(4 * (int64_t)v22 + v6) != 0) {
            if (v23 % 10 == 0) {
                // 0x100003e78
                v26 = v23 - 100;
                if (v26 == 0 || v26 < 0 != (99 - v23 & v23) < 0) {
                    // 0x100003e8c
                    _printf("\n");
                }
            }
            // 0x100003e9c
            v27 = v23 + 1;
            v28 = v23 - 99;
            if (v28 == 0 || v28 < 0 != (v27 & 98 - v23) < 0) {
                // 0x100003ebc
                _printf("%3d ", 4);
                v24 = v27;
            } else {
                // 0x100003ee4
                v24 = v27;
                if (v27 == 0xf4240) {
                    // 0x100003efc
                    _printf("\n%d th prime is %d\n", 4, v25);
                    return 0;
                }
            }
        }
        // 0x100003f3c
        v22++;
    }
    // 0x100003f4c
    return 0;
}

// Address range: 0x100003f5c - 0x100003f68
int64_t * function_100003f5c(int32_t nmemb, int32_t size) {
    // 0x100003f5c
    return _calloc(nmemb, size);
}

// Address range: 0x100003f68 - 0x100003f74
float64_t function_100003f68(float64_t a1) {
    // 0x100003f68
    return _log(a1);
}

// Address range: 0x100003f74 - 0x100003f80
int32_t function_100003f74(char * format, ...) {
    // 0x100003f74
    return _printf(format);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 4

