//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <math.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_100003abc(void);
int64_t function_100003c5c(void);
float64_t function_100003f64(float64_t a1);
int32_t function_100003f70(char * format, ...);
float64_t function_100003f7c(float64_t a1);

// --------------------- Global Variables ---------------------

float64_t g1 = 0.05; // 0x100003f88
float64_t g2 = NAN; // 0x100003f90
float64_t * g3 = (float64_t *)0x100000cfeedfacf; // 0x100008000
float64_t * g4 = NULL; // 0x100008f80
float64_t * g5 = NULL; // 0x100009f00
float64_t * g6 = NULL; // 0x10000ae80
float64_t * g7 = NULL; // 0x10000af80
float64_t * g8 = NULL; // 0x10000b080
float64_t * g9 = NULL; // 0x10000b180

// ------- Dynamically Linked Functions Without Header --------

float64_t _cos(float64_t a1);
int32_t _printf(char * a1, ...);
float64_t _sin(float64_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x100003abc - 0x100003c5c
int64_t function_100003abc(void) {
    // 0x100003abc
    int64_t v1; // 0x100003abc
    int32_t v2 = v1; // 0x100003ad8
    int64_t result; // 0x100003abc
    if (v2 < 1) {
        // 0x100003c4c
        return result;
    }
    float64_t * v3 = (float64_t *)(8 * (int64_t)((31 - v2) * (32 - v2) / 2 + (int32_t)v1) + v1); // 0x100003b5c
    float64_t v4 = *v3; // 0x100003b5c
    if (v4 != v4 || 0.0 != 0.0) {
        float64_t v5 = *(float64_t *)(v1 + (0x100000000 * v1 >> 29)); // 0x100003b84
        function_100003abc();
        function_100003abc();
        int64_t v6 = function_100003abc(); // 0x100003c18
        *v3 = 2 * (v5 - *(float64_t *)(v1 + (8 * 2 * v1 & 0xfffffff8))) / 0.0;
        result = v6;
    }
    // 0x100003c4c
    return result;
}

// Address range: 0x100003c5c - 0x100003d48
int64_t function_100003c5c(void) {
    // 0x100003c5c
    int64_t v1; // 0x100003c5c
    int32_t v2 = v1; // 0x100003c78
    int32_t v3 = v2 - 31; // 0x100003c80
    int64_t result; // 0x100003c5c
    if (v3 == 0 || v3 < 0 != (30 - v2 & v2) < 0) {
        // 0x100003c9c
        function_100003abc();
        function_100003abc();
        result = function_100003c5c();
    }
    // 0x100003d38
    return result;
}

// Address range: 0x100003d48 - 0x100003f64
int64_t entry_point(void) {
    int64_t v1 = 0;
    int128_t v2 = __asm_sshll(0.0f, 0); // 0x100003d7c
    int64_t v3 = 8 * v1; // 0x100003da0
    int64_t v4 = v3 + (int64_t)&g9; // 0x100003da0
    float64_t v5; // 0x100003d48
    *(float64_t *)v4 = v5 * g1;
    int64_t * v6 = (int64_t *)v4;
    float64_t v7 = _sin((float64_t)(int64_t)v2); // 0x100003dac
    int64_t v8 = v3 + (int64_t)&g7; // 0x100003dc4
    *(int64_t *)v8 = *v6;
    float64_t v9 = _cos(v7); // 0x100003dd0
    int64_t v10 = v3 + (int64_t)&g6; // 0x100003de4
    *(int64_t *)v10 = *v6;
    float64_t v11 = *(float64_t *)v8 / *(float64_t *)v10; // 0x100003df8
    *(float64_t *)(v3 + (int64_t)&g8) = v11;
    v1++;
    while (v1 != 32) {
        // 0x100003d74
        v2 = __asm_sshll(0.0f, 0);
        v3 = 8 * v1;
        v4 = v3 + (int64_t)&g9;
        *(float64_t *)v4 = v11 * g1;
        v6 = (int64_t *)v4;
        v7 = _sin((float64_t)(int64_t)v2);
        v8 = v3 + (int64_t)&g7;
        *(int64_t *)v8 = *v6;
        v9 = _cos(v7);
        v10 = v3 + (int64_t)&g6;
        *(int64_t *)v10 = *v6;
        v11 = *(float64_t *)v8 / *(float64_t *)v10;
        *(float64_t *)(v3 + (int64_t)&g8) = v11;
        v1++;
    }
    int32_t v12 = 0;
    int64_t v13 = 8 * (int64_t)v12; // 0x100003e50
    *(int64_t *)(v13 + (int64_t)&g5) = (int64_t)g2;
    *(int64_t *)(v13 + (int64_t)&g3) = (int64_t)g2;
    *(int64_t *)(v13 + (int64_t)&g4) = (int64_t)g2;
    int32_t v14 = v12 + 1; // 0x100003e7c
    while (v12 < 495 != (494 - v12 & v14) < 0) {
        // 0x100003e3c
        v12 = v14;
        v13 = 8 * (int64_t)v12;
        *(int64_t *)(v13 + (int64_t)&g5) = (int64_t)g2;
        *(int64_t *)(v13 + (int64_t)&g3) = (int64_t)g2;
        *(int64_t *)(v13 + (int64_t)&g4) = (int64_t)g2;
        v14 = v12 + 1;
    }
    // 0x100003e88
    function_100003c5c();
    _printf("%16.14f\n", v9);
    function_100003c5c();
    _printf("%16.14f\n", v9);
    function_100003c5c();
    _printf("%16.14f\n", v9);
    return 0;
}

// Address range: 0x100003f64 - 0x100003f70
float64_t function_100003f64(float64_t a1) {
    // 0x100003f64
    return _cos(a1);
}

// Address range: 0x100003f70 - 0x100003f7c
int32_t function_100003f70(char * format, ...) {
    // 0x100003f70
    return _printf(format);
}

// Address range: 0x100003f7c - 0x100003f88
float64_t function_100003f7c(float64_t a1) {
    // 0x100003f7c
    return _sin(a1);
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

